### ISSUE TITLE
Bad link in Readme.md

### ISSUE THREAD

**Issue by KardonskyRoman** [vaadin/hilla#1001]
https://hilla.dev/docs/tutorials is now working

**Comment by tarekoraby** [comment]
Thanks, @KardonskyRoman. But how did you generate/find the project that includes this README? (A project generated using the CLI doesn't show this link to me).

**Comment by KardonskyRoman** [comment]
This link provided in official hilla project in github

пт, 2 июн. 2023 г., 13:12 Tarek Oraby ***@***.***>:
