### ISSUE TITLE
How to create own 403 and 404 error pages?

### ISSUE THREAD

**Issue by egloffmark** [vaadin/hilla#1014]
I like to understand how I need to configure hilla routes for serving own 403 and 404 error pages in case location or URLs get accessed which does not exists or get denied by the Server (e.g. due VaadinWebSecurity configuration) ? Can you may be explain how this need to be configured? Thank you

The standard Article about Navigation and Routes does not contain such a section. 
https://hilla.dev/docs/lit/guides/routing

**Comment by platosha** [comment]
Thanks for pointing this out.

For now until the documentation is updated, you can:
- Use redirects for the 403 page
- Add a catch-all route as the last item to show the 404 response: `{path: '(.*)', component: 'x-not-found-view'},`

**Comment by egloffmark** [comment]
Thank you, that is what I have been looking for. Regards
