### ISSUE TITLE
Redirected Routes in Hilla ignores "authenticated" settings in VaadinWebSecurity with SpringBoot 3.0

### ISSUE THREAD

**Issue by egloffmark** [vaadin/hilla#1015]
### Description of the bug 
I try to define for my Hilla Web App an "admin" backend and like to protect the incoming request at server side by using VaadinWebSecurity and "requestMatchers". All other requests should be permitted. When I now creates "routes" at the client site for Hilla, and uses "redirects" for my admin section I noticed that that the WebSecurity config which I specified in VaadinWebSecurity Config gets bypassed. 

This I think should not be the case, I expect when you create "redirects" it should still be validated by the  VaadinWebSecurity and stopped or redirected to the login page.

### Minimal reproducible example

Take the offical hilla-auth example and extend the Security Config and add some extra views and routes.

**ServerSide Spring Security**

```
@EnableWebSecurity
@Configuration
@Slf4j
public class SecurityConfig extends VaadinWebSecurity {

    // create file "config/secrets/application.properties"
    // use this command to generate new random secret for your app:
    // openssl rand -base64 32
    @Value("${com.example.application.app.secret}")
    private String appSecret;

    @Override
    protected void configure(HttpSecurity http) throws Exception {

    	http.authorizeHttpRequests((authz) -> {
			authz.requestMatchers("/admin/**").authenticated();
			authz.requestMatchers("/**").permitAll();
    	}); 	
    	
        super.configure(http);
        
        http.sessionManagement()
                .sessionCreationPolicy(SessionCreationPolicy.STATELESS);
        
        log.info("appSecret: {}",appSecret);
        
        setStatelessAuthentication(
        		http,
                new SecretKeySpec(Base64.getDecoder().decode(appSecret), JwsAlgorithms.HS256),
                "com.example.application");
        
        setLoginView(http, "/login","/");
    }
    
   ....
```
**Client Side "routes" in Hilly Typescript Config**
```
export const routes: ViewRoute[] = [
  {
    path: '',
    component: 'hello-view',
    action: async (_context, _command) => {
      await import('./views/hello/hello-view');
      return;
    },
  },
  {
    path: '/admin/main',
    component: 'main-view',
    action: async (_context, _command) => {
      await import('./views/admin/main-view');
      return;
    },
  },
  // Create a redirect to a protected view 
  {
    path: '/main',
    redirect: '/admin/main'
  },
  {
    path: '/login',
    component: 'login-view',
    action: async (_context, _command) => {
      await import('./views/login/login-view');
      return;
    },
  },
];
```
When you now access the following paths in your browser

-  path "/"  calls "hello-view" and serves it as expected 
-  path "/admin/xxxx"  redirects to "/login"  because the "admin/**" policy in WebSecurity defines it as protected view. This is fine and works as expected.
- path "/main" gets redirected at client side to "/admin/man" and get served without checking the WebSecurity. Here I would expect that the user get rerouted to "/login".

### Expected behavior
When user enters a path which redirects to a protected view then the WebSecurity should redirect it to the "login" page

### Actual behavior
When user enters a path which redirects to a protected view then the WebSecurity policies get "ignored" and the protected view get served.

### Versions:
    - Vaadin / Hilla version: 2.0.2
    - Node version:  16.15.1
    - Spring Boot Version:  3.0.5
    - Java version: 17
    - OS version: Linux Mint 21.3 
    - Browser version: Firefox 113.02

**Comment by ahsinsiddique** [comment]
Probably you can try using action on `/main` path as well 

` action: async (_context, _command) => {
      await import('./views/hello/hello-view');
      return;
    },`

**Comment by platosha** [comment]
The security config on the server by design does not affect the client-side navigation redirect. Use additional client-side check in the route to prevent access, for example, with action:

```typescript
    action: async (_context, _command) => {
      if (!hasAccess(_context.route)) {
        return _command.redirect('login');
      }
      return;
    },
```

**Comment by Artur-** [comment]
With Hilla you should, like with React and other frameworks, mainly aim to protect the data and not the views. An app should preferably be built so that getting access to the view templates is not a security risk.

To be able to actually protect views which are implemented client side, you need to prevent sending of the JS containing the view implementation to the browser unless the user has proper access. If you send the JS, then any router configuration does not matter as everything that is client side can be bypassed.
