### ISSUE TITLE
Input Fields: Link not working for corresponding article on vaadin.com

### ISSUE THREAD

**Issue by ahsinsiddique** [vaadin/hilla#1018]
When I click on this provided link for detailed information on vaadin.com, then I see page not found. 

<img width="1314" alt="Screenshot 2023-06-12 at 12 32 08 AM" src="https://github.com/vaadin/hilla/assets/20045689/3bc9327b-92ba-4597-96e6-f3f8886b32a9">

https://hilla.dev/docs/react/components/input-fields

Expected behaviour: Link should navigate to correct path for input field detailed information

**Comment by taefi** [comment]
Nice catch! It seems that the docs structure changed between the v23 and latest, and that generic article about input-fields is missing.

**Comment by taefi** [comment]
Closed by vaadin/docs#2573
