### ISSUE TITLE
Generic EndpointError is thrown for an unauthorized call to endpoints with different role

### ISSUE THREAD

**Issue by platosha** [vaadin/hilla#1023]
### Description of the bug 

Accessing endpoints with insufficient role compared to what is declared in `@RolesAllowed` results in generic `EndpointError` on the client side instead of the specific `ForbiddenResponseError`.

### Minimal reproducible example

- Create a Hilla application with authentication enabled.
- Mark an endpoint with `@RolesAllowed("ROLE_ADMIN")`
- Call the endpoint while logged in as a normal user

### Expected behavior

The endpoint call rejects with `ForbiddenResponseError`.

### Actual behavior

The endpoint call rejects with `EndpointError`.

### Versions:
    - Vaadin / Hilla version: 2.1
    - Node version:
    - Java version:
    - OS version:
    - Browser version (if applicable):
    - Application Server (if applicable):
    - IDE/Editor (if applicable):

**Comment by taefi** [comment]
One can argue that exposing the fact that there is a resource available on the server that the user cannot access it with their current roles/permissions is opening a door for security attacks. 

We may consider refining our responses to the standards of Rest APIs, e.g. returning a 404 for unauthorized or forbidden cases. Not sure whether a different response during development vs. production can help with the DX either.

**Comment by cromoteca** [comment]
This is a regression compared to 1.3. Now a valid JSON is returned which has priority when handling exception types.
