### ISSUE TITLE
PiT 24.2: Hilla 2.2.0.alpha1 project build on windows failed 

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/hilla#1072]
building hilla starter with 2.2.0.alpha1 failed with the following error

![image](https://github.com/vaadin/hilla/assets/31067185/604b9f07-5a95-45d7-bfaa-6f058f6207cd)

step to reproduce:
- clone `v2.2` branch from https://github.com/vaadin/skeleton-starter-hilla-lit
- update to use hilla `2.2.0.alpha1`
- run `mvn`

related discussion on slack https://vaadin.slack.com/archives/CDNTYMS9H/p1687861324389489

**Comment by platosha** [comment]
See also: #1073 for testing on Windows
