### ISSUE TITLE
the build fail because of generated frontend code

### ISSUE THREAD

**Issue by abdenassar01** [vaadin/hilla#1098]
When I try to build a production ready jar file using 

` mvn package -Pproduction`

or 

`mvn clean package -Pproduction`

or even in the dev mode an error keep showing in the dev tools saying that the generated methods for http status code starts with a number like 4xxClientError() and 3xxClientError()... is there any way I can solve this or just ignore the error during build because I've ignored it in dev mode and was working with no problems.

frontend/generated/org/springframework/http/HttpStatusCode.ts(2,6): error TS1351: An identifier or keyword cannot immediately follow a numeric literal.

# Screenshot
_errors in console_
![img](https://i.imgur.com/txihpDk.png)

_generated code by hilla_
![generated code by hilla](https://i.imgur.com/834lCbz.png)

### Versions:
    - Vaadin / Hilla version:
    - Node version: v18.16
    - Java version: java 11
    - OS version: fedora workstation 38
    - Browser version (if applicable):
    - Application Server (if applicable):
    - IDE/Editor (if applicable): Intelij

**Comment by marcushellberg** [comment]
A TypeScript function name cannot start with a number. According to the ECMAScript specification, function names must start with a letter, an underscore (_), or a dollar sign ($). 

Looks like we should have some check for that. 

As a workaround, maybe you can prefix your method names, like `getHttp5xxServerError`

**Comment by abdenassar01** [comment]
I can't prefix them. the names are generated by hilla plugin. may be I just don't know how. any way I will be grateful if you could guide me sir.

**Comment by marcushellberg** [comment]
They are generated based on the methods in your Java class, you need to change them there.

**Comment by abdenassar01** [comment]
I don't have methods for http status code. maybe because I return Response entity each time? if so is there any way I can fix that without changing the return type in all the methods?

**Comment by marcushellberg** [comment]
You can think of Hilla endpoint methods as RPC. You should not return Response entities from them, only the actual return value. 

Instead of checking HTTP statuses for errors when calling, you can look at the exception type https://hilla.dev/docs/lit/guides/endpoints/#error-handling

**Comment by abdenassar01** [comment]
Thank you sir for your help. I'll consider refactoring my backend code.
