### ISSUE TITLE
Failed to configure Hilla engine (using gradle in Windows)

### ISSUE THREAD

**Issue by Cieszlunek** [vaadin/hilla#1106]
Hi, while running the `vaadinBuildFrontend` Gradle task in the project described on your page (https://hilla.dev/docs/react/start/gradle), I encountered an exception.

The stacktrace indicates that the exception is caused by `com.vaadin.flow.server.ExecutionFailedException: Failed to configure Hilla engine`.

The root cause of this issue is that somewhere in this task, there is a check command being executed:
`./gradlew.cmd -v`
However, there is no `gradlew.cmd` script, but rather a `gradlew.bat` script.

To resolve this, you can simply copy the `gradlew.bat` script and rename it to `gradlew.cmd`.

I'm unsure about the best solution for this problem, but I couldn't find any. If you'd like, I can create a pull request (PR) to update the documentation with this information.

**Comment by cromoteca** [comment]
Which Hilla version are you using? This has been fixed in https://github.com/vaadin/hilla/pull/1064 and https://github.com/vaadin/hilla/pull/1068.

**Comment by platosha** [comment]
The fix (#1068) was released in 2.1.2.
