### ISSUE TITLE
DevTools auto reload of endpoint changes is unreliable

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/hilla#1139]
### Description of the bug 
When updating Endpoint and building the project the reload process is unreliable. 

It works sometimes, but often on of the following happens:
- A blank page is displayed and you need to refresh manually
- The browser displays an error after changing the backend API signature, but VS code shows no errors
- No errors are shown in either browser or IDE after changing the backend API even though it should cause a compile error.

### Minimal reproducible example
I haven't been able to reproduce reliably, but it has happened consistently in demos.

### Expected behavior
The change should be reloaded reliably. 

### Actual behavior
See above.

### Versions:
    - Vaadin / Hilla version: 2.0
    - Node version: 18
    - Java version: 17

**Comment by Legioth** [comment]
There might be multiple different underlying issues causing these symptoms. One of those, https://github.com/vaadin/hilla/issues/1134, was closed recently.

**Comment by platosha** [comment]
@marcushellberg is this something still happening in the demos?

**Comment by platosha** [comment]
Should be addressed by https://github.com/vaadin/flow/pull/18018
