### ISSUE TITLE
React Form Binder: the submitting property missing in the BinderNodeControls type

### ISSUE THREAD

**Issue by taefi** [vaadin/hilla#1164]
### Description of the bug 
While evaluating the React Form Binder, it seems that the `submitting` property missing in the `BinderNodeControls` type.

### Minimal reproducible example
Simply, the following won't compile:
```TSX
const { submitting } = useBinder(EntityModel);
```

### Expected behavior
To have the submitting property available in the Binder similar to the Lit Binder API.

**Comment by Inmoresentum** [comment]
Please fix it already :)
