### ISSUE TITLE
React Form Binder: compilation error while trying to call useBinderNode hook

### ISSUE THREAD

**Issue by taefi** [vaadin/hilla#1177]
### Description of the bug 

When trying to obtain the binder node for a specific field using `useBinderNode` hook, assuming that the field is of type string, there is a compilation error such as:
> Argument of type 'StringModel' is not assignable to parameter of type 'AbstractModel<unknown>'.

Workaround: Use `// @ts-ignore` since it works as intended at runtime
Or, to use the `useBinderNode` with the generic arguments for now, e.g. `useBinderNode<string, StringModel>(...)`.

**Comment by platosha** [comment]
Fixed by #1178
