### ISSUE TITLE
Childendpoints from a typed @EndpointExposed Baseclasses have wrong method parameter types

### ISSUE THREAD

**Issue by AirbornePanda** [vaadin/hilla#1214]
### Description of the bug 
When you have a typed Endpoint annotated with @EndpointExposed and multiple children extend this endpoint, it is possible that wrong method parameters are used for the second and later endpoints if they have the same method name.
### Minimal reproducible example

Have a typed exposed endpoint with the type as a method parameter:
```
@EndpointExposed
public abstract class BaseEndpoint<T> {

    public String getAll(T param) {
        return null;
    }

}
```

Then have two endpoints extending the baseendpoint with different types:

```
@Endpoint
@AnonymousAllowed
public class HelloWorldEndpoint extends BaseEndpoint<String>{

}
```

```
@Endpoint
@AnonymousAllowed
public class SecondEndpoint extends BaseEndpoint<Long>{
}
```

Now generate the endpoints. Both endpoints have the same method parameter type:

HelloWorldEndpoint.ts

`async function getAll_1(param: number | undefined, init?: EndpointRequestInit_1): Promise<string | undefined> { return client_1.call("HelloWorldEndpoint", "getAll", { param }, init); }`

SecondEndpoint.ts
`async function getAll_1(param: number | undefined, init?: EndpointRequestInit_1): Promise<string | undefined> { return client_1.call("SecondEndpoint", "getAll", { param }, init); }`

This only happens with methods from the baseclass. If both endpoints implement their own methods, they have the correct parameter types. 

Reproducable Repo:

https://github.com/AirbornePanda/hilla_endpoint_error_example

### Expected behavior
The get_All function of the HelloWorldEndpoint.ts should have string as method parameter type.
### Actual behavior
The get_All function of the HelloWorldEndpoint.ts has number as method parameter type.
### Versions:
    - Vaadin / Hilla version: 2.2.0.beta1
    - Node version: v18.16.1
    - Java version: 19
    - OS version: Win 10
    - Browser version (if applicable): Irrelevant
    - Application Server (if applicable): Spring Boot
    - IDE/Editor (if applicable): IntelliJ

**Comment by Artur-** [comment]
Seems like it combines the method already when generating `openapi.json` as it contains
```
  "paths" : {
    "/ShouldGetAndReturnLong/getAll" : {
      "post" : {
        "tags" : [
          "ShouldGetAndReturnString"
        ],
        "operationId" : "ShouldGetAndReturnString_getAll_POST",
```

**Comment by AirbornePanda** [comment]
Wow that was a fast response and fix. Thank you!
