### ISSUE TITLE
Update starters to use new @hilla/react-auth package

### ISSUE THREAD

**Issue by sissbruecker** [vaadin/hilla#1349]
We need to update starters to use the new `@hilla/react-auth` package. This involves:
- Removing the boilerplate auth code from starters
- Using `@hilla/react-auth` instead
- If we want to support a prerelease version of starters that include the new package:
  -  Update auth API in starter boilerplate so that it matches the API from `@hilla/react-auth`
  - Dynamically change imports to use either boilerplate or `@hilla/react-auth`

**Comment by cromoteca** [comment]
Honestly, update the auth API boilerplate looks like doing the package again to me. Given the complexity, I'd wait for 2.3 to be stable before working on this issue.

**Comment by sissbruecker** [comment]
Sure, but if we find a prerelease valuable we could just straight-up copy over the auth package into the starter and get the same API with little effort.

**Comment by sissbruecker** [comment]
This has been resolved with https://github.com/vaadin/start/pull/2795
