### ISSUE TITLE
Be able to do Fusion code generator on application startup

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/hilla#137]
Currently, with the new generator, I need to run a maven to do the code generator. As a developer, I want to have the same behavior as the old generator so that when the application starts, the code is generated automatically for me, so that I don't have to run a specific goal manually.

**Comment by Artur-** [comment]
Keep in mind that you typically start the app by launching the `Application` class and not run Maven at all

**Comment by haijian-vaadin** [comment]
> Keep in mind that you typically start the app by launching the `Application` class and not run Maven at all

Yep, thanks for the remind, plan to go with the way that having a code generation task for NodeTasks, which is called by `DevModeInitializer`, the code generation task simply invokes the mvn command, e.g. `mvn fusion:generate`. If it's a Gradle project, we can invoke the gradle command. 

Does the solution also sound to you? Or do you see some problems? @Artur-

**Comment by cromoteca** [comment]
Waiting for #414 as ITs will probably fail at the beginning when the multi-module generator is enabled
