### ISSUE TITLE
Add support for Gradle

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/hilla#141]
The new generator is now done as a maven plugin, we should also support Gradle users, we need a `fusion-gradle-plugin` for this.

**Comment by jonas-tm** [comment]
I was looking into setting up Kotlin + Hilla project based on @marcushellberg sample [here](https://github.com/marcushellberg/hilla-kotlin).
However, using Maven with Kotlin always feels a bit odd to me.

Would love if we would also get a Gradle plugin for Hilla.

**Comment by marcushellberg** [comment]
Agreed. As far as I know, we have this on the backlog, but not sure of when we'll get it done.

**Comment by multicaststorm** [comment]
We are heavily invested in Gradle, So this would be great news for our plans to adopt Hilla

**Comment by kjordan2001** [comment]
Is there any timeline for this?  Given that the Vaadin Gradle plugin will no longer generate endpoint typescript code, this kind of breaks anyone trying to upgrade to 24 that's using @Endpoints.

**Comment by platosha** [comment]
Hi, we have recently prioritised this in our roadmap for the upcoming Hilla 2.1 release, which is scheduled for June 2023. Please stay tuned.

**Comment by KotlinFactory** [comment]
Gradle would be much appreciated
