### ISSUE TITLE
[autocrud] Provide your own form layout

### ISSUE THREAD

**Issue by Artur-** [vaadin/hilla#1423]
It should be possible to use a custom layout for the form so you can make the usability better for the end user

**Comment by taefi** [comment]
Does it mean that the developer will be provided a way to define how the fields should be ordered and placed in the form? 
Such as a json like this:
```json
{ "layout": [
        ["name", "family", "dateOfBirth"],
        ["country", "city", "zipCode"],
        ["streetAddress1"],
        ["addressLine"],
        ["tel", "email"],
        ["additionalInfo"]
    ]
}
```

Or just to have some default predefined layouts such as:
* oneFieldPerRow
* twoFieldPerRow
* ...

**Comment by sissbruecker** [comment]
I think before we start with high-level abstractions, let's first provide a way to write your own form layout UI component while providing access to the form's data and behavior. With how the binder works there really isn't a lot of overhead putting together a declarative layout.

```tsx
function CustomFormLayout() {
  const { binder, model } = useContext(AutoFormContext);

  return (
    <TextField label="Name" {...binder.field(model.name)} />
    <DatePicker label="Date" {...binder.field(model.date)} />

    ...

    <Button onClick={binder.submit}>Save</Button>
  );
}
```

Additionally we could expose some of our internal abstractions, for example an `AutoFormTextField` which brings auto-configuration (label, disabled state, binding value) while still allowing you to customize individual props:

```tsx
<AutoTextField property="name" label="Custom label" />
```
