### ISSUE TITLE
Consider annotated getters in the generation of TS models

### ISSUE THREAD

**Issue by simasch** [vaadin/hilla#146]
JPA and Jackson lets you set annotations on getters instead of fields.

**JPA**
For JPA that means if the getter has an annotation the field should not be used.

This can also be specified setting the `AccessType` with the `Access `annotation: https://javaee.github.io/javaee-spec/javadocs/javax/persistence/Access.html 
In that case the defined AccessType should be used to access the state of the entity.

**Jackson**
Jackson has the JsonProperty, JsonGetter and JsonSetter annotations. 
If these are used then also getter or setter should be used instead of the field.

Why do we want to use that?

There could be the case that we want to serialize a calculated field that is calculated in the getter of the DTO or Entity.
For example if we have a Order we want to calculate the total price of the order and serialize that to the client.

**Comment by platosha** [comment]
Added in PR #720
