### ISSUE TITLE
getPropertyIds in property-info does not consider parent models

### ISSUE THREAD

**Issue by Artur-** [vaadin/hilla#1486]
### Describe the bug

getPropertyIds should return the property ids of the model, including all property ids of the parent model.

Currently you cannot delete an item in AutoCrud if it looks like
```java
public class User extends AbstractEntity {

    private String username;
}
```

```java
public abstract class AbstractEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "idgenerator")
    // The initial value is to account for data.sql demo data ids
    @SequenceGenerator(name = "idgenerator", initialValue = 1000)
    private Long id;
}
```

because the `id` property is not found

### Reproduction

-

### System Info

main branch

**Comment by cromoteca** [comment]
Fixed in https://github.com/vaadin/hilla/pull/1586
