### ISSUE TITLE
[autogrid][dx] Enable multi-column sorting

### ISSUE THREAD

**Issue by taefi** [vaadin/hilla#1509]
### Describe your motivation

Having the multi-column sorting enabled by default is a nice feature to have.
Then, there could be a way to disable sorting completely, or fall back to single column sorting based on developer discretion.

**Comment by tarekoraby** [comment]
I think @sissbruecker's [argument against enabling multi-sorting by default ](https://github.com/vaadin/hilla/pull/1510#issue-1936237905) makes sense

> I did not enable multi-sort by default, as I found it quite bothersome that you first have to remove sort from one column (two clicks) if you just want to sort a different column (third click). 

Also, as discussed in one of the dailies, let's aim to be consistent with the default Grid behavior whenever possible (where multi-sorting is not the default). 

We should, however, provide an option to enable it as an opt-in.
