### ISSUE TITLE
[autocrud] support i18n for grid column titles and form field labels

### ISSUE THREAD

**Issue by taefi** [vaadin/hilla#1569]
### Describe your motivation

This could be done in the following steps

- [ ] Enable `<AutoGrid />` to support i18n column titles 
- [ ] Enable `<AutoForm />` to support i18n field labels
- [ ] Enable `<AutoCurd />` to support i18n titles and automatically provide them for the underlying `<AutoGrid />` and `<AutoForm />`

**Comment by platosha** [comment]
Mostly done. Let's create another issue for the remaining i18n todos.
