### ISSUE TITLE
Improve the Starting the Application doc

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/hilla#157]
There are a few improvements for the [Starting the Application](https://vaadin.com/docs/latest/fusion/application/starting) doc
1. Remove the Experimental feature warning box, as the bootstrapping won't change in the coming LTS
<img width="656" alt="Screen Shot 2021-12-20 at 14 52 22" src="https://user-images.githubusercontent.com/30408303/146889696-cf6c0e90-61cb-4a56-bea1-232cc47ab3ad.png">

2. The article seems to be for how to do client-side bootstrapping in a Flow app, not quite what a Fusion user needs. We can split the doc into 2 articles, keep the bare minimum for starting a Fusion application in this article, and move the Flow related to a separate article like `Integrate with Flow/Java views`.

**Comment by platosha** [comment]
The content in docs was restructured, so this issue is not relevant anymore.
