### ISSUE TITLE
`react-crud` in Hilla 2.3 depends on RC versions of React Components and Lumo

### ISSUE THREAD

**Issue by cromoteca** [vaadin/hilla#1575]
### Describe the bug

This causes `Tried to define vaadin-lumo-styles version 24.2.0 when version 24.2.0-rc1 is already in use. Something will probably break.`

### Reproduction

See https://github.com/vaadin/hilla/blob/a7eb92e82d895ae1ff0e203cd032922b62d30ff0/packages/ts/react-crud/package.json#L51-L53

### System Info

Hilla 2.3.1

**Comment by cromoteca** [comment]
This is also visible in the dev tools:
![image](https://github.com/vaadin/hilla/assets/498086/55bee484-00d2-4fd2-9b9b-6a1004c4754f)

**Comment by Artur-** [comment]
Fixed by #1585
