### ISSUE TITLE
[autogrid] show properties from parent classes

### ISSUE THREAD

**Issue by cromoteca** [vaadin/hilla#1579]
### Describe your motivation

When using AutoGrid in the Pet Clinic applications, veterinarians don't have first and last name since they come from the `Person` parent class. They should be available in the grid by default.

See https://github.com/cromoteca/hilla-petclinic/blob/10fc9164cbb29629b35bebe8e2cdf52ab86bdd4d/src/main/java/org/springframework/samples/petclinic/vet/Vet.java#L46

Hilla 2.3.1

**Comment by platosha** [comment]
Implementation tip: to get the definitions from the model object hierarchy, iterate the prototype chain using `Object.getPrototypeOf(...)`. Here is an example: https://github.com/vaadin/hilla/blob/12c79d494c84857ba0b2627d4f6b3738b0d77112/packages/ts/form/src/Models.ts#L152-L163

**Comment by tarekoraby** [comment]
Should this be closed?
