### ISSUE TITLE
[autocrud] Allow passing grid and form options via auto crud props

### ISSUE THREAD

**Issue by sissbruecker** [vaadin/hilla#1614]
It should be possible to pass options to the internal auto grid and form via the props of the auto crud. For example:
```tsx
<AutoCrud 
  service={PersonService} 
  model={PersonModel}
  gridProps={{ visibleColumns: [...] }} 
  formProps={{ customLayout: {...} }}
/>
```

**Comment by tarekoraby** [comment]
Wouldn't it be better if the user would deal directly with the `AutoCrud`? For example, so that they can do 
```tsx
<AutoCrud
  service={ProductService}
  visibleColumns={[...]}
/>
```

**Comment by sissbruecker** [comment]
I suggested using nested objects to avoid conflicts if grid and form use a prop with the same name at some point. You could also argue that it's easier to figure out what's going on in each part of the CRUD.

**Comment by tarekoraby** [comment]
I worry that it's not super clear to the end user that the AutoCrud component consists of an AutoGrid component + form. For the end user (I suspect), it would be more intuitive to do things like column manipulation directly on the AutoCrud.

**Comment by sissbruecker** [comment]
Added https://github.com/vaadin/hilla/issues/1648 as a follow-up for introducing possible convenience APIs.
