### ISSUE TITLE
(CI) create a job that updates `package(-lock).json` files

### ISSUE THREAD

**Issue by cromoteca** [vaadin/hilla#1623]
In https://github.com/vaadin/hilla/pull/1536 we've seen that having outdated `package(-lock).json` files causes excessive delay in PR validation, when not timeouts.

It would be great to run a nightly job that runs the full build and validation process, with a long timeout, and then, if the build passes, creates a PR with the changes generated by that build.

Then we can manually approve and merge those PRs.

**Comment by cromoteca** [comment]
Ideally this should run after new snapshots are created.

**Comment by cromoteca** [comment]
There should also be a way to either not run this if a PR already exists, or close the old one.

**Comment by cromoteca** [comment]
Actually, this could also happen in the build that creates snapshots, to avoid running other stuff. That build already runs all the needed commands, including `mvn verify`.

**Comment by platosha** [comment]
Done.
