### ISSUE TITLE
[autogrid] Horizontal scrolling throws Uncaught TypeError 

### ISSUE THREAD

**Issue by taefi** [vaadin/hilla#1641]
### Describe the bug

Whenever an AutoGrid has horizontal scrollbar visible (e.g. due having more columns than the width allows), trying to move the scrollbar (even for 1 px) is throwing the following error:

(Same stacktrace, but different error message)

In Chrome:
```
vaadin-grid-scroll-mixin.js:324 Uncaught TypeError: Cannot read properties of undefined (reading 'offsetLeft')
    at Grid.__isColumnInViewport (vaadin-grid-scroll-mixin.js:324:1)
    at Grid._predictFocusStepTarget (vaadin-grid-keyboard-navigation-mixin.js:690:1)
    at Grid._onFocusIn (vaadin-grid-keyboard-navigation-mixin.js:806:1)
```

In FireFox:
```
Uncaught TypeError: column._sizerCell is undefined
    __isColumnInViewport vaadin-grid-scroll-mixin.js:324
    _predictFocusStepTarget vaadin-grid-keyboard-navigation-mixin.js:690
    _onFocusIn vaadin-grid-keyboard-navigation-mixin.js:806
```

The grid itself remains functional.

### Expected-behavior

To support horizontal scrolling without any errors.

### Reproduction

- Get the demo source code: `git clone https://github.com/taefi/auto-form-demo`
- Run the application: `mvn`
- Navigate to the `Crud` view
- Try using the horizontal scrollbar

Look the browser's console or the devtools:

Chorme:
![Screenshot 2023-11-02 at 14 23 23](https://github.com/vaadin/hilla/assets/70698630/6a9a371d-6a4f-4ea7-86e8-f06db3a37bef)

FireFox:
![Screenshot 2023-11-02 at 14 28 36](https://github.com/vaadin/hilla/assets/70698630/25653896-5677-4fee-8c0b-56694fcfcb33)

### System Info

Hilla: `2.3.2` and also `2.4.0.alpha3`
Browser: Chrome, FireFox

**Comment by DiegoCardoso** [comment]
Related with https://github.com/vaadin/web-components/issues/6724

Seems like a regression introduced by https://github.com/vaadin/web-components/pull/6406
