### ISSUE TITLE
Changes in package.json are discarded

### ISSUE THREAD

**Issue by baianux** [vaadin/hilla#1643]
### Describe the bug

Adding new packages to the package.json are discarded when run the project.

### Expected-behavior

Allow to use any other dependencies.

### Reproduction

Add a package to the package.json and run the project via `./mvnw` or `Application` class.

### System Info

macOS 13.5.2
Hilla 2.3.2
Brave browser 1.58.135

**Comment by Artur-** [comment]
Please use e.g. `npx @hilla/cli init my-hilla-app` to create an example project where this happens and include instructions on how to reproduce it

**Comment by tarekoraby** [comment]
I cannot reproduce in a new 2.3.2 project.

**Comment by baianux** [comment]
I'm sorry, my mistake. Some weird thing while replacing with Vue.js
