### ISSUE TITLE
[autocrud] Add way to refresh grid from outside of autocrud

### ISSUE THREAD

**Issue by krissvaa** [vaadin/hilla#1657]
### Describe your motivation

Add way to refresh grid from outside of AutoCrud component.
AutoCrud can be used in place of AutoGrid and there are many use case when grid (now crud component) should refresh content. 

Refresh should only refresh Grid part of the component. 

### Describe the solution you'd like

It should be same as AutoGrid `refreshTrigger` property
Either implemented in `gridProps` or component itself
`<ExperimentalAutoCrud service={UserService} model={UserModel}
 gridProps={{ refreshTrigger: 1 }} />`
or
`<ExperimentalAutoCrud service={UserService} model={UserModel} refreshTrigger={1}/>`

**Comment by platosha** [comment]
Addressed in #1769
