### ISSUE TITLE
[autogrid] Improve UX of operator selection in header filters

### ISSUE THREAD

**Issue by sissbruecker** [vaadin/hilla#1663]
Header filters for numeric and date / time properties contain a select for choosing the operator (equal, greater than, less than). The select is currently a separate control before the actual filter value:

<img width="239" alt="Bildschirmfoto 2023-11-07 um 11 10 06" src="https://github.com/vaadin/hilla/assets/357820/da4b07b3-7a58-44e5-8428-b3101fe36d53">

We should consider moving the select into the prefix slot of the filter field instead:

<img width="214" alt="Bildschirmfoto 2023-11-07 um 11 12 44" src="https://github.com/vaadin/hilla/assets/357820/6cec5f3a-287b-4625-8df1-22e81a01c5fd">

That results in a more coherent UI and also reduces the size of the filter a bit. We should also make sure that the select uses proper aria labels to identify the select as the part of the filter that selects the operator.

**Comment by tarekoraby** [comment]
What does @rolfsmeds think about this?

**Comment by rolfsmeds** [comment]
I proposed this actually 😁

**Comment by platosha** [comment]
We have a good compromise already: removed the margin, but not using a prefix yet.
