### ISSUE TITLE
[autoform] simplify basic form layout settings 

### ISSUE THREAD

**Issue by platosha** [vaadin/hilla#1678]
It seems that the multi-dimensional template API is not something that we want to support for a long run. At the same time, exposing the renderer for the form layout does not cover simple cases well, such as:

- Defining which fields are visible
- Defining the order of the fields
- Changing the number of columns

Let us replace the form layout template API and our custom layout mechanism with the default `<FormLayout>` and these two properties in `<AutoForm>`:

- `visibleFields: string[]` that defines the list of visible fields and the order of them in the default `<FormLayout>`
- `formLayoutProps` that gets passed down to the default `<FormLayout>` that renders the field list.

Aside from this, let us keep the `fieldOptions` property for passing the props to the individual field components. Make sure that `colspan` could be defined using `fieldOptions`.

In addition, rename `customLayoutRenderder` to `layoutRenderer`. The only supported value format in this property should be the callback / component.

**Comment by Lodin** [comment]
What if instead of a lot of small properties we just create a single entrypoint for behavior extension? It could look like the following.

```ts
<AutoForm layout={(fields, props) => {
  // visible fields
  const preparedFields = fields.filter((field) => !field.name.includes('secret'))
  // order
  .sort((aField, bField) => someCustomSorting(a, b)).map((field) => {
    if (field.name === 'password') {
      <SomeSpecificPasswordComponent {...props} />
    }
    
    const DefaultComponent = field.constructor;
    return <DefaultComponent {...field} />;
  });

  return <FormLayout {...props}>{preparedFields}</FormLayout>
}} />
```
