### ISSUE TITLE
Make it possible to cancel endpoint requests

### ISSUE THREAD

**Issue by rna2i** [vaadin/hilla#169]
**Is your feature request related to a problem? Please describe.**
We have a few use cases where we fetch large data sets through an endpoint. This is initiated by a user making a selection in a grid. However, if the user selects a different row in the grid, we are making a new set of requests (based on that selection) but cannot cancel the previous requests that might not have been completed yet.

Potentially, the connections (that we wish to cancel), are prohibiting the next set of requests from being initialized as fast as possible, since the browser is limited in how many active connections it can create per host.

**Describe the solution you'd like**
Marcus Hellberg suggested in Discord to add support for AbortController:
https://developer.mozilla.org/en-US/docs/Web/API/AbortController

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Lodin** [comment]
Thanks for the issue!

To solve it, we are thinking about a solution that we are going to implement. Each endpoint method should have an optional `controller` parameter that accepts the `AbortController` created by the user. In the code generated by the framework it will look like the following:

```ts
async function _nullableString(
  nullableParameter: string | undefined,
  controller?: AbortController,
): Promise<string | undefined> {
  return client_1.call("MyEndpoint", "nullableString", { nullableParameter }, controller);
}
```

**Comment by Legioth** [comment]
Would it make more sense to keep the API aligned with `fetch()` so that you would pass `{ signal }` instead of the abort controller itself?

In addition to being aligned with the native API, it would also give the opportunity to later on introduce other properties in addition to `signal` in the object that gets passed as the last parameter without introducing any breaking changes (or weirdness with different types supported for the last parameter).

**Comment by sveine** [comment]
> Would it make more sense to keep the API aligned with `fetch()` so that you would pass `{ signal }` instead of the abort controller itself?
> 
> In addition to being aligned with the native API, it would also give the opportunity to later on introduce other properties in addition to `signal` in the object that gets passed as the last parameter without introducing any breaking changes (or weirdness with different types supported for the last parameter).

I think so! Would it look something like this:
```Typescript
function _getPoiSymbols(
 ids: Array<number>,
 options?:{fetch?: RequestInit}
): Promise<Array<PoiSymbol>> {
 return client.call('MapEndpoint', 'getPoiSymbols', {ids});
}
```

```Typescript
let abortController = new AbortController();
let signal = abortController.signal;
return MapEndpoint.getPoiSymbols(ids, {fetch: {signal}}).then(poiSymbols => {
...
```

**Comment by Legioth** [comment]
I was thinking of `TheEndpoint.theMethod(regularArgument, {signal});` since none of the other configuration parameters for `fetch()` (e.g. choosing the HTTP verb or controlling caching) would seem to be particularly applicable in this context.

**Comment by sveine** [comment]
I could not wait for this to be fixed when I could create a immediate workaround. It is necessary to cancel fetch of Mapping data if user has slow network and/or is panning very fast. In interactive search too. My hack is close to the solution by @Legioth, and I can tell that it is working as expected. Currently I am patching node_modules/@hilla/frontend/Connect.js in VaadinServiceInitListener - hope I can remove this hack soon. Attaching some examples of the workaround. 
![image](https://user-images.githubusercontent.com/367125/158393183-f4905cbe-db6d-459c-8c6a-387d13f8d027.png)
![image](https://user-images.githubusercontent.com/367125/158393293-228b4f55-ab22-4b5d-8024-8332fa93c1e2.png)

@&ZeroWidthSpace;Endpoint:
![image](https://user-images.githubusercontent.com/367125/158393334-6235b2da-3f88-403f-9e05-e1a65436df02.png)
Usage:
![image](https://user-images.githubusercontent.com/367125/158393429-e00086c9-aa3b-41c3-85cb-7911efc61393.png)

**Comment by cromoteca** [comment]
I created vaadin/flow#13877 to track the part of code changes that are in the Flow project.
