### ISSUE TITLE
frontend/backend api backward compatibility

### ISSUE THREAD

**Issue by jeacott1** [vaadin/hilla#1690]
Hi all,
  I'm researching hilla, and can see that typescript models are generated to match the java models.
What I would like to know is how to manage backward compatibility in the wild. if I have v1 in production and publish a new release,
Is there a means to guarantee that existing frontends running in browsers and the new version can remain compatible with both backend api's during the transition?
The existing docs and approach seem to assume an instant and ubiquitous transition between versions client and serverside.

**Comment by marcushellberg** [comment]
Thanks for filing the issue. We already have an ongoing discussion about the topic here https://github.com/vaadin/hilla/issues/946, could you please your question there so we have everything in one place? Thanks!
