### ISSUE TITLE
Using QueryParameters and return a Location in a @Service function lead to error in TypeScript generator

### ISSUE THREAD

**Issue by SashLi** [vaadin/hilla#1724]
### Describe the bug

Using QueryParameters and Location as return value in a function inside of a service lead to:

ERROR(TypeScript)  Type 'ObjectModel<NonNullable<T["parameters"]>>' is not assignable to type 'ObjectModel<Record<string, readonly string[]>>

```
INFO 6164 --- [onPool-worker-3] c.v.b.devserver.AbstractDevServerRunner  : Started Vite. Time: 19586ms
INFO 6164 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 
INFO 6164 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   ➜  Local:   http://127.0.0.1:52220/VAADIN/
INFO 6164 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 
INFO 6164 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :  ERROR(TypeScript)  Type 'ObjectModel<NonNullable<T["parameters"]>>' is not assignable to type 'ObjectModel<Record<string, readonly string[]>>'.
INFO 6164 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   Type 'NonNullable<T["parameters"]>' is not assignable to type 'Record<string, readonly string[]>'.
INFO 6164 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     'string' index signatures are incompatible.
INFO 6164 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :       Type '(string | undefined)[] | undefined' is not assignable to type 'readonly string[]'.
INFO 6164 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :         Type 'undefined' is not assignable to type 'readonly string[]'.
INFO 6164 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :  FILE  /Users/testuser/my-hilla-app/frontend/generated/com/vaadin/flow/router/QueryParametersModel.ts:6:9
INFO 6164 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 
INFO 6164 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     4 |     static override createEmptyValue = makeObjectEmptyValueCreator_1(QueryParametersModel);
INFO 6164 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     5 |     get parameters(): ObjectModel_1<Record<string, ReadonlyArray<string>>> {
INFO 6164 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   > 6 |         return this[_getPropertyModel_1]("parameters", (parent, key) => new ObjectModel_1(parent, key, true, { meta: { javaType: "java.util.Map" } }));
INFO 6164 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :       |         ^^^^^^
INFO 6164 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     7 |     }
INFO 6164 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     8 |     get queryString(): StringModel_1 {
INFO 6164 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     9 |         return this[_getPropertyModel_1]("queryString", (parent, key) => new StringModel_1(parent, key, true, { meta: { javaType: "java.lang.String" } }));
INFO 6164 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 
INFO 6164 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : [TypeScript] Found 1 error. Watching for file changes.

```

### Expected-behavior

Build frontend with success

### Reproduction

- Use Hilla with Lit Starter App
- Add function returnLocation to HelloWorldService
- Run ./mvnw

Here is the added function for the HelloWorldService
```
public Location retunLocation(){

        Map<String,List<String>> paramsMap = new HashMap<>();

        ArrayList<String> usernameParams = new ArrayList<>();
        usernameParams.add("test");
        paramsMap.put("user",usernameParams);

        QueryParameters params = new QueryParameters(paramsMap);
        return new Location("/myservlet/",params);
    }
```

### System Info

- macOS
- Node: v18.18.2
- Java: Temurin-17.0.8.1+1
- Hilla 2.3.3

**Comment by Legioth** [comment]
Flow's `com.vaadin.flow.router.Location` class is not designed with JSON serialization in mind.

What are you trying to achieve by using that type in a browser-callable Hilla service? Would it be more feasible to instead use a generic URI builder library to create and return a `String` that represents the same location?

**Comment by SashLi** [comment]
Just added the code to the Starter App to demonstrate the issue, browser-callable not used in the project. This worked without any problems on older Hilla versions. Does this maybe broke with  [Issue 1612](https://github.com/vaadin/hilla/issues/1612)

**Comment by Legioth** [comment]
Thanks for the clarification that this used to work in previous versions.

`HelloWorldService` is a "browser callable service" since it's a service where all public methods are callable from the browser - `@Endpoint` and `@BrowserCallable` are equivalent in that sense.

**Comment by SashLi** [comment]
I rechecked it with all 3.x.x versions of Hilla and its working until the last Hilla 2.2.2 version

**Comment by SashLi** [comment]
If its not designed with JSON serialization in mind and should not be used as return value, feel free to close this issue. As I already mention it was useable and used be me in Hilla 2.x.x and 1.x.x

**Comment by knoobie** [comment]
Just wondering: why not making this method private? I would guess Hilla doesn't re-create those methods, allowing you to use this helper method as what is it intended: a private helper method

**Comment by platosha** [comment]
Regardless of the use case that triggers it, this is a regression in the TypeScript model generator around handling the case when the field is a map with optional values.

Expected output:

```typescript
get parameters(): ObjectModel_1<Record<string, ReadonlyArray<string | undefined> | undefined>>
```

Actual output:
```typescript
get parameters(): ObjectModel_1<Record<string, ReadonlyArray<string>>>
```

At the same time, the data interface is generated correctly:

```typescript
interface QueryParameters {
    parameters?: Record<string, Array<string | undefined> | undefined>;
    queryString?: string;
}
```
