### ISSUE TITLE
Allow MavenRunner to accept a custom path for maven executable

### ISSUE THREAD

**Issue by mcollovati** [vaadin/hilla#1749]
### Describe your motivation

Currently, to detect the maven executable Hilla uses a list of potential executables hard-coded in `MavenRunner` class (e.g. for *nix they are `./mvnw` and `mvn`).

However, the detection can fail when starting the Hilla application from and IDE, if Maven executable is not present on PATH. For example, if you use [SDKMAN!](https://sdkman.io/) to handle multiple maven installations, the default one may be added to the PATH in a way that is not visible.

Another case of failure is having a multi-module maven project, where the Hilla application is in a submodule, but the maven wrapper is in the root project folder.

### Describe the solution you'd like

It would be nice to have the opportunity to extend the maven executables path list in MavenRunner by using a system property and/or the MAVEN_HOME environment variable (e.g. $MAVEN_HOME/bin/mvn).

### Describe alternatives you've considered

Setting a PATH environment variable in the IDE run configuration seems not to work.
Also creating a symlink to the maven wrapper in the submodule is not working properly.

**Comment by platosha** [comment]
I would suggest to add a system property for that.
