### ISSUE TITLE
Binding boolean field to a true/false select element

### ISSUE THREAD

**Issue by Feuerwerk** [vaadin/hilla#177]
### Description of the bug 
When binding a boolean field to a vaadin-select using the following construct

```html
<vaadin-select ${field(model.mode)} .renderer="${guard([], () => (root: HTMLElement) => render(html`
   <vaadin-list-box>
      <vaadin-item value="true">Description Text A</vaadin-item>
      <vaadin-item value="false">Description Text B</vaadin-item>
   </vaadin-list-box>`, root))}">
</vaadin-select>
```

the used _BooleanModel_ will interpret every string that is not empty as _true_ since _Boolean()_ is used to convert the string back to a boolean.
Changing the false-item to an empty string as suggested by @Haprog doesn't work either. Writing back into the model works but reading from the model will result in an empty select element.
Using a checkbox or radio buttons in this case is not a viable solution in my case since i have longer labels to describe the two options which would either confuse the user (checkbox) or waste ui space (radiobuttons)

### Expected behavior
It is expected that if the property value is _true_ _option A_ of the select element is shown and if the value is _false_ _option B_ is shown.
When changing the select element to _option A_ the property value should be change to _true_ and if changed to _option B_ the value should be _false_.

### Actual behavior
When changing the select element to _option A_ the property value will be set to _true_ and if changed to _option B_ the value is set to _false_. But when reading from the model the select element becomes empty for every property value.

### Versions:
Vaadin 22.0.2
Java: 16

**Comment by haijian-vaadin** [comment]
It's a bug in the BooleanModel fromString, we should fix that and possibly open a static property that users can override themselves to customize the behavior.
