### ISSUE TITLE
[autogrid] Allow disabling sorting for specific column

### ISSUE THREAD

**Issue by sissbruecker** [vaadin/hilla#1796]
When using a custom renderer for a column that aggregates multiple fields you might not have a sensible single value to sort by. For example, for an address renderer there isn't really a single field that you would want to sort:
```tsx
<AutoGrid
  visibleColumns: ['name', 'address'],
  columnOptions: {
    address: {
      renderer: AddressRenderer,
    },
  },
/>
```

In such cases it should be possible to disable sort. Furthermore, if a column's path points at an `ObjectModel`, sorting should be disabled automatically.

As a workaround, it would be possible to replace the auto rendered column with a custom non-sortable column.

**Comment by platosha** [comment]
Implemented
