### ISSUE TITLE
[autoform] Allow configuring client-side validators

### ISSUE THREAD

**Issue by sissbruecker** [vaadin/hilla#1797]
When rendering an `AutoForm`, there is no straight-forward way to configure client-side validators. This would be useful for cases where developers either don't want to, or can not use Jakarta annotations on entities or DTOs.

There should be a way to configure client-side validators for individual fields as well as the whole form.

As a workaround, it might be possible to define a custom layout renderer, which gets access to the form instance.

**Comment by platosha** [comment]
Let's first make sure that it is possible in some way. Using a custom layout is fine for the initial support.
