### ISSUE TITLE
JSR380 validation error message interpolation does not work in production mode

### ISSUE THREAD

**Issue by pm-finamis** [vaadin/hilla#1840]
### Describe the bug

https://hilla.dev/docs/lit/guides/forms/binder-validation#validation-message-interpolation
suggests to use validator.constructor.name to construct the key for localization message lookup.

In production mode, class names are minified (or what causes this), 'NotBlank' changes to e.g. 'Yg' and the lookup fails.
I.e. the key is 'validationError.Yg' and the translation file contains 'validationError.NotBlank'.

JSR380 validation messages are always shown in English.
The documentation is misleading - it appears that there is a clean way to do this, but it does not work in production mode. 

### Expected-behavior

Hilla should provide a clean and working way to interpolate JSR380 messages. Documentation and sample code should be fixed.

    Idea 1:
        Exempt the jakarta.validation.constraints.* from minification (or what causes this). How?
        It will work with the Hilla sample interpolation logic.

    Workaround1:
        Define an explicit message for every validation annotation usage. This works, but requires
        a lot of unnecessary and duplicate code in annotations. E.g.
        @Size(max = 15, message = "jsr380Error.Size")
        Then move all the translations in LANG_CODE.json from validationError to jsr380Error subtree.
        Use the following interpolation logic:
        Binder.interpolateMessageCallback = (message, validator, binderNode) => {
            if(message.startsWith('customValidationError.') || message.startsWith('jsr380Error.')) {
                if (translateConfig.lookup(message, translateConfig)) {
                    return get(message, validator as any);
                }
            }
            // Fall back to original message if no translations are found
            return message;
        };

    Workaround2:
        Detect the validator name from its message in localization.ts. This is bad.
        It will work with the Hilla sample interpolation logic (to do: check DecimalMin, DecimalMax).
        let validatorName : String = validator.constructor.name;
        if(message === 'must not be blank') {
            validatorName = 'NotBlank';
        } else if(message === 'must be true') {
            validatorName = 'AssertTrue';
        } else if(/size must be between [0-9]+ and [0-9]+/.test(message)) {
            validatorName = 'Size';
        }
        key = `validationError.${validatorName}`;

### Reproduction

Follow the https://hilla.dev/docs/lit/guides/forms/binder-validation#validation-message-interpolation and run the app in production mode.

### System Info

Hilla 2.4.0 (it is very probable that it applies also to previous versions)

**Comment by pm-finamis** [comment]
Unfortunately message as the key does not work for parametrized messages e.g. "size must be between 0 and 250" unless you want to "translate" all possible values.

I don't think it is possible to add name attribute to validators, those are standard jakarta annotations, unless you provide your own set of validators which simply is not "jsr380 validations support" then.

I like the "Idea 1" the most, but I don't know how to do it. I was hoping that javascript/build specialists at your company would. This might be the cleanest solution.

We went with "Workaround 1", because our app is very small. It breaks the idea of jsr380 validations support, because it requires changes in model pojos extra to jsr380

"Workaround 2" is similar to your concept, but it adds the needed complexity of regular expressions for parametrized messages. This might be quite usable if it was provided with the framework as a blackbox (claiming to have support for jsr380). Some attempt was made here [https://github.com/Haprog/vaadin&#45;fusion&#45;message&#45;interpolator&#45;example/blob/main/frontend/localization.ts](https://github.com/Haprog/vaadin-fusion-message-interpolator-example/blob/main/frontend/localization.ts), still it is a very different approach from the recommended one (and code seems to be a bit complicated maybe) and it tooks us a long time to even find it.

**Comment by TatuLund** [comment]
I updated the demo app to use the new `name `property for localization key https://github.com/TatuLund/hilla-demo/blob/hilla2/frontend/index.ts#L22

For custom validator how to set `name `https://github.com/TatuLund/hilla-demo/blob/hilla2/frontend/util/validators.ts#L5
