### ISSUE TITLE
Stateless auth with @AnonymousAllowed endpoint fails when spring csrf is disabled

### ISSUE THREAD

**Issue by johannest** [vaadin/hilla#185]
### Minimal reproducible example
1. Use https://github.com/vaadin/fusion-crm-tutorial as a basis of test project
2. Create simple @AnonymousAllowed endpoint (see **A** below)
3. Use the endpoint in login-view (see **B** below)
4. Add line `http.csrf().disable();` to configure(HttpSecurity) method. (edit)
5. Run the app, login and logout and see the browser's console for the errors
### Expected behavior
Calling the @AnonymousAllowed endpoint in login-view should work even after logout.
### Actual behavior
401 error is got when calling the endpoint:
```
Uncaught (in promise) Error: expected "200 OK" response, but got 401 
    EndpointError Connect.js:21
    assertResponseIsOk Connect.js:88
    responseHandlerMiddleware Connect.js:208
    chain Connect.js:237
    call Connect.js:245
    _getHello HelloEndpoint.ts:12
```
### Versions:
    - Vaadin / Fusion version: 22.0.2 and 23.0.0.alpha1
    - Node version:  14.17.0 (global)
    - Java version: Amazon Corretto 11
    - OS version: Win 11 Pro

I wonder does the Hilla client in browser have an old csrf token after logout, and thus the call to anonymous allowed endpoint fails.

**(A)**
```
@Endpoint
@AnonymousAllowed
public class HelloEndpoint {
    public String getHello() {
        return "Hello world";
    }
}
```

**(B)**
```
async connectedCallback() {
    super.connectedCallback();
    this.classList.add('flex', 'flex-col', 'items-center', 'justify-center');
    uiStore.setLoggedIn(false);
    console.log(">>>>"+ await HelloEndpoint.getHello());
  }
```

Edit: added more complete code example.

**Comment by haijian-vaadin** [comment]
Hi, thanks for the feedback. 

The jwt cookie is cleared during logout, see the code [here](https://github.com/vaadin/hilla/blob/main/packages/ts/fusion-frontend/src/Authentication.ts#L160).

The described problem here is caused by the `HelloEndpoint` being called in the `connectedCallback`, which is called asynchronously while the logout code is running.  

If I move the `HelloEndpoint` call out of the `connectedCallback`, for example, into a click listener, 
```
<vaadin-button @click=${this.sayHello}>Say Hello</vaadin-button>
async sayHello() {
    console.log(">>>>"+ await HelloEndpoint.getHello());
}
```
then it works fines.

**Comment by johannest** [comment]
Thanks @haijian-vaadin you are right that fixes the issue described in the original description. The original description's code example was oversimplified. If I add `http.csrf().disable();` line to `configure(HttpSecurity http)`, then  @AnonymousAllowed endpoint breaks after login-logout cycle.

**Comment by johannest** [comment]
Edited the original bug description to include the above.
