### ISSUE TITLE
[autogrid] custom column header should be at the same level as other headers

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/hilla#1854]
### Describe your motivation

An AutoGrid with some filterable columns that have a custom column added to it, will show the header of the custom column at the same level as the filters.

![image](https://github.com/vaadin/hilla/assets/42799254/4db88bb6-9316-4e11-a65e-66eefa6433a4)

### Describe the solution you'd like

The custom column header should be at the same level as other headers.

**Comment by platosha** [comment]
Would be nice to render the sorter and filter in the same row.
