### ISSUE TITLE
Package naming changes 

### ISSUE THREAD

**Issue by platosha** [vaadin/hilla#1904]
For Java artifacts, the package names and Maven groupIds should be `com.vaadin.hilla` (instead of `dev.hilla`). Artifact names stay the same.

For npm packages, all packages that require using Hilla should be prefixed with `@vaadin/hilla-` instead of `@hilla/`, with few exceptions:
- `@hilla/frontend` → `@vaadin/hilla-core`
- `@hilla/form` → `@vaadin/hilla-lit-form`
- `@hilla/react-components` → `@vaadin/react-components` (out of scope for this issue)
- Consider simplifying the naming for the `generator-typescript-` packages, maybe the `typescript-` part could be removed

**Comment by tarekoraby** [comment]
Perhaps [hilla](https://github.com/vaadin/hilla/tree/main/packages/java/hilla) package should be renamed to `hilla-lit`.

**Comment by taefi** [comment]
> Perhaps [hilla](https://github.com/vaadin/hilla/tree/main/packages/java/hilla) Java artifact should be renamed to `hilla-lit`.

In that case, we may also consider renaming `hilla-spring-boot-starter` to `hilla-lit-spring-boot-starter` to align it with the `hilla-lit` and `hilla-react-spring-boot-starter`. WDYT @platosha?

**Comment by tarekoraby** [comment]
Yes, let's do that.

**Comment by taefi** [comment]
Apart from simplifying `generator-typescript-xxx` to `generator-xxx`, renaming the npm package name in `package.json` from `@hilla/generator-xxx` to `@vaadin/generator-xxx` sounds a bit weird. I suggest adding the `hilla-` to have the npm package name as `@vaadin/hilla-generator-xxx`. Any counter arguments?
