### ISSUE TITLE
Vaadin Fusion in multimodule Maven project

### ISSUE THREAD

**Issue by otto-vodvarka** [vaadin/hilla#195]
Hello,

we have a Spring Boot project divided into multiple Maven modules. Right now we are using JSF for UI, but we are not really satisfied with it and we are considering migration to Vaadin Fusion. I haven't find any documentation whether it is even possible to use Fusion(Hilla) in a multimodule Maven project. From my point of view it seems unlikely it would be possible as in every module you need to have e.g. package.json file and it would have to be somehow merged. But maybe I am missing something and it is possible. 

Thanks

**Comment by samie** [comment]
Hi! The multi-module support is WIP for now. We are currently working on with a new version of Java-TS generator, that will bring this support as well.

**Comment by otto-vodvarka** [comment]
Thanks for the answer! Do you have any estimations when will this feature be available? Will it be part of the Vaadin 23 LTS version?

**Comment by haijian-vaadin** [comment]
Hi @otto-vodvarka, really glad to hear you are interested in Hilla. You can track the progress of the multi-module support with this [Epic](https://app.zenhub.com/workspaces/fusion-5d413125e27a7b3dba911156/issues/vaadin/hilla/123) is finished. 
We are targeting it for Vaadin 23.1.

**Comment by haijian-vaadin** [comment]
Since it's a question and answer, I'd prefer to close this ticket.
