### ISSUE TITLE
Move Hilla docs from hilla.dev to vaadin.com

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/hilla#1952]
In preparation for bringing Hilla under vaadin.com, let's move Hilla docs from hilla.dev to vaadin.com. Practically this means moving the `hilla` branch in the [docs repo](https://github.com/vaadin/docs) to the `next` branch there.

**Comment by geoffreylgv** [comment]
Hi @tarekoraby,
How can this be done, because I can't see the documentation part of `hilla` on this repository to arrive to migrate it into `hilla` on vaadin doc repo.

**Comment by tarekoraby** [comment]
Hi, the docs are in a separate repo: https://github.com/vaadin/docs. @taefi has already completed most of the needed work: https://github.com/vaadin/docs/pull/3139.

**Comment by tarekoraby** [comment]
Closing as duplicate of https://github.com/vaadin/docs/issues/3132.

**Comment by geoffreylgv** [comment]
Ok
