### ISSUE TITLE
Icons don't show up after production build

### ISSUE THREAD

**Issue by adambchouti** [vaadin/hilla#1957]
### Describe the bug

Hello,

I've just created a brand new hilla app by running: `npx @hilla/cli init my-hilla-app`

I added an Icon component to the app, ex: `<Icon style={{ height: '15px', width: '15px' }} icon="vaadin:chat" />`

If I run the app in development mode, everything works great, I see the icon. But if I build it for production:
```
mvn clean package -Pproduction
```

and run the jar, the icon is not visible. I might be missing something very simple somewhere. All css is working fine, expect for the icons not showing up.

### Expected-behavior

Icons to be visible after production build

### Reproduction

-Create brand new Hilla project: `npx @hilla/cli init my-hilla-app`
-Add an icon:  `<Icon style={{ height: '15px', width: '15px' }} icon="vaadin:chat" />`
-Build for production: `mvn clean package -Pproduction`
-Run the jar: `java -jar <jar_location>`

### System Info

Windows 10, hilla 2.5.5, java 17

**Comment by tarekoraby** [comment]
I'm unable to reproduce. The icons show up fine for me. 

Do you have the icons imported?
```
import { Icon } from '@hilla/react-components/Icon.js';
import '@vaadin/icons';
```

**Comment by adambchouti** [comment]
I knew I was missing something simple. I had the Icon import but not `import '@vaadin/icons';`
thanks!

Any reason it works without it in dev mode but not in production build?

**Comment by tarekoraby** [comment]
I'm not sure if this is intended. Sounds like something that should fixed/improved to me. Opened a separate ticket: https://github.com/vaadin/react-components/issues/218.
