### ISSUE TITLE
Support @NotNull annotation in form binding

### ISSUE THREAD

**Issue by DarioArena87** [vaadin/hilla#1986]
### Describe your motivation

Suppose i have a entity class that has some child object associated with JPA annotations (`@OneToOne`, `@ManyToOne`) like this:
```java
public class Pet extends IdEntity {
    @NotEmpty(message = "Cannot be empty")
    private String name;

    @ManyToOne
    private Fence fence;

   ...
}
```
And in a page to create i have a simple control to associate Pets to a Fence (for example a [PickList](https://primereact.org/picklist/) or something similar)
At the moment i have not found a way to impose that to register a new Pet it must be associated to a Fence and make the association required so that if fence is null the form is invalid. For a `@OneToMany` association that is on a collection field i can use the `@NotEmpty` association and even customize the message if the collection is empty but the reverse seems impossible. 
If i use the `@NotNull` annotation from `jakarta.validation.constraints` package the typescript interface for Pet requires that the fence is not null:
```typescript
interface Pet {
    name: string;
    fence: Fence_1;
}
```
But the generated model for form bindings is missing the information that the fence is required
```typescript
class PetModel<T extends Pet_1 = Pet_1> extends ObjectModel_1<T> {
    static override createEmptyValue = makeObjectEmptyValueCreator_1(PetModel);
    get name(): StringModel_1 {
        return this[_getPropertyModel_1]("name", (parent, key) => new StringModel_1(parent, key, true, { validators: [new NotEmpty_1({ message: "Cannot be empty" })], meta: { javaType: "java.lang.String" } }));
    }
    get fence(): FenceModel_1 {
        return this[_getPropertyModel_1]("fence", (parent, key) => new FenceModel_1(parent, key, true, { meta: { annotations: [{ name: "jakarta.persistence.ManyToOne" }] } }));
    }
```
If i add a `@Nonnull` annotation (for example the jakarta or spring ones that do not have a "message" field) in the generated model the 'optional' parameter is false but still there are no validators like the NotEmpty one in the name field.
Is this a bug or is it the intended behaviour (or am i doing something really wrong without realizing it)?

### Describe the solution you'd like

I would like that when i write the "fence" field in the class like this:
```java
    @NotNull(message = "Specify a fence for the pet")
    @ManyToOne
    private Fence fence;
```
In the generated model the field is generated like this:
```typescript
    get fence(): FenceModel_1 {
        return this[_getPropertyModel_1]("fence", (parent, key) => new FenceModel_1(parent, key, true, { validators: [new NotEmpty_1({ message: "Specify a fence for the pet" })], meta: { annotations: [{ name: "jakarta.persistence.ManyToOne" }, {}] } }));
    }
```

### Describe alternatives you've considered

As i've said in the motivation section i've tried adding some `@Nonnull' annotation, in particular i've tried:

- jakarta.validation.constraints.NotNull
- jakarta.annotation.Nonnull
- org.springframework.lang.NonNull

### Additional context

Maybe there could be hope that to define a field nullability, instead of any 'nonnull' (case insensitive) annotation, to define a field that cannot be null hilla could switch to using `jakarta.validation.constraints.NotNull` (maybe adding a commodity one like `dev.hilla.NotNull` for generic types) to conform more to the Jakarta Bean Validation specification?

**Comment by platosha** [comment]
Let's investigate if we have a bug in this case.

**Comment by taefi** [comment]
What I observe is that having a `@NotNull` on a relation property (e.g. marked with `@ManyToOne`) doesn't generate a validation in the TS model for that property. 

As an example, I have a `City` entity with a `name` property, and a `Country` property (a `@ManyToOne` relation). The generated TS model for City is:

```ts
class CityModel<T extends City_1 = City_1> extends AbstractEntityModel_1<T> {
    static override createEmptyValue = makeObjectEmptyValueCreator_1(CityModel);
    get name(): StringModel_1 {
        return this[_getPropertyModel_1]("name", (parent, key) => new StringModel_1(parent, key, true, { validators: [new NotEmpty_1()], meta: { javaType: "java.lang.String" } }));
    }
    get country(): CountryModel_1 {
        return this[_getPropertyModel_1]("country", (parent, key) => new CountryModel_1(parent, key, true, { meta: { annotations: [{ name: "jakarta.persistence.ManyToOne" }] } }));
    }
}
``` 
Which is clearly missing a validator for the Country being not null.
I believe this is a bug (maybe a regression), rather than an enhancement.
