### ISSUE TITLE
Plugin name clash when running Vaadin 24.4 with multiplatform-runtime

### ISSUE THREAD

**Issue by mshabarov** [vaadin/hilla#2011]
### Describe the bug

Vaadin Flow + Multiplatform-Runtime or Vaadin Hilla + Flow + Multiplatform-Runtime don't work with Vaadin 24.4 latest pre-release as Vaadin tries to call `vaadin:configure` goal that clashes with legacy `vaadin-maven-plugin` having the same name `vaadin`:

When invoking the `vaadin:build-frontend` goal, the `TaskGenerateOpenAPIImpl` node task is executed, that in turn runs `mvn vaadin:configure`, see `AbstractTaskEndpointGenerator` class in Hilla.

The problem is that in an MPR project this will call the framework's maven plugin, resulting in the following error
```
[ERROR] Could not find goal 'configure' in plugin com.vaadin:vaadin-maven-plugin:8.20.0 among available goals clean, compile, compile-report, compile-theme, css, debug, eclipse, eclipseTest, generateAsync, help, i18n, mergewebxml, resources, run, run-codeserver, source-jar, test, update-theme, update-widgetset, upgrade8 -> [Help 1] 
```

Flow invokes the `TaskGenerateOpenAPI` and `vaadin:configure`, because Lookup detects the Hilla class in the classpath, as `vaadin-spring-boot-starter` now depends on Hilla.

### Expected-behavior

Flow and Hilla + MPR project should work with V24.4.

### Reproduction

Run `Session IT` test module in MPR project.

### System Info

Vaadin 24.4 pre-release.

**Comment by mcollovati** [comment]
The proposed solution is to run the goal indicating the full coordinates of the plugin: `com.vaadin:vaadin-maven-plugin:24.4-SNAPSHOT:configure`

The version can be taken from `com.vaadin.flow.server.Platform.getVaadinVersion()`.
It returns an `Optional`; if the optional is empty, fallback to `vaadin:configure`
