### ISSUE TITLE
Provide initial Hilla signals library

### ISSUE THREAD

**Issue by platosha** [vaadin/hilla#2035]
To do:
- Add a `@vaadin/react-signals` npm package to Hilla repository
- Exports follow `@preact/react-signals`
- Run `installAutoSignalTracking()` from our reexport module
- Add IT test for basic signals usage
- Update docs and starters to use signals for managing the state (basically every case of `useState` and `useContext`)

**Comment by cromoteca** [comment]
https://github.com/vaadin/docs/issues/3173 created to follow docs separately
