### ISSUE TITLE
Move the fusion-endpoint module from Flow to Hilla repo

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/hilla#208]
The [fusion-endpoint](https://github.com/vaadin/flow/tree/master/fusion-endpoint) module contains the endpoint controller and the code generator. Now we have the new generator under development, once it's ready, we should move the fusion-endpoint module to hilla.

DoD:
- Flow no longer has the `fusion-endpoint` module
- The Fusion-specific security tests in the [flow-tests/vaadin-spring-tests](https://github.com/vaadin/flow/tree/master/flow-tests/vaadin-spring-tests) module are moved from the Flow repo to Hilla repo.

**Comment by manolo** [comment]
Remember to find all occurrences of fusion in sources and pom files, and fix them as much as possible
