### ISSUE TITLE
PiT 24.4: generate-maven-sbom and generate-npm-sbom are missing in maven-plugin

### ISSUE THREAD

**Issue by manolo** [vaadin/hilla#2121]
### Describe the bug

Since platform wraps hilla-maven-plugin instead of flow-maven-plugin, we need to offer all goals already present in flow.
The lack of these goals breask appsec kit

### Expected-behavior

both goals are present

### Reproduction

run `mvn vaadin:generate-maven-sbom` in any flow app

### System Info

24.4-SNAPSHOT

**Comment by platosha** [comment]
Fixed by #2123
