### ISSUE TITLE
Sort.ts is incorrectly generated with 24.4 alpha7

### ISSUE THREAD

**Issue by Artur-** [vaadin/hilla#2148]
### Describe the bug

With 24.4 alpha5 and 2.5, Sort.ts is generated as
```
interface Sort {
    orders: Array<Order_1 | undefined>;
}
```

but with alpha7 it is
```
interface Sort {
    orders?: Array<Order_1 | undefined>;
}
```

It seems like https://github.com/vaadin/hilla/blob/5d05a07cdcb39874449da399bcd59dbb60476084/packages/java/runtime-plugin-transfertypes/src/main/java/com/vaadin/hilla/mappedtypes/Sort.java#L27 nonnull here is ignored

### Expected-behavior

As in alpha5

### Reproduction

Use Sort

### System Info

24.4 alpha7

**Comment by cromoteca** [comment]
This is introduced by https://github.com/vaadin/hilla/pull/2136

**Comment by cromoteca** [comment]
Fixed by https://github.com/vaadin/hilla/pull/2152
