### ISSUE TITLE
Remove docs workaround

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/hilla#2149]
https://github.com/vaadin/docs/pull/3233 upgraded the docs to 24.4 alpha7, which incorrectly generates `Sort.ts` as reported in https://github.com/vaadin/hilla/issues/2148. As a workaround to enable the docs production to pass, https://github.com/vaadin/docs/pull/3233 used the non-null assertion operator at L88-92 of https://github.com/vaadin/docs/blob/77b927647b7e2898aeb9ca8af77ed797a50efef9/frontend/demo/services/CrudService.ts. 

When https://github.com/vaadin/hilla/issues/2148 is fixed, the docs workaround should be reverted.

**Comment by taefi** [comment]
Already fixed in the docs.
