### ISSUE TITLE
ViewConfig.register has no impact

### ISSUE THREAD

**Issue by Legioth** [vaadin/hilla#2156]
### Describe the bug

The type definition for `ViewConfig` has a `register` property that is documented to prevent the view from being automatically registered with the router. It is, however, possible to navigate to a view even if `register` has been set to `false`.

### Expected-behavior

Expected that documented properties work. Should either make the property work or remove it from the type definition if it's out of scope.

### Reproduction

1. https://github.com/Lodin/hilla-file-router-example/commit/ec8cd0b6f580f052292082ea598702c49f30d0df
2. Add `export const config : ViewConfig = { register: false }` to `hilla.tsx`
3. Navigate to `path/to/hilla` and note that the view is rendered there

### System Info

Vaadin 24.4.0.alpha7

**Comment by Legioth** [comment]
The same also applies for the `lazy` property. Even if the property is set to `true`, the content in `views.ts` is not updated to wrap the import for that view in `lazy()`. Furthermore, it's expected that all routes except `/` and `/login` should be lazy by default.

**Comment by platosha** [comment]
Could be addressed by removing the option for now.
