### ISSUE TITLE
[i18n] Add support for HMR when changing translations

### ISSUE THREAD

**Issue by sissbruecker** [vaadin/hilla#2175]
When the developer changes translations in a properties file, or Copilot writes a new translation string into a property file, the frontend should update immediately and render the updated translation without a page reload.

The current approach is to serve translation strings from the server at runtime, where the server looks up translations from a resource bundle packaged into the Java application. That means just changing a properties file would have no effect on the frontend. The developer would also have to recompile the Java app which updates the resource bundle and triggers a restart of the Spring app, which would then also trigger a reload of the page in the browser. Ideally our solution would notice changes to property files and then update translations in the frontend automatically, without requiring a page reload.

Two options come to mind:
1. In development mode, the server request handler does not use the compiled resource bundle, but loads the contents of the property files from the file system. We would then add a watcher for the property files on the file system, somehow use the Vite dev server to push a notice to the browser that those files have changed, which in turn causes the I18n instance to reload translations from the server.
2. We don't load translations from the server at all, but instead compile the property files into Javascript modules as part of the Vite build. The I18n instance would use dynamic imports to load these JS modules. By using JS imports we can reuse the Vite HMR mechanism that automatically updates these modules when they are recompiled.

**Comment by sissbruecker** [comment]
Prototype for a Vite plugin that watches translation properties files and sends an HMR update to the browser when those change:
```ts
import chokidar, { type FSWatcher } from "chokidar";

let translationsWatcher: FSWatcher;
const translationsHmrPlugin: Plugin = {
  name: "translations-hmr",
  configureServer(server) {
    translationsWatcher = chokidar
      .watch("./src/main/resources/vaadin-i18n/*.properties")
      .on("all", () => {
        server.ws.send({
          type: "custom",
          event: "translations-update",
        });
      });
  },
  buildEnd() {
    translationsWatcher.close();
  },
};
```

The I18n implementation in the client could then listen for the event and reload translations for the current language:
```ts
if (import.meta.hot) {
  import.meta.hot.on('translations-update', () => {
    // reload translations
  });
}
```

**Comment by Artur-** [comment]
Is this really a problem we should solve? None of the copilot features for Java can work properly without jrebel or hotswapagent

**Comment by sissbruecker** [comment]
I think we should, requiring a Java hot swap solution would be a weird requirement when working on React views where everything else there (views, theme) already works with HMR. 

It also doesn't seem to be too difficult to solve. We'll need to make the server work with the property files instead of the resource bundle in dev mode, and then add the Vite plugin to `vite.generated.ts`. The hard-coded path to the translations is a bit sketchy. Maybe there's a better solution to this, but it seems like a good start at least.

**Comment by Artur-** [comment]
We have the watcher through `Hotswapper` nowadays, so what is mostly missing here is the implementation of `// reload translations`. Any ideas on what the implementation of that would be @sissbruecker ?

**Comment by sissbruecker** [comment]
I was thinking we would dispatch an event in the browser that translations have changed. The Hilla React I18N library would listen for that and then reload the translation chunks that have been loaded so far, for the current language. The code for that could just be added to the [index module](https://github.com/vaadin/hilla/blob/main/packages/ts/react-i18n/src/index.ts).

**Comment by Artur-** [comment]
There is a draft PR here that just resets the state to the original but apparently that is not the correct way #2795. Want to do a quick update of it?

**Comment by sissbruecker** [comment]
I can't get the react-i18n integration test project running to test this. Starting it fails to run the endpoint generator. I probably need to run `npm run build`, but that fails with an nx error about a circular dependency.

I'm also not sure how the new chunk mechanism works, or if that is already implemented on the Flow side. Let's pull in @platosha who has worked on that feature.
