### ISSUE TITLE
Can't download Reactive Endpoints example From npx

### ISSUE THREAD

**Issue by LaplusIjns** [vaadin/hilla#2195]
### Describe the bug

According to [hilla-cli](https://github.com/vaadin/hilla-cli) and [blog](https://hilla.dev/blog/interactive-applications-with-server-push/)
if I download with --push
the project should include react endpoint example code but it not work

### Expected-behavior

The download files should include reactor example code?
or v2.0 dont have such example?

### Reproduction

npx @vaadin/cli init --push my-project
or
npx @hilla/cli init --push my-project

### System Info

Windows11
Java 17 
npx 10.2.4
node v20.11.1

**Comment by Artur-** [comment]
The starter app you get with `--push` does not contain reactive endpoints, it used to enable the push feature when it was experimental. If you want a small example project, look at e.g. https://github.com/Artur-/hilla-chat
