### ISSUE TITLE
Server is redeployed when an empty $index.tsx is created inside views/

### ISSUE THREAD

**Issue by Legioth** [vaadin/hilla#2204]
### Describe the bug

A redeploy is triggered immediately when creating a new empty `$index.tsx` file inside `frontend/views/` (either as in the root or in a sub directory). It seems like a new empty entry is added to `views.json` even though that entry doesn't seem to serve any purpose.

### Expected-behavior

Expected that a redeploy would happen only when some actual content is saved in the file since the view is functional only at that point. More specifically, I would expect that an `$index.tsx` file would be handled in the same way as an empty file with some other name.

### Reproduction

1. Create a `foo` sub directory inside `frontend/views`. No redeploy
2. Create an empty `$index.tsx` file inside `foo`. This causes a redeploy even though the file is empty.

### System Info

Vaadin 24.0.0.alpha11. File created through VS Code.

**Comment by Legioth** [comment]
Now with alpha18, it's actually even more annoying since it re-renders the page but for some reason shows a blank page rather than keeping the old content.

Also note that with alpha18, the name of the file is `foo/@index.tsx`.

**Comment by taefi** [comment]
The way I understand this, no matter what's the name of any file under `views/`, as long as it's empty it should not be processed any further, right? 
Does it make sense to check for the contents to at least contain the `export ` or `export default ` considering all the possibilities for normal file views + special ones (`@index.tsx` and `@layout`)?

**Comment by Legioth** [comment]
Might be a good start to ignore files that are empty (or only contain whitespace). It could be reasonable to also ignore files that don't have a `default` export but should in that case maybe log a warning (unless the file is already ignored due to `_`) to help developers understand what's expected.
