### ISSUE TITLE
Default menu order puts ordered items after unordered items

### ISSUE THREAD

**Issue by Legioth** [vaadin/hilla#2222]
### Describe the bug

It seems like the default value used if `menu.order` is not defined in `export const config` is 1 which means that setting the order to 1 for a view causes it to end up after views without an explicitly defined menu order rather than before.

As a workaround, you can use negative numbers for items that should be placed before items without an explicit order.

### Expected-behavior

Views with an explicitly defined order should be shown before other views in the menu. In practice, this means that the default `order` value should be `Number.MAX_VALUE` rather than `0`. 

### Reproduction

1. https://github.com/Lodin/hilla-file-router-example.
3. Add `export const config : ViewConfig = { menu: { order: 1 } }` to the view that is in the middle in the menu.
4. Notice that this makes the menu entry for that view show up last in the menu rather than first

### System Info

Vaadin 24.4.0.alpha14

**Comment by platosha** [comment]
It would be also great to sort the items missing order alphabetically by `path`.

**Comment by Legioth** [comment]
So the menu order should first have any view with an explicit `order` (descending so that 10 is before 9) and then the remaining entries would be in alphabetical order based on their path (ascending so that `/` is before `/a` which is before `/b`)

**Comment by taefi** [comment]
> So the menu order should first have any view with an explicit `order` (descending so that 10 is before 9) and then the remaining entries would be in alphabetical order based on their path (ascending so that `/` is before `/a` which is before `/b`)

Not sure if I missed the discussion around this, but why the `order` should be considered in a descending order when sorting the menu items?
To me, a menu with order = 9 should appear before a menu with order = 10.
is there a reason to interpret `order` as `priority` for some reason?

**Comment by Legioth** [comment]
"order" can be interpreted either as "index" (ascending) or as "priority" (descending). The reason to not go for the "index" interpretation is that you don't need to "re-index" all your existing views if you add or remove something - it's fine to have orders 1, 2, 4 and it's also fine to have 1, 1.5, 2.

One remaining question is whether "priority" would then be a more suitable name? I don't think so since this is explicitly about the ordering but not any other impact that a "priority" could have.

**Comment by taefi** [comment]
Though, technically the word "order" can represent both ascending and descending orders, still feels a weird to me to assume the default would be descending. In many projects, people have adopted the orders to be 10, 20, 30, ... or even 100, 200, 300, ... to overcome the issue of add/removal of menus during the time, and since we have numbers and not integers, even the floating point numbers can help with that. That's the reason I'm in favor of interpreting "order" as index instead of priority, since I feel the natural order of numbers should be the default (and a self-documentary way of naming that property), not the other way around.

**Comment by Legioth** [comment]
Based on a very unscientific poll that I did on Slack, it seems like most users would indeed expect that lower order values are higher up in the menu so let's do it in that way. This also means that the default order when none is defined would be `Number.MAX_VALUE` (not the suggested `Number.MAX_SAFE_INTEGER` since there's nothing that says that those numbers will be integers).

I've updated the original message and the message with additional specs to show this order.

**Comment by taefi** [comment]
In an imaginary array of ViewConfig objects as the following:
```
const views: Array<ViewConfig> = [
    {path: '/a/b'},
    {path: ''},
    {path: '/employee', menu: {order: 20}},
    {path: '/a'},
    {path: '/hello', menu: { order: 5}},
    {path: '/'},
    {path: '/countries', menu: { order: 20}},
    {path: '/b'},
    {path: '/about', menu: { order: 10}},
]
```
if I first apply order and then use a normal string comparison function such as `localeCompare` it would result it having `/a/b` before `/b`. Is this the desired output:
```
[{
  "path": "/hello",
  "menu": {
    "order": 5
  }
}, {
  "path": "/about",
  "menu": {
    "order": 10
  }
}, {
  "path": "/countries",
  "menu": {
    "order": 20
  }
}, {
  "path": "/employee",
  "menu": {
    "order": 20
  }
}, {
  "path": ""
}, {
  "path": "/"
}, {
  "path": "/a"
}, {
  "path": "/a/b"
}, {
  "path": "/b"
}]
```
Assuming that I define the length of a path as `path.split('/').length`, when a orders are equal (either defined orders or the fallback MAX_VALUE) should comparing the path length have a higher priority over the alphabetical comparison?

**Comment by Legioth** [comment]
`/a` should be before `/b` but it doesn't have to be immediately before. `/a` and `/a/b` should be adjacent since they are assumingly related to each other. `/a` should  be before `/a/b` since it's more of a "heading". From these steps follow that the suggested order of `/a`, `/a/b`, `/b` would be a good outcome.

Path length on its own is not a good heuristic since `/a/bcdefgh` and `/a` are related to each other but would be put far from each other based on the length. Regular alphabetic ordering is already taking the length into account as a tie breaker when one string is the prefix of another string (e.g. so that `/a` comes before `/a/b`) so I assume we don't need to do anything special there either.
