### ISSUE TITLE
support maven system dependency

### ISSUE THREAD

**Issue by sheiy** [vaadin/hilla#2230]
### Describe your motivation

support maven system scope dependency
```xml
  <dependency>
            <groupId>taobao</groupId>
            <artifactId>sdk-java</artifactId>
            <version>auto_1709828590347-20240314</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/lib/taobao-sdk-java-auto_1709828590347-20240314.jar</systemPath>
        </dependency>
```
```xml
<plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <includeSystemScope>true</includeSystemScope>
                </configuration>
            </plugin>
```

**Comment by Artur-** [comment]
Not sure what exactly you are looking for here but it seems like system dependencies are discouraged by Maven: https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#system-dependencies

**Comment by Legioth** [comment]
What would this feature help you achieve? Could there be another way of achieving that without relying on deprecated features?

**Comment by Legioth** [comment]
The correct place to address this would probably be in https://github.com/vaadin/flow/blob/e973f16fe406fde24b0a6d987c5b9a9d9a2d5784/flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java#L245-L248

**Comment by Legioth** [comment]
For reference, this is the discussion that lead to including this feature in Spring Boot. https://github.com/spring-projects/spring-boot/issues/2224

To me, the key point is really this comment:
> Usecase where I see this is with some wrapper libraries not available in maven - and CI server being operated centrally and not liking people adding stuff to repositories on their own, or running own repositories.

**Comment by Legioth** [comment]
...and here's a discussion related to why the Maven maintainers think that the system scope should be deprecated: https://issues.apache.org/jira/browse/MNG-6523

My interpretation is that Maven has this feature for other purposes and the Maven maintainers think the way it's actually used is _wrong_ and shouldn't be needed in a perfect world. They think you should make the world perfect rather than relying on Maven to officially support the current state of the world.

**Comment by platosha** [comment]
Let's follow what Spring Boot does here: add a property flag that enables this.

**Comment by platosha** [comment]
As part of the solution, let us verify that Hilla supports entities from system dependencies.
