### ISSUE TITLE
Hilla doesn't redirect to a given URL when logout with Hilla's useAuth API

### ISSUE THREAD

**Issue by mshabarov** [vaadin/hilla#2235]
### Description of the bug

Hilla doesn't redirect to a `logoutSuccessfulUrl` being set with `VaadinWebSecurity::setLoginView(http, "/login", "/")` if the logout method uses Hilla's provided `useAuth::logout` API.

It performs the logout successfully, but the page isn't redirected and the page content is visible.

If I logout from a Hilla view, it redirects me to login page, which also a bit unexpected, but better than keeping the content of the current page.

Here is how I configure my logout:

**MainLayout.tsx:**
```
import {useAuth} from "../auth";
...
const { state, logout } = useAuth();
...
<Button onClick={async () => logout()}>Sign out</Button>
```
**auth.tsx**
```
import { UserInfoService } from 'Frontend/generated/endpoints';
import {configureAuth} from "@vaadin/hilla-react-auth";

const auth = configureAuth(UserInfoService.getUserInfo, {
    getRoles: (userInfo) => userInfo.authorities,
});

export const useAuth = auth.useAuth;
export const AuthProvider = auth.AuthProvider;
```

Browser sends POST "/logout" request to server and it's caught by `UidlRedirectStrategy`. Then it falls into `super.sendRedirect(request, response, url);` and redirect doesn't happen for some reason.

### Expected behavior

Flow should redirect to "/" after logout.

### Minimal reproducible example

1. Checkout branch https://github.com/vaadin/flow-hilla-hybrid-example/tree/stateful-auth
2. mvn
3. Log in with admin/admin
4. Navigate to Flow view
5. Click on Logout button
6. Browser the Flow content is still there.

### Versions

- Vaadin / Flow version: 24.4.0.alpha15

**Comment by TatuLund** [comment]
Currently I am doing that like this https://github.com/TatuLund/hilla-v2-demo/commit/ccc5570bbe844eabd22987a447d0686a4418b353

**Comment by platosha** [comment]
#2237 was causing this, now it's fixed.

**Comment by platosha** [comment]
Ah sorry, logout redirect... 😅

**Comment by Lodin** [comment]
@mshabarov, it looks like there is no `stateful-auth` branch anymore 🤔

**Comment by platosha** [comment]
@Lodin it was merged into `24.4`, I think.

**Comment by Lodin** [comment]
@mshabarov, @platosha, @Legioth, what would you expect on logout?

- The page fully reloads
- The page is updated using the React Router capabilities

**Comment by Legioth** [comment]
It's always a good practice to reload the page whenever the authentication state changes. When logging out, one of the main benefits is that you can ensure that no sensitive data remains referenced in JS variables.
