### ISSUE TITLE
Fusion Endpoint tests fail when running on windows.

### ISSUE THREAD

**Issue by caalador** [vaadin/hilla#224]
The tests run in Fusion Endpoint fail in the windows builds.
Currently the failing set is `[ERROR] Tests run: 330, Failures: 19, Errors: 0, Skipped: 5`
See nightly run for windows in 9.0 and 10.0

**Comment by platosha** [comment]
Thanks for reporting. Let me close this, as we’re going to move the Fusion Endpoint module to our repo, see #208
