### ISSUE TITLE
Meaning of empty array in `rolesAllowed` is not clear

### ISSUE THREAD

**Issue by cromoteca** [vaadin/hilla#2246]
By looking at https://github.com/vaadin/hilla/blob/0c88e2c4d7670a87e0634a971614ba34b29c82a0/packages/ts/react-auth/src/ProtectedRoute.tsx#L68, it seems that if `rolesAllowed` is empty, then it is accessible to all users. It was thought to be a way to mimic the `DenyAll` annotation in Java EE security, so there's probably a mismatch between the Java and the TypeScript implementations.

**Comment by Artur-** [comment]
https://docs.oracle.com/javaee%2F7%2Fapi%2F%2F/javax/annotation/security/RolesAllowed.html

Specifies the list of roles permitted to access method(s) in an application. The value of the RolesAllowed annotation is a list of security role names

Says nothing about some exception for an empty list

**Comment by cromoteca** [comment]
Sure, but at the moment the TS code does not match the Java code in Hilla concerning this case.

**Comment by cromoteca** [comment]
`jakarta.annotation.security.RolesAllowed` does not allow an empty list. It is a compilation error.
