### ISSUE TITLE
[FS Router] configuring `route` property of exported ViewConfig in views is breaking the router functionality

### ISSUE THREAD

**Issue by taefi** [vaadin/hilla#2254]
### Describe the bug

The [ViewConfig](https://github.com/vaadin/hilla/blob/main/packages/ts/hilla-file-router/src/types.d.ts#L19-L24) type introduces a `route` property with the following documentation:

```ts
  /**
   * Allows overriding the route path configuration. Uses the same syntax as
   * the path property with React Router. This can be used to define a route
   * that conflicts with the file name conventions, e.g. /foo/index.
   */
  route?: string;
```
IMO, it is a great feature to have, as there are always situations that leads to structuring the view files in a different way than what we expect them to be handled by the router, but when I export a config of type `ViewConfig` that tries to override the default route for a view by initializing the `route` property, it breaks the router functionality in the following ways:

* The default route is not resolved by the FS router anymore, so an attempt to hit that in the browser simply falls back to server-side router (ends up showing No Route Found message). 
* Attempting to hit the url with configured `route` for that view renders a blank page.  

### Expected-behavior

By defining a route in the exported `config` from a view, I expect to be able to override the default extracted route based on the file system, so that it works.  

### Reproduction

1. Taking a starter app
2. Create an `AboutView` under `frontend/views/about` so the automatically resolved route for it becomes `/about/AboutView` and verify that it works
3.  Export the following config from the `AboutView`:
```ts
export const config: ViewConfig = {
  route: "about"
};
```
4. Now the expected route for this view is `/about`, but navigating to it would result in rendering a blank page. 
5. The default route is not also working, so the `route` is not simply ignored, but causes a misbehaviour.

### System Info

Vaadin 24.4.0.alpha16

**Comment by cromoteca** [comment]
The `route` parameter allows to customize the current path item, not the whole path. This means that, since you're defining an `about` view in the `about` folder, you have to visit `/about/about` to see your configured page.

This could be pointed out in the comment, but changing the functionality to redefine the whole looks quite complicated to me, since in the generated JSON each item only contains the corresponding path level, so it's not easy to customize the whole thing.

**Comment by cromoteca** [comment]
I'd open another issue if the `route` parameter must configure the whole thing.
