### ISSUE TITLE
HMR does not work with 24.4.0.alpha18

### ISSUE THREAD

**Issue by Artur-** [vaadin/hilla#2277]
### Describe the bug

If you make a change to a view, a full reload takes place because of https://github.com/vaadin/hilla/blob/0961d0bb9b527ab8d27402b32cfe924501b70cc3/packages/ts/file-router/src/vite-plugin.ts#L95

### Expected-behavior

The view should be update with HMR

### Reproduction

Any project, any change to a view

### System Info

24.4.0.alpha18

**Comment by platosha** [comment]
Cannot reproduce, please provide more details. Changes to React rendering work with HMR. Changes to view metadata result in full reload.

**Comment by Artur-** [comment]
```
npx @hilla/cli init --pre mah-hillah
cd mah-hillah
npx upgrade-vaadin 24.4.0.alpha18
mvn
```

```
touch src/main/frontend/views/helloworld/HelloWorldView.tsx
```

**Comment by Legioth** [comment]
Seems like this is indeed always happening. I just didn't notice that the page was reloading since it all happens so fast that the screen itself doesn't flicker. You only notice the reload through the animation of the Development Mode popup or through the browser's network inspector .

**Comment by Artur-** [comment]
You notice it by typing "123" in the text field and it being gone after the change
