### ISSUE TITLE
Unnecessary warning in pure Flow project

### ISSUE THREAD

**Issue by tepi** [vaadin/hilla#2281]
### Describe the bug

Using 24.4-SNAPSHOT and running a pure Flow project, I get this in the server log:

`WARN 24788 --- [nio-8080-exec-2] .r.RouteUnifyingIndexHtmlRequestListener : Failed to find views.json under /Users/tepi/Downloads/drawer/./frontend/generated`

Originated somewhere in `com.vaadin.hilla.route.RouteUnifyingIndexHtmlRequestListener`

### Expected-behavior

When I only have Flow views, I do not expect this kind of warning.

### Reproduction

Run any pure Flow app and open a view with browser

### System Info

24.4-SNAPSHOT

**Comment by platosha** [comment]
Let's change the verbosity of this message to debug.
