### ISSUE TITLE
Project generated with Hilla CLI using flag --empty contains no empty view

### ISSUE THREAD

**Issue by rbrki07** [vaadin/hilla#2286]
### Describe the bug

A new Hilla project created with the Hilla CLI using the flag `--empty` does not contain an empty view. The Hilla CLI shows the following help text for the flag `--empty`:
>   --empty            Create a project with no menu and one empty view

The folder `frontend` does not contain a view.

### Expected-behavior

A new Hilla project created with the Hilla CLI using the flag `--empty` should contain an empty view.

Otherwise, the help text for the flag `--empty` should be changed.

### Reproduction

```shell
npx @hilla/cli init --empty hilla-project-with-no-menu-and-one-empty-view
``` 

### System Info

Hilla: 2.5.6
Hilla CLI: 2.0.1
Java: 21.0.2
OS: macOS Sonoma 14.4.1 (23E224)

**Comment by platosha** [comment]
Let's fix the CLI documentation.

**Comment by rbrki07** [comment]
Suggestion: `Create a project with no menu and no view(s)`?
