### ISSUE TITLE
Protected server route information is leaked to the browser

### ISSUE THREAD

**Issue by Artur-** [vaadin/hilla#2292]
### Describe the bug

Define an admin Java view like
```
@Route(value = "dashboard", layout = MainLayout.class)
@RolesAllowed("ADMIN")
public class DashboardView extends Main {
```

The existence of the route is leaked to the browser as 
```
window.Vaadin.server.views["/dashboard"]
```

### Expected-behavior

The route is only available for users with the ADMIN role and not discoverable without the role and knowledge of the url

### Reproduction

start.vaadin.com

- add a public view
- add a protected view

start the app and open the public view

### System Info

Vaadin 24.4 alpha20

**Comment by Legioth** [comment]
We need to add some APIs for controlling things to Flow to fix this properly: https://github.com/vaadin/flow/issues/19127

We shouldn't wait with fixing this problem until that API is implemented so let's just disable the whole feature by default and provide a crude way (e.g. a setting in `application.properties`) to explicitly enable it for testing purposes.
