### ISSUE TITLE
`MultiSelectComboBox` with `allowCustomValue` doesn't support `onCustomValueSet`

### ISSUE THREAD

**Issue by enimatek-nl** [vaadin/hilla#2303]
### Describe the bug

`MultiSelectComboBox` in the `@hilla/react-components` should support `onCustomValueSet` by documentation.

### Expected-behavior

The https://hilla.dev/docs/react/components/multi-select-combo-box refers to the https://hilla.dev/docs/react/components/combo-box#custom-value-entry for custom value entry. This works in Vaadin, but in Hilla only the `allowCustomValue` works but the `onCustomValueSet` is only available on the `ComboBox` and not on the `MultiSelectComboBox`.

### Reproduction

Try using the `MultiSelectComboBox` and follow the code snippet in the documentation and replace the ComboBox with MultiSelectComboBox:

```
<MultiSelectComboBox
  allowCustomValue
  label="Browser"
  helperText="Select or type a browser"
  items={items}
  onCustomValueSet={(event) => {
    setItems([...items, event.detail]);
  }}
/>
```

### System Info

MacOS 14.3.1
java.version: 21
vaadin.version: 24.3.9
hilla.version: 2.5.7

**Comment by knoobie** [comment]
This was already fixed and should be available in the next release: https://github.com/vaadin/react-components/issues/238#issuecomment-1985621120

**Comment by enimatek-nl** [comment]
> This was already fixed and should be available in the next release: [vaadin/react-components#238 (comment)](https://github.com/vaadin/react-components/issues/238#issuecomment-1985621120)

Thanks, I will close this bug.
