### ISSUE TITLE
How do I configure SQL authentication data sources for Spring Security?

### ISSUE THREAD

**Issue by Yue-plus** [vaadin/hilla#2307]
How do I configure SQL authentication data sources for Spring Security?
如何为 Spring Security 配置 SQL 认证数据源？

I saw in the [documentation](https://hilla.dev/docs/react/guides/security/spring-login#appendix-production-data-sources) that it mentioned the need to override the `configure(AuthenticationManagerBuilder auth)` method in the `VaadinWebSecurity` configuration class, but I did not find this method in Hilla 2.5.7.
我看到了 [文档](https://hilla.dev/docs/react/guides/security/spring-login#appendix-production-data-sources) 中提到了需要重写 `VaadinWebSecurity` 配置类中的 `configure(AuthenticationManagerBuilder auth)` 方法，但是我在 Hilla 2.5.7 中没有找到该方法。

![image](https://github.com/vaadin/hilla/assets/33195150/ff78e824-a992-442d-9882-55888aea4c7e)

**Comment by Yue-plus** [comment]
I followed the [documentation](https://hilla.dev/docs/react/guides/security/spring-login) to create a new project and tried to authentication with Spring Security.
我按照 [文档](https://hilla.dev/docs/react/guides/security/spring-login) 新建了一个项目，并试着使用 Spring Security 进行身份验证。

Why does the client not have permission to call `getUserInfo()`?
为什么在客户端没有权限调用 `getUserInfo()`？

![image](https://github.com/vaadin/hilla/assets/33195150/2d1b8c71-f2d0-4a62-a899-8de1fbe3ea15)
![image](https://github.com/vaadin/hilla/assets/33195150/a401143d-afae-4ce3-a738-c9a5d5bbe7b2)

**Comment by platosha** [comment]
As seen from the screenshots, the user isn't authenticated yet, and the `getUserInfo()` endpoint does not allow anonymous access, so it is correctly responding with the 401 error.

There has been a related issue fixed around handling this error from the Hilla auth side, see #2237.

Otherwise this seems to work as expected.
