### ISSUE TITLE
AutoGrid uses JSON renderer for column of type object, although a custom path is set.

### ISSUE THREAD

**Issue by rbrki07** [vaadin/hilla#2322]
### Describe the bug

Having two entities `Order` and `Customer` in a Many-To-One-Relation, I use `AutoGrid` to display `Orders` and I would like to configure `AutoGrid` to display `customer.name` in the column for `Customer` using a custom `path`:
```tsx
<AutoGrid 
    model={OrderModel} 
    service={OrderService}
    columnOptions={{
      customer: {
        path: "customer.name",
      }
    }} 
/>
```
Unfortunately, `AutoGrid` keeps using the `AutoGridJsonRenderer` for column `customer` and displays the whole object, although a custom `path` is set, that points to a single attribute:
![image](https://github.com/vaadin/hilla/assets/14867943/645f8d8b-b666-40f6-90aa-8cf541c2f742)

If I set the renderer to `null`, I get the desired result:
```tsx
<AutoGrid 
    model={OrderModel} 
    service={OrderService}
    columnOptions={{
      customer: {
        path: "customer.name",
        renderer: null
      }
    }} 
/>
```
![image](https://github.com/vaadin/hilla/assets/14867943/ff326496-7c1a-48a2-9783-226bf3ad6d46)

### Expected-behavior

AutoGrid should not use the `AutoGridJsonRenderer` for a column of type `object`, if a custom path is set. It should be sufficient to configure a custom `path`. Setting the `renderer` to `null` should not be required.

Please also see the [comment](https://vaadin.com/forum/t/manytoone-relation-in-autogrid/165954/6) by @sissbruecker in this Vaadin Forum Thread, where this issue was raised as a question.

### Reproduction

Create two entities like `Order` and `Customer`:
```java
@Entity
@Table(name = "orders")
public class Order {

    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    Long id;

    @NotNull
    private LocalDate created;

    @NotNull
    @ManyToOne(targetEntity = Customer.class, optional = false)
    private Customer customer;

   // Getters and Setters omitted

}

@Entity
@Table(name = "customers")
public class Customer {

    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    Long id;

    @NotBlank
    String name;

    @NotBlank
    @Email
    String mail;

   // Getters and Setters omitted   
}
```

Create a `OrderService`:
```java
@BrowserCallable
@AnonymousAllowed
public class OrderService extends CrudRepositoryService<Order, Long, OrderRepository> {}
```

Use `AutoGrid` like this:
```tsx
<AutoGrid 
    model={OrderModel} 
    service={OrderService}
    columnOptions={{
      customer: {
        path: "customer.name",
      }
    }} 
/>
```

Actual result:
![image](https://github.com/vaadin/hilla/assets/14867943/645f8d8b-b666-40f6-90aa-8cf541c2f742)

Expected result:
![image](https://github.com/vaadin/hilla/assets/14867943/ff326496-7c1a-48a2-9783-226bf3ad6d46)

### System Info

Hilla: 24.4.0.alpha21
Hilla CLI: 2.0.1
Java: 21.0.2
OS: macOS Sonoma 14.4.1 (23E224)

**Comment by platosha** [comment]
Thanks, looks like a bug indeed.

By the way, another possible workaround is to use a custom column, see https://hilla.dev/docs/react/components/auto-grid#adding-custom-columns

**Comment by platosha** [comment]
After fixing this, let us make sure that changing `path` in column options is sufficiently documented.

**Comment by rbrki07** [comment]
I would like to try and provide a pr for this, but I need a little help upfront, please. Where will I find the relevant code, that handles this logic? Is it in [vaadin/hilla](https://github.com/vaadin/hilla) or is it somewhere else, like in [vaadin/react-components](https://github.com/vaadin/react-components)?

**Comment by sissbruecker** [comment]
The Auto* components are in the Hilla repo itself. The relevant logic should be here (see also the defaults defined in the function above): https://github.com/vaadin/hilla/blob/be9a911be3413770a16b1e2af8314434fd7adb8f/packages/ts/react-crud/src/autogrid-columns.tsx#L103-L117

**Comment by rbrki07** [comment]
Thank you @sissbruecker! I already had a look at this piece of code, but I wasn't sure, if this is the right place. I think I need to invest some time to understand how the pieces fit together.

**Comment by rbrki07** [comment]
I'm not sure which way to go here. It could be possible to do something like this:
```tsx
  return customColumnOptions
    ? { 
        ...typeColumnOptions, 
        headerFilterRenderer, 
        ...customColumnOptions, 
        ...(customColumnOptions?.path && customColumnOptions.renderer === undefined) && { renderer: null }
      }
    : typeColumnOptions;
```

This would ensure the default renderer and would probably "fix" this issue.

Instead, we could go further, and we could create/load a `ModelInfo` instance for the referenced entity. This way we could determine which renderer to use, based on the type of the entity property referenced in `path`.

**Comment by taefi** [comment]
Btw, Another way of dealing with simple cases such as rendering the "customer.name" instead of the json representation of customer entities is to utilize the `visibleColumns`, e.g. in your case:
```tsx
<AutoGrid model={OrderModel} 
          service={OrderService}
          visibleColumns=['created', 'customer.name']
          columnOptions={{
              customer: {
                   header: "Customer"
              }
          }}
/>
``` 
This way, the default header filter is also working without any further efforts.
