### ISSUE TITLE
Routes do not work when using a context path

### ISSUE THREAD

**Issue by Artur-** [vaadin/hilla#2330]
### Describe the bug

When you use a servlet context path, e.g. /foo for the app, many things related to routes are broken

1. When you start the app, you see http://localhost:28666/foo/ but it shows the "route not found" view instead of the root mapped view
2. When you have an /about view, the route not found page links to /about instead of /foo/about. Clicking on it highlights "About" in the menu but shows the route not found page. Refreshing shows 404
3. If you click on the root view, it shows the root view but changes to url to / instead of /foo/ so refreshing gives 404
4. Opening http://localhost:28666/foo/about shows the "not found" view

### Expected-behavior

Everything just works when using a context path

### Reproduction

npx @hilla/cli init --react --pre context-path
+
```
server.servlet.context-path=/foo
```
in `src/main/resources/application.properties`

### System Info

24.4

**Comment by platosha** [comment]
Should be a matter of setting the `basename` correctly for React Router, see https://reactrouter.com/en/main/routers/create-browser-router#basename

**Comment by Artur-** [comment]
Some starter app used to have
```
const router = createBrowserRouter(routes, {basename: new URL(document.baseURI).pathname });
```

but this does not seem to be used currently by the fs router
