### ISSUE TITLE
[PT-PiT 24.4] Documentation is not helpful for adding a new Flow view to side menu

### ISSUE THREAD

**Issue by jojule** [vaadin/hilla#2335]
### Describe the bug

Failed find from documentation how to add a Flow view to a new project

### Expected-behavior

Expected a Flow view to visible in menu (Hilla views are available without any extra work)

Failing that, expected the documentation to explain how could I add the views to menu.

Potentially should give you example
```
<SideNavItem path="/flow">Flow view </SideNavItem>
```
And guide to add that to `src/main/frontend/views/@layout.tsx` somewhere inside `</SideNav>`.

### Reproduction

- Create a new Vaadin 2.4.0.alpha21 app with start vaadin com, including one Hilla view
- Upgrade to 2.4.0.alpha22
- Add a new Flow view 
- run with `mvnw`
- Observe that the new Flow view works
- Observe that it is not listed in the menu

Browse the documentation to find section about adding Flow view to Hilla
- It is very confusing as I do not understand what is a "Flow application" nor what is a "Hilla application". I created a "Vaadin application"
- It guides me to "Use Vaadin’s [Side Navigation](https://hilla.dev/docs/react/components/side-nav) or React’s [NavLink](https://hilla.dev/docs/react/guides/routing#adding-routes) / [Link](https://reactrouter.com/en/main/components/link) components to navigate from a Hilla view to a Flow view", giving a JS example. It does not hint where that code should be added. Example itself is not helpful for alpha22

### System Info

- Hilla: 24.4.0.alpha23
- Flow: 24.4.0.alpha29
- Vaadin: 24.4.0.alpha22
- Copilot: 24.4.0.alpha21

**Comment by Lodin** [comment]
Related to #2319

**Comment by Legioth** [comment]
We will "fix" this by introducing the `@Menu` annotation and the heuristics related to it already before the beta. The implementation is already under way and shouldn't take very long. In that way, it will just work out of the box in the basic cases and the other things would be covered by documentation specifically for `@Menu`.

**Comment by platosha** [comment]
Related: https://github.com/vaadin/docs/issues/3410

**Comment by mshabarov** [comment]
Adding a Flow view menu item is now as simple as adding `AtMenu` annotation to the Java class, annotated with `Route`, tested with V24.4.0.beta3.

The docs for how to mark a Flow view as a menu item is [here](https://vaadin.com/docs/next/flow/integrations/hilla#include-route-to-hilla-main-menu) and [here](https://vaadin.com/docs/next/hilla/guides/routing#creating-menu-from-routes) is an instruction how to use the automatic main menu with React/Hilla.

I believe this issue can be closed now.
