### ISSUE TITLE
[PT-PiT 24.4] Whitelabel error page - Hilla runner fails

### ISSUE THREAD

**Issue by gtzluis** [vaadin/hilla#2336]
### Describe the bug

Application fails to run > It seems the Hilla runner fails to find mvn in the project

Artur attempted to debug it, but we couldn't fix it

[hilla project failed log.txt](https://github.com/vaadin/hilla/files/15008195/hilla.project.failed.log.txt)
[hilla project failed log & Artur debug attempt.txt](https://github.com/vaadin/hilla/files/15008199/hilla.project.failed.log.Artur.debug.attempt.txt)

Please let me know if I'm doing something wrong :) 

### Reproduction

I downloaded a project from start.vaadin.com containing a Hilla + React view > changed version to 24.4.0.alpha22 > tried to run the application using VS Code. 

### System Info

Windows 11, Vaadin 24.4.0.alpha22, Chrome Version 123.0.6312.123 (Official Build) (64-bit)

**Comment by platosha** [comment]
Thanks.

Do you have Maven installed in your system? You can try by typing `mvn` on the command line.

Also, could try if it reproduces with the latest stable Hilla 2.5?

**Comment by ZheSun88** [comment]
i tried to download an app 
```
open start.vaadin.com
click `start a project`
click `Add the first view to your application`
click `Hilla(React)` -> ‘Hello World’ -> 'Add view'
click `download Project`

unzip the folder
run `mvn`
```

the version here is alpha24, there is no issue. 
downgrade to `alpha22`, issue with `could not navigate to ''`

windows machine.

**Comment by Artur-** [comment]
The original project was in a folder named something with space and (parenthesis) like `my-app (2)`, if it matters

**Comment by ZheSun88** [comment]
my folder is `my-app (13)` , so i guess that is not the issue.

**Comment by marcushellberg** [comment]
I happened to run into the same while recording a video, so here are my steps to reproduce. 

Not shown in the video: updating vaadin.version to 24.4.0.beta1 and adding pre-release repo to pom.xml.

https://github.com/vaadin/hilla/assets/883698/99f09247-0553-4278-a2c0-d9c27d6ba278

**Comment by ZheSun88** [comment]
oh, you downloaded the app from start.spring.io, i guess that is probably the reason.
as upgrading from Vaadin 24.3 to 24.4 needs some steps.

**Comment by mcollovati** [comment]
@ZheSun88 probably not related, but I got an error with Hilla internal Maven call with a reproducer project you attached to a GH issue; basically the `mvnw` had windows EOL, and it was unable to run, until I converted them.

**Comment by ZheSun88** [comment]
aww, i downloaded the app locally and upgraded things based on the video.
using `./mvnw`  i got  error in the image..
then i tried to `mvn spring-boot:run` , app is working..
![image](https://github.com/vaadin/hilla/assets/31067185/19262876-b612-4fcf-97bc-0fc32c916476)
![image](https://github.com/vaadin/hilla/assets/31067185/8bd71960-4b57-4473-a216-908b70be44c4)

**Comment by mcollovati** [comment]
@marcushellberg can you please set `logging.level.com.vaadin.hilla.engine.commandrunner=DEBUG` in the application properties and check in the server logs if there is additional information printed by the Hilla command runners?

**Comment by manolo** [comment]
I tried the same steps and cannot reproduce in my mac, I'm using java 21 but didnt change the java.version in the pom file, and also used the JavaAppliction.java play button for start the application in vscode. Seems some specific local setup

**Comment by manolo** [comment]
@marcushellberg does it happens always? I mean each time you stop and start the application, or only once at the beginning?

**Comment by mcollovati** [comment]
@marcushellberg did you add to the pom the Vaadin pre-releases both as `<repository>` and `<pluginRepository>`?

**Comment by manolo** [comment]
The only way I have managed to reproduce it is by removing the following block from the `pom.xml` file

```
   <pluginRepositories>
       <pluginRepository>
           <id>vaadin-prereleases</id>
           <url>https://maven.vaadin.com/vaadin-prereleases</url>
       </pluginRepository>
   </pluginRepositories>
```

Then the app works, and at some point endpoint generator tries to run `mvn -q com.vaadin:vaadin-maven-plugin:generate` displaying the following error in console.

```
com.vaadin.flow.server.ExecutionFailedException: Failed to configure Hilla engine: no runner succeeded. Set log level to debug to see more details.
	at com.vaadin.hilla.internal.AbstractTaskEndpointGenerator.prepareEngineConfiguration(AbstractTaskEndpointGenerator.java:122) ~[hilla-engine-runtime-24.4.0.beta1.jar:na]
```
Code executing this action is [here](https://github.com/vaadin/hilla/blob/main/packages/java/engine-runtime/src/main/java/com/vaadin/hilla/internal/AbstractTaskEndpointGenerator.java#L87)

So the problem is that hilla cannot run correctly the tasks for generating frontend stuff if the plugin cannot be downloaded.

Note that it only happens with pre-releases, because in the case of releases deployed in maven central, the plugin artifact would be downloaded.

Not sure if there is a way for fixing this, maybe a better message in console, or stoping the servlet container.

**Comment by manolo** [comment]
So in summary, in both cases the `mvn vaadin:configure` was not executed correctly @gtzluis logs happen in the same code line, perhaps some problem with `mvn` in local, and in the case of @marcushellberg perhaps he forgot to add the plugin repository.

**Comment by platosha** [comment]
It would probably help to have a more descriptive error message when `mvn vaadin:configure` fails. Let's address the error message in the scope of this ticket.
