### ISSUE TITLE
Using routeUtil::isRouteAllowed causes a redirect to /login when redeploying

### ISSUE THREAD

**Issue by Legioth** [vaadin/hilla#2358]
### Describe the bug

There seems to be some glitch with `routeUtil::isRouteAllowed` that triggers a redirect to `/login` while redeploying if you're not already logged in. The same does not happen with a hardcoded `new AntPathRequestMatcher("/")` rule.

### Expected-behavior

Expected to remain on the current view when redeploying even if I'm not logged in

### Reproduction

1. Configure an app on start.vaadin.com with a publicly accessible Hilla view at `/` and another Hilla view that requires login
2. Download, extract, and rename `views/.tsx` to `views/@index.tsx` to work around https://github.com/vaadin/start/issues/3037.
3. Run
4. Make a change to an unrelated Java file, e.g. by changing one of the returned strings in `HelloWorldService`.
5. Notice that you're redirected to `/login` after the server has redeployed.

You remain at `/` in step 5 if you replace the `routeUtil::isRouteAllowed` line in `SecurityConfiguration` with a hardcoded rule for the same URL: `http.authorizeHttpRequests().requestMatchers(new AntPathRequestMatcher("/")).permitAll();`

### System Info

Vaadin 24.4.0.alpha24

**Comment by cromoteca** [comment]
Maybe the registry is empty when the check happens? This would be a timing issue.

**Comment by taefi** [comment]
To me this sound like a timing issue, as Spring Security filters and (`routeUtil::isRouteAllowed`) are always called before the IndexHtmlListener (that is responsible for initializing the ClientRouteRegistry in DEV mode). We can Let the `RouteUnifyingServiceInitListener` to also attempt to initialize the ClientRouteRegistry in the DEV mode as well and silently log-n-ignore if the `file-routes.json` isn't available yet (this can happen in the initial clean run of the apps).
