### ISSUE TITLE
File router cannot handle view that have same names

### ISSUE THREAD

**Issue by abdullahtellioglu** [vaadin/hilla#2365]
### Describe the bug

I created two views that have same names but different paths. As you can see below, they are listing in available routes but one of them returns 404

![two-overlay-views](https://github.com/vaadin/hilla/assets/100126447/ffcf117e-915e-4bfa-8fb1-6f53e0b85284)

![pathing](https://github.com/vaadin/hilla/assets/100126447/e9527cf5-4497-4816-a5b2-c877d752b489)

Both have exported syntax like this(not sure if it is related though):
```typescript
const Overlay = () => { 
... 
} 
export default Overlay;
```

### Expected-behavior

Should handle both views in different paths. `/overlay` and `/overlay/overlay` should work.

### Reproduction

Create the same structure in an example project and you would get the same result

### System Info

Flow version: 24.4.0.alpha31
Platform version: 24.4.0.alpha24

**Comment by Artur-** [comment]
Does this work if you move `overlay.tsx` to be `overlay/@index.tsx`?

**Comment by abdullahtellioglu** [comment]
> Does this work if you move overlay.tsx to be overlay/@index.tsx?

Then `localhost:8080/overlay` works but `localhost:8080/overlay/overlay` does not. It should work because I have two separate files for both routes 
![overlay-with-index](https://github.com/vaadin/hilla/assets/100126447/648db5b1-b174-4b4e-96ed-28a4645f206a)

https://github.com/vaadin/hilla/assets/100126447/9d62ddee-ea31-4dbc-bb8e-bc94d576a417

**Comment by abdullahtellioglu** [comment]
Also, the menu has 2 overlay links

**Comment by platosha** [comment]
What could cause this is that we match the `/overlay` directory route, and then the Flow fallback index in that directory route also matches.

If we give less priority to directories over files when sorting FS route entries, it would solve this issue.
