### ISSUE TITLE
`window.Vaadin.server.views` contains all routes not just server-side routes

### ISSUE THREAD

**Issue by taefi** [vaadin/hilla#2375]
### Describe the bug

FS Router's generated routes from the `frontend/views` directory along with the registered server-side routes are being stored in the `window.Vaadin.server.views` by `RouteUnifyingIndexHtmlListener`. Either the `Vaadin.server.views` should only hold the server-side views, or the object should be renamed to something more general e.g. `Vaadin.views` (in case it doesn't clash with another existing global object). It's confusing to have all views under `Vaadin.server.views`. Also, the term `"views"` is probably better to change to `"routes"`.

### Reproduction

N/A

### System Info

N/A

**Comment by Legioth** [comment]
The vision for the long run is that it should be possible to filter and modify (e.g. translate menu titles) both client-side and server-side views through a Java API. Based on that, I would suggest that we keep all views in the structure but rename it.
