### ISSUE TITLE
createMenuItems includes parameterized routes

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/hilla#2378]
### Describe the bug

The menu items created by `createMenuItems` includes paths with parameters, leading to links like `users/{id}/edit` in the menu
![image_720](https://github.com/vaadin/hilla/assets/883698/cbe8823f-b277-416c-bb75-8f7552adab45)

### Expected-behavior

Only paths without parameters are shown

### Reproduction

Create the following structure in a Hilla starter `users/{id}/edit.tsx`

### System Info

Hilla 24.4.0.alpha25

**Comment by Legioth** [comment]
We are planning to add support for an automatic main menu also for Flow layouts and we wouldn't want to have parameterized Hilla routes in the Flow menu either. From this follows that it would be preferable to filter them out before reaching `index.html` (i.e. either in Java or the Vite plugin).

**Comment by Legioth** [comment]
Views with optional parameters should be in the menu except if excluded using the regular mechanism. It's only the ones with required parameters that must be left out since we cannot even generate a valid URL to such a view without knowing a parameter value.

**Comment by marcushellberg** [comment]
This is still broken in 24.4.0.rc1 with the same exact steps as in the initial issue description

**Comment by Legioth** [comment]
Seems like this is "only" broken for the case when the parameter is in the directory name.

`views/test/{id}.tsx` does not show up in the menu but `users/{id}/edit.tsx` does.

**Comment by Legioth** [comment]
Note that the problematic view also gets a (invalid) link in the dev mode 404 view. I suspect that's caused by the same root cause. If that's not the case, then we should fix only the menu issue right away and then fix the 404 page issue separately with lower priority.
