### ISSUE TITLE
file-routes.json cannot be found

### ISSUE THREAD

**Issue by mshabarov** [vaadin/hilla#2408]
### Describe the bug

Each Vaadin 24.4 application, that contains Hilla, shows this exception on startup, complaining about `file-routes.json` file not found:
```
java.io.FileNotFoundException: .../skeleton-starter-flow-spring/./src/main/frontend/generated/file-routes.json (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method) ~[na:na]
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216) ~[na:na]
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157) ~[na:na]
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111) ~[na:na]
	at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86) ~[na:na]
	at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:189) ~[na:na]
	at java.base/java.net.URL.openStream(URL.java:1161) ~[na:na]
	at com.vaadin.hilla.route.ClientRouteRegistry.registerClientRoutes(ClientRouteRegistry.java:158) ~[hilla-endpoint-24.4-20240506.022159-195.jar:na]
	at com.vaadin.hilla.startup.RouteUnifyingServiceInitListener.serviceInit(RouteUnifyingServiceInitListener.java:101) ~[hilla-endpoint-24.4-20240506.022159-195.jar:na]
```

This, however, doesn't affect the application behaviour and most likely an intermediate state during the build, when this file isn't created yet.

Related-to https://github.com/vaadin/hilla/issues/2358#issuecomment-2079454615, as a possible way to fix it, this exception can be ignored in the `ClientRouteRegistry`.

### Expected-behavior

No exception

### Reproduction

Any Hilla or Flow+Spring-Boot starter for Vaadin 24.4.

### System Info

Vaadin 24.4.0.beta2

**Comment by ZheSun88** [comment]
this actually affects my application with the following steps. 

```
download the app using this preset https://start.vaadin.com/dl?&preset=test-hybrid-react&projectName=test-hybrid-react&preset=partial-prerelease
unzip
./mvnw
navigate to localhost:8080 [1]
click Hello Hilla
click Hello Flow
```

- [1]
![image](https://github.com/vaadin/hilla/assets/31067185/bb9c0b72-8b3d-4ada-8ad1-5a6107579c9c)

- [2]
the url goes to `about:blank#blocked` and leave a blank screen 
![image](https://github.com/vaadin/hilla/assets/31067185/8a6f1e76-a38e-4213-a98a-69ed7d607649)

**Comment by taefi** [comment]
@ZheSun88 I haven't looked into this yet, but that error log is only happening when a clean app (mostly when a newly created one) is started as the result of an eager attempt for initializing the `ClientRouteRegistry` and that error log should be just silently ignored as it is expected not to have the `file-routes.json` in that phase for a new/clean app. 
I'd say it has nothing to do with what you've described above, and it's a separate issue (highly probably a blocker) that should be resolved.

**Comment by ZheSun88** [comment]
I can create a separate issue if necessary..

**Comment by Artur-** [comment]
Create a new issue, we need to fix this first to avoid that everybody associates all new issues with this stack trace when no other stack trace is shown

**Comment by mcollovati** [comment]
I think it is related to the fact that the Flow view has a route template parameter

```
@Route(value = "/:samplePersonID?/:action?(edit)")
@RouteAlias(value = "")
@Uses(Icon.class)
public class HelloFlowView extends Div implements BeforeEnterObserver {
```

If you replace the `@Route(value = "/:samplePersonID?/:action?(edit)")` part with `@Route("")` (also removing the alias) the menu link seems to work,

**Comment by ZheSun88** [comment]
@mcollovati then it seems the problem comes from the app itself than flow/hilla? 

if so, we need to fix that in start project on how to generate this project.

**Comment by mcollovati** [comment]
I'm not sure. The `/:samplePersonID?/:action?(edit)` is a valid route in a Flow application, but I don't know if it is supported in the autogenerated menu.

**Comment by ZheSun88** [comment]
aww.. okay.. anyway.. i will make this to another ticket.. :-)
