### ISSUE TITLE
Menu route items are not visible 

### ISSUE THREAD

**Issue by abdullahtellioglu** [vaadin/hilla#2414]
### Describe the bug

An example project from Copilot and a project downloaded from start do not have any route items in Drawer  However `frontend/generated/file-routes.ts` has the route definitions. Additionally, routes are visible on flow projects. 

![sidenav-empty](https://github.com/vaadin/hilla/assets/100126447/6da14ff7-d0d1-4cc1-bea7-bb82db7ca4b6)

```
import type { AgnosticRoute } from "@vaadin/hilla-file-router/types.js";
import { createRoute } from "@vaadin/hilla-file-router/runtime.js";
import * as Page0 from "../views/@index.js";
import * as Page1 from "../views/hello-world.js";
import * as Layout2 from "../views/@layout.js";
const routes: readonly AgnosticRoute[] = [createRoute("", Layout2, [createRoute("", Page0), createRoute("hello-world", Page1)])];
export default routes;

```

- 

### Expected-behavior

Routes should be rendered in Sidenav properly.

### Reproduction

Download a project from start.vaadin.com or open the project. 

[my-app (39).zip](https://github.com/vaadin/hilla/files/15304759/my-app.39.zip)

### System Info

Vaadin version: 24..5-SNAPSHOT
OS: MacOS 14.4.1 (23E224)

**Comment by Artur-** [comment]
This is probably because 24.5-SNAPSHOT downgrades hilla npm dependencies from 24.4 beta2 to 24.4 beta1

**Comment by taefi** [comment]
Just a side note: 
Apart from what the actual cause of this issue is, the menus are populated based on the value of the `window.Vaadin.views` global object, that in turn is being initialized based on the entries of `file-routes.json` not the `file-routes.ts`. However, when there are proper routes imported in the `file-routes.ts`, it can be assumed that the proper values are also present in the `file-routes.json`.

**Comment by taefi** [comment]
Hi @abdullahtellioglu, 
I gave your attached application a try with beta3 and couldn't reproduce the issue, the output looks like this:
![Screenshot 2024-05-22 at 14 41 37](https://github.com/vaadin/hilla/assets/70698630/ac45945e-9a8d-496b-93c0-4bf0d2f977db)
Is this still an issue for you or could we close it?

**Comment by abdullahtellioglu** [comment]
I cannot reproduce it either. Closing the issue as complete 👍  Thanks @taefi
