### ISSUE TITLE
Missing hilla-file-router in generated file-routes.ts

### ISSUE THREAD

**Issue by whiteancient** [vaadin/hilla#2454]
### Describe the bug

ERROR(TypeScript)  Cannot find module '@vaadin/hilla-file-router/types.js' or its corresponding type declarations.
[v-server-output] c.v.b.devserver.DevServerOutputTracker   :  FILE  C:/x/frontend/generated/file-routes.ts:1:36
[v-server-output] c.v.b.devserver.DevServerOutputTracker   : 
[v-server-output] c.v.b.devserver.DevServerOutputTracker   :   > 1 | import type { AgnosticRoute } from "@vaadin/hilla-file-router/types.js";
[v-server-output] c.v.b.devserver.DevServerOutputTracker   :       |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[v-server-output] c.v.b.devserver.DevServerOutputTracker   :     2 | const routes: readonly AgnosticRoute[] = [];
[v-server-output] c.v.b.devserver.DevServerOutputTracker   :     3 | export default routes;
[v-server-output] c.v.b.devserver.DevServerOutputTracker   :     4 |
[v-server-output] c.v.b.devserver.DevServerOutputTracker   : 
[v-server-output] c.v.b.devserver.DevServerOutputTracker   : [TypeScript] Found 1 error. Watching for file changes.

### Expected-behavior

No errors

### Reproduction

I upgraded from Vaadin 24.3.0 and Hilla 2.5.0 till Vaadin/Hilla 24.4.0.beta3

### System Info

Windows 11 and IntelliJ JVM

**Comment by whiteancient** [comment]
After deleting node-modules, package-lock etc it seems to have gone away. Sorry for stupid ticket.

**Comment by taefi** [comment]
@whiteancient no worries! It's great that you're trying out the prereleases. Early indication of any potential problems are very valuable for us. Please keep on trying out next Beta(s) and RC(s) and report whatever seems suspicious.
