### ISSUE TITLE
Permanent Endpoint search log entries

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/hilla#2476]
### Describe the bug

When endpoint hot redeployment is activated, Hilla spams the server log with 
```
2024-05-25T08:50:17.804+02:00  INFO 5984 --- [pool-6-thread-1] com.vaadin.hilla.parser.core.Parser      : Search for endpoints in directories [C:\Arbeit\workspace\other\hilla-crm\target\classes]
```

Please change it to a lower log level (debug).

### Expected-behavior

Logging should be on debug level

### Reproduction

Create an hilla application.
Activate endpoint hot redeploy in the application properties.
Start the application and wait.

### System Info

Hilla 24.4.0.beta5

**Comment by taefi** [comment]
Well, this is happening in the [Parser](https://github.com/vaadin/hilla/blob/24.4/packages/java/parser-jvm-core/src/main/java/com/vaadin/hilla/parser/core/Parser.java#L326), so in an application without any endpoint hot-reload, this is happening only once during the startup as an info during the development, and if we change this debug, then applications without this feature enabled no longer will see that one INFO log anymore. Not sure if we should make it complicated by passing around the value of `hilla.endpoint.hot-reload` for the purpose of logging.

**Comment by taefi** [comment]
Based on the internal discussion, changing the log level to DEBUG is acceptable and it's not necessary to make the API complex for the sake of logging that one line of INFO/DEBUG conditionally.
