### ISSUE TITLE
@JsonValue/@JsonCreate generates unknown type when value object extends generic base class

### ISSUE THREAD

**Issue by peholmst** [vaadin/hilla#2499]
### Describe the bug

Given the following base class for value objects:

```java
public abstract class SingleValueObject<T> {

    private final T value;

    public SingleValueObject(T value) {
        this.value = value;
    }

    public T value() {
        return value;
    }
}
```

And the following concrete implementation:

```java
public final class TimeZone extends SingleValueObject<String> {

    @JsonCreator
    public TimeZone(String value) {
        super(value);
    }

    @Override
    @JsonValue
    public String value() {
        return value;
    }
}
```

When used like this:

```java
public record LocationReference(
        @Nonnull TimeZone timeZone
) 
```

The generated TypeScript looks like this:

```typescript
interface LocationReference {
    timeZone: unknown;
}
export default LocationReference;
```

### Expected-behavior

The generated TypeScript should look like this (`string` instead of `unknown`):

```typescript
interface LocationReference {
    timeZone: string;
}
export default LocationReference;
```

### Reproduction

Create the classes described above in a project and generate the corresponding TypeScript types.

### System Info

MacOS 14.5, Chrome 125.0.6422.114, Vaadin 24.5.0.alpha1.

**Comment by Legioth** [comment]
Potentially related to https://github.com/vaadin/hilla/issues/579

**Comment by cromoteca** [comment]
Will be fixed by https://github.com/vaadin/hilla/pull/2615.
