### ISSUE TITLE
404 should be returned when there is a layout but no view

### ISSUE THREAD

**Issue by Artur-** [vaadin/hilla#2539]
### Describe the bug

If you have `src/main/frontend/views/@layout.tsx` but no `src/main/frontend/views/@index.tsx` then opening / returns the layout without any contents

### Expected-behavior

It should return the "route not found" page as there is no `@index.tsx`

### Reproduction

start.vaadin.com -> new project -> download -> run

### System Info

24.4.1

**Comment by platosha** [comment]
It seems not possible to reproduce, start.vaadin.com generates a Java MainLayout project. Steps for Hilla:

start.vaadin.com → new project → add Hilla view (adds as index) → download → delete Hilla `@index.tsx` view
