### ISSUE TITLE
Error checkbox use with AutoCrud component

### ISSUE THREAD

**Issue by ta2khu75** [vaadin/hilla#2547]
### Describe the bug

Error when use groupcheckbox with autocrud

### Expected-behavior

I unchecked all check box role but I got checked role user

### Reproduction

![Screenshot from 2024-06-14 17-12-28](https://github.com/vaadin/platform/assets/118422652/78766730-bdde-442b-b08e-f0d97f1c8c53)
![Screenshot from 2024-06-14 17-12-35](https://github.com/vaadin/platform/assets/118422652/f0d94a43-bb32-4bcf-8e0a-1bd85fbc0010)
![Screenshot from 2024-06-14 17-12-46](https://github.com/vaadin/platform/assets/118422652/ffb4c02e-0120-495b-a7ef-d28660403469)
![Screenshot from 2024-06-14 17-12-55](https://github.com/vaadin/platform/assets/118422652/f7368e01-226e-4cf5-a6eb-b1a85d714d5c)

### System Info

I using vaadin hilla 24.4.1 with react on browser firefox and system ubuntu

**Comment by krissvaa** [comment]
Typescript undefined issue fixed with:  https://github.com/vaadin/hilla/pull/2707

Another issue is that CheckboxGroup checkboxes are not disabled in AutoForm:
![image](https://github.com/user-attachments/assets/f06286ef-b9d6-44cc-8613-dd27db7e1659)
