### ISSUE TITLE
Maven Plugin: [WARNING] The 'configure' goal is only meant to be used in Hilla projects with endpoints

### ISSUE THREAD

**Issue by leluna** [vaadin/hilla#2548]
### Description of the bug

When using Vaadin maven plugin as documented with either `prepare-frontend` or `build-frontend` goal, the `configure` goal seem to always be activated even if there is no Hilla dependency. This leads to a warning that states "The 'configure' goal is only meant to be used in Hilla projects with endpoints.", which is irritating as it suggests that the configuration of the plugin is not correct.

### Expected behavior

Either the `configure` goal is only executed if there is Hilla dependency on the classpath, or the warning is a info instead stating that the configure goal is skipped as there is no Hilla dependency.

### Minimal reproducible example

* Download the starter
* Exclude Hilla dependency
* Build

### Versions

- Vaadin / Flow version: 24.4.2
- Java version: 17
- OS version: Windows
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by Artur-** [comment]
This is the same as 
- #2440
