### ISSUE TITLE
Warning when adding a new route

### ISSUE THREAD

**Issue by Artur-** [vaadin/hilla#2551]
### Describe the bug

If you add a route you see
```
Warning: You are calling ReactDOMClient.createRoot() on a container that has already been passed to createRoot() before. Instead, call root.render() on the existing root instead if you want to update it.
```

and then the page is reloaded

### Expected-behavior

The route is added, there is no warning and the page is not reloaded

### Reproduction

`npm init vaadin` 

Choose Hilla views

`mvn`

`cp src/main/frontend/views/about-hilla.tsx src/main/frontend/views/about2.tsx` after the app is open

### System Info

24.4.3

**Comment by cromoteca** [comment]
Related to #2552

**Comment by Artur-** [comment]
This might have been solved in the latest version
