### ISSUE TITLE
Translations are not refreshed without full server restart

### ISSUE THREAD

**Issue by Legioth** [vaadin/hilla#2554]
### Describe the bug

Changes to translation files are not picked up by a regular redeploy but only after the server is restarted.

### Expected-behavior

Expected that I can update translations while developing without having to constantly restart the server.

### Reproduction

1. Download a "Hello World Project" with Hilla / React from start.vaadin.com
2. Import into an IDE (I used VS Code) an launch Application.java
3. Enable the Hilla I18n feature flag (I did it through Copilot) and restart the server
4. Add `vaadin-i18n/translations_en.properties` containing a single line: `greeting = Hello in English`.
5. Add `await i18n.configure({language: "en"});` to `@layout.tsx`
6. Change the button label in `@index.tsx` to `{translate("greeting")}`
7. Observe that the translation is used
8. Change the translation file to `greeting = Hello in English2`
9. Observe that the server redeployed and that the page is reloaded in the browser, but the button text keeps using the old translation.
10. Restart the server. Observe that the new translation is now used.

### System Info

Vaadin 24.4.3

**Comment by cromoteca** [comment]
I debugged the application using Spring Dev Tools and I see that in [DefaultI18NProvider::getBundle](https://github.com/vaadin/flow/blob/2586444dce0ffa982c2aaaba1043eef5ccca05c4/flow-server/src/main/java/com/vaadin/flow/i18n/DefaultI18NProvider.java#L112-L118) the class loader is `AppClassLoader` and not the _restart_ classLoader that should allow to reload the file.

**Comment by mcollovati** [comment]
For Spring applications, the default `I18NProvider` bean is created by `DefaultI18NProviderFactory`, providing its classloader (`DefaultI18NProviderFactory.class.getClassLoader()`)  to the `DefaultI18NProvider` constructor.
