### ISSUE TITLE
Flow view with default route it is not loaded in hybrid application

### ISSUE THREAD

**Issue by MarcinVaadin** [vaadin/hilla#2571]
### Describe the bug

Flow view with default route it is not loaded in hybrid application.

[Slack thread](https://vaadin.slack.com/archives/C6X43FE8M/p1719218290742189)

From @caalador:
> I can see hilla generating into file-routes.ts the line createRoute("", Layout0) which I expect overrides the flow "" route as it's a match on the client router

### Expected-behavior

View should be loaded and rendered

### Reproduction

Create new Start project, add new Custom View with single button, download it as hybrid application.

### System Info

Hilla: 24.4.1
Flow: 24.4.2
Vaadin: 24.4.3
Copilot: 24.4.3
Copilot IDE Plugin: 1.0.9-intellij
Java: Oracle Corporation 22.0.1
Java Hotswap: false
Frontend Hotswap: Enabled, using Vite
OS: aarch64 Mac OS X 14.5
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

**Comment by Artur-** [comment]
Fixed in #2572, released in 24.4.4
