### ISSUE TITLE
Javascript error on submit for an invalid form

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/hilla#2586]
### Describe the bug

When I submit a form that is invalid I have a javascript error.
```
Uncaught (in promise) ValidationError: There are validation errors in the form.
 - fullName - NotNull: must not be null
    at BinderRoot.submitTo (chunk-UA3PFYSQ.js?v=5a255b3a:1929:13)
```

### Expected-behavior

I don't expect a javascript error for a validation error that is handled in my form.
Especially because the documentation says:
> Submission failures are handled automatically, so there is no need to do an explicit try-catch.

https://vaadin.com/docs/latest/hilla/guides/forms/binder-load#saving-data

### Reproduction

Run this project:
https://github.com/jcgueriaud1/hilla-example-form

Go to the home page and click on save, see the error in the console.

### System Info

Vaadin 24.4.4

**Comment by cromoteca** [comment]
The current behavior handles validation errors, but the main error itself is not handled and goes to the browser, which puts it in the console.
Either we add some default handling, or we change the documentation to better explain what happens.
An example of full handling is in the [AutoForm](https://github.com/vaadin/hilla/blob/ca6c731680fcff3700c52d7e21004bc04b52c4cb/packages/ts/react-crud/src/autoform.tsx#L297-L323).
Let's update the documentation.
