### ISSUE TITLE
Endpoint returns model or undefined array

### ISSUE THREAD

**Issue by abdullahtellioglu** [vaadin/hilla#2606]
### Describe the bug

I have an endpoint that returns a list of objects. In frontend, I would expect the response type would be an Object[] array not  `Array<MyObject,undefined>` which is never the case. 
<img width="874" alt="response-1" src="https://github.com/user-attachments/assets/5bf7c53e-db28-4085-bbcd-cf97b0ab25fe">

<img width="382" alt="response-2" src="https://github.com/user-attachments/assets/d67296f2-38cc-4885-abaf-93ba6edef79c">

### Expected-behavior

Response should return Array<MyObject> 

### Reproduction

Download the example project and open dev tools to hit debugger.

[bugrap-hilla.zip](https://github.com/user-attachments/files/16195949/bugrap-hilla.zip)

### System Info

Hilla: 24.5.0.alpha4
Flow: 24.5.0.alpha6
Vaadin: 24.5.0.alpha4
Copilot: 24.5.0.alpha4
Copilot IDE Plugin: 1.0-SNAPSHOT-intellij
Java: Oracle Corporation 22.0.1
Java Hotswap: false
Frontend Hotswap: Enabled, using Vite
OS: aarch64 Mac OS X 14.5
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

**Comment by Artur-** [comment]
See https://vaadin.com/docs/latest/hilla/reference/type-nullability

**Comment by abdullahtellioglu** [comment]
Should it not be reversed? You never expect a null element in a list unless it is marked explicitly by default.

**Comment by cromoteca** [comment]
In Java, if you write `List<Issue>`, both the list and its items can be null. You can use `@NonNullApi` if you want to avoid putting nullability annotations everywhere.

The TypeScript is generated as expected, so I'm going to close this issue.
