### ISSUE TITLE
add support for both SSR and CSR in hilla(just like qwik)

### ISSUE THREAD

**Issue by muhammadismailkhan0009** [vaadin/hilla#2607]
### Describe your motivation

currently, hilla,despite being full-stack framework, only supports CSR of template.
Whereas the potential of combining React with spring boot in single full-stack application is to actually add both SSR and CSR support in it(just like what qwik does). 
This will provide all the benefits of SSR and CSR while countering any SEO and js download latency issues.

### Describe alternatives you've considered

i have considered using qwik as if offers what i am seeking. but given the fact that both qwik and hilla being full-stack frameworks as well as hilla providing react facility, it would be a very good addition if hilla is made to act just like qwik.

**Comment by Legioth** [comment]
Server-side rendering of React templates is far from trivial with a Java server. It's probably doable e.g. by running the React through GraalVM on the server but we haven't looked into exactly what kinds of compromises that would lead to.
