### ISSUE TITLE
[Full-stack Signals] subscribe and update calls to SignalsHandler should be secured

### ISSUE THREAD

**Issue by taefi** [vaadin/hilla#2642]
### Describe the bug

When acquiring an instance of a full-stack signal in the client-side code, the call made to the endpoint that exposes a shared value as a signal instance can have the same method security similar to any other endpoint methods in Hilla framework. However, the subsequent calls to a signal instance is not secured. These subsequent calls are handled by an automatically registered endpoint called SignalsHandler that doesn’t apply any security checks on the request (as of now).

### Expected-behavior

Developers should be able to restrict access to shared signal instance (on the server). In other words, It should be possible to restrict access to a shared signal instance, for instance, the same shared signal instance:
- might be unavailable at all for anonymous users
- could have read-only access for anonymous users or users with insufficient privileges
- could be read and manipulated by users with sufficient privileges

### Reproduction

Currently, the developers can define these fine-grained rules on an endpoint method that exposes a (shared) signal instance. But, the `SignalsHandler` is not applying them when `subscribe` or `update` methods are getting called from client-side.

**Comment by platosha** [comment]
For the scope of this ticket, let's consider only checking access to the signal. Checking the kind of access (manipulation vs read-only) is out-of-scope.
