### ISSUE TITLE
In Dev-Mode, AutoCrud throws error when selecting an entity of which one field has the value null

### ISSUE THREAD

**Issue by sahrmann** [vaadin/hilla#2643]
### Describe the bug

If I use an `<AutoCrud>`-Component and I select an entity of which one field is `null`, the following error is shown:

```
Unexpected Application Error!
baseQueue is undefined

updateReducer@http://localhost:8080/VAADIN/@fs/../my-app/node_modules/.vite/deps/chunk-E4UNORPT.js?v=65bb8eeb:11752:25
useReducer@http://localhost:8080/VAADIN/@fs/../my-app/node_modules/.vite/deps/chunk-E4UNORPT.js?v=65bb8eeb:12737:24
useReducer@http://localhost:8080/VAADIN/@fs/../my-app/node_modules/.vite/deps/chunk-IF5A3MEL.js?v=65bb8eeb:1070:29
useUpdate@http://localhost:8080/VAADIN/@fs/../my-app/node_modules/.vite/deps/@vaadin_hilla-react-crud.js?v=65bb8eeb:1211:52
useForm@http://localhost:8080/VAADIN/@fs/../my-app/node_modules/.vite/deps/@vaadin_hilla-react-crud.js?v=65bb8eeb:1328:18
AutoForm@http://localhost:8080/VAADIN/@fs/../my-app/node_modules/.vite/deps/@vaadin_hilla-react-crud.js?v=65bb8eeb:1492:23
renderWithHooks@http://localhost:8080/VAADIN/@fs/../my-app/node_modules/.vite/deps/chunk-E4UNORPT.js?v=65bb8eeb:11548:35
updateFunctionComponent@http://localhost:8080/VAADIN/@fs/../my-app/node_modules/.vite/deps/chunk-E4UNORPT.js?v=65bb8eeb:14582:28
beginWork@http://localhost:8080/VAADIN/@fs/../my-app/node_modules/.vite/deps/chunk-E4UNORPT.js?v=65bb8eeb:15924:22
beginWork$1@http://localhost:8080/VAADIN/@fs/../my-app/node_modules/.vite/deps/chunk-E4UNORPT.js?v=65bb8eeb:19753:22
performUnitOfWork@http://localhost:8080/VAADIN/@fs/../my-app/node_modules/.vite/deps/chunk-E4UNORPT.js?v=65bb8eeb:19198:20
workLoopSync@http://localhost:8080/VAADIN/@fs/../my-app/node_modules/.vite/deps/chunk-E4UNORPT.js?v=65bb8eeb:19137:30
renderRootSync@http://localhost:8080/VAADIN/@fs/../my-app/node_modules/.vite/deps/chunk-E4UNORPT.js?v=65bb8eeb:19116:15
recoverFromConcurrentError@http://localhost:8080/VAADIN/@fs/../my-app/node_modules/.vite/deps/chunk-E4UNORPT.js?v=65bb8eeb:18736:42
performConcurrentWorkOnRoot@http://localhost:8080/VAADIN/@fs/../my-app/node_modules/.vite/deps/chunk-E4UNORPT.js?v=65bb8eeb:18684:30
workLoop@http://localhost:8080/VAADIN/@fs/../my-app/node_modules/.vite/deps/chunk-E4UNORPT.js?v=65bb8eeb:197:50
flushWork@http://localhost:8080/VAADIN/@fs/../my-app/node_modules/.vite/deps/chunk-E4UNORPT.js?v=65bb8eeb:176:22
performWorkUntilDeadline@http://localhost:8080/VAADIN/@fs/../my-app/node_modules/.vite/deps/chunk-E4UNORPT.js?v=65bb8eeb:384:29
```

This only happens in dev mode with vite serving the frontend. If I build a production bundle, everything works fine.

### Expected-behavior

There should not be an error and the form should be shown, with `null` fields being empty.

### Reproduction

Fresh Hilla app. 

- create a `TestEntity` with the properties `id` and `name`.
- create a `TestRepository extends CrudRepository<TestEntity, Long>, JpaSpecificationExecutor<TestEntity>`
- create a `TestService extends CrudRepositoryService<TestEntity, Long, TestRepository>` and annotate with `@BrowserCallable`
- create a class `Runner implements CommandLineRunner`, annotate with `@Component` and autowire the `TestRepository`. Create and save two `TestEntity`s, one with `name = null` and one with `name = "Test"` 
- in a frontend view, create an `<AutoCrud service={TestService} model={TestEntityModel}></AutoCrud>`

Run `vaadin:prepare-frontend`, start the app.

- click on the Entity named `Test`: Form is filled
- click on the Entity with no name: an error is shown

Build a production bundle and retry clicking on the Entity with no name: no error

### System Info

Vaadin 24.4.7

**Comment by platosha** [comment]
Needs to be investigated, the cause could be same as in #2658.
