### ISSUE TITLE
[Full-stack Signals] Add automatic resynchronization

### ISSUE THREAD

**Issue by platosha** [vaadin/hilla#2653]
A signal instance that has subscribers will automatically resynchronize with the server when the client reconnects to the server after having been disconnected. While disconnected, the signal value remains set to the value that was last seen before going losing the connection, supplemented with latency compensation for any pending operations. Pending operations that have been performed while disconnected will be sent to the server when the connection is restored (assuming the same client-side instance is still in active use).

```tsx
const counter = CounterService.counter();

effect(() => console.log("Value update:", counter.value));

addEventListener("offline", () => {
  console.log("Value when going offline:", counter.value);
  
  // Will be logged immediately thanks to latency compensation but delivered to the server only when connectivity is restored
  counter.incrementBy(1);
});

addEventListener("online", () => {
  // Nothing to do here since any change from the server hasn't yet been retrieved but that will happen soon
});
```

Note that the implementation should also recover from network connectivity issues that cause the connection with the server to be broken even though the browser fires no `offline` and `online` events.

**Comment by platosha** [comment]
Workflow notes:
- Any changes on the client are considered happening after any changes from the server. The server acts first.
- We should never rewrite history. After the server confirms the change, the order is never changed.

**Comment by platosha** [comment]
Note that there is a `.result` Promise on every operation result.

**Comment by platosha** [comment]
Note: reusing Flux is not in the scope of this ticket. We assume here that the server has disposed the Flux instance.

**Comment by platosha** [comment]
For now, let us drop the concept of buffering the outgoing operations. At the same time, we have no guarantee yet on wether the outgoing operations were received by the server or not. We'll come back to this when we have a proper event log.

**Comment by Legioth** [comment]
Buffering operations and making sure they are delivered exactly once is now described in https://github.com/vaadin/hilla/issues/2721.
