### ISSUE TITLE
[push] client tries to reconnect to a Flux that no longer exists

### ISSUE THREAD

**Issue by cromoteca** [vaadin/hilla#2716]
### Describe the bug

https://github.com/vaadin/hilla/pull/2684 introduced support for reconnection, but if the underlying Flux is no longer active, that reconnection keeps trying indefinitely.

That can happen, for example, after server timeout (`ApplicationConfig.WEBSOCKET_IDLETIME` in the Atmosphere servlet configuration).

### Expected-behavior

When the Flux is no longer there, the retry should stop at the first attempt and the API should give the developer an option to reconnect. There's no universal logic for that: only the developer knows what to do in that case.

### Reproduction

Configuring a short idle time (it's in milliseconds) allows to test that case easily.

### System Info

Hilla 24.5.alpha13

**Comment by Legioth** [comment]
> There's no universal logic for that: only the developer knows what to do in that case.

In other words, it should trigger the `onDisconnect` callback that was introduced in https://github.com/vaadin/hilla/pull/2684.
