### ISSUE TITLE
Allow getting form state inside fieldOptions > renderer for AutoForm

### ISSUE THREAD

**Issue by pratikpanchal4472** [vaadin/hilla#2754]
### Describe your motivation

I have to render a conditional field based on value of other field. right now with auto form it seems to be not supported. 
I am using fieldOptions > renderer property to customize both the fields but the dependent field cannot get the value of other field.

I want to perform something similar to what mentioned over here but with AutoForm:
https://vaadin.com/docs/latest/hilla/guides/forms/form-status-tracking#example-populate-a-field-based-on-another

### Describe the solution you'd like

Allow for a propety to share state of whole form from the caller component and update that state when the form values changes. AutoForm has this item propery, if we accept the setter for that then updating the same state can help handle fieldOptions rendering.

```
const [formState, setFormState] = useState<any>({country: '' , city: ''});

<AutoForm service={AddressService}
                            model={AddressModel}
                            item={formState}
                            onChange={(value) => setFormState(value)}
```

observe the onChange method.

### Describe alternatives you've considered

I tried using useForm hook with AutoForm but it seems not to update the value.
Happy to understand if there are any other ways possible and available currently.

**Comment by platosha** [comment]
Should be already available by using `layoutRenderer`, which has access to entire form state and models:

```tsx
<AutoForm layoutRenderer={({ form }) =>
  <VerticalLayout>
    <TextField {...form.field(form.model.name)} />
    { form.value.option ? 'yes' : 'no' }
  </VerticalLayout>
/>
```

The `form` provides the entire `useForm` hook result from the Hilla forms library. You can also modify the state by calling e. g., `form.setValue(form.model.fieldName, 'newValue')`

**Comment by pratikpanchal4472** [comment]
@platosha The ask is without the need for layoutRenderer. 
I will have to still write the boiller plat to arrange my fields.
