### ISSUE TITLE
Default value is required for nullable ValueSignal methods

### ISSUE THREAD

**Issue by Legioth** [vaadin/hilla#2760]
### Describe the bug

It's expected that a signal method defined to not allow null values would require defining a default value that will be used before a value has been fetched from the server. But it feels pointless that I have to define a default value also when the value is nullable since `undefined` would be a perfectly reasonable default value in such cases.

### Expected-behavior

Expected that the generated TS function requires a default value when the type is `ValueSignal<X>` but not when the type is `ValueSignal<X | undefined>`.

### Reproduction

N/A

### System Info

Hilla 24.5.0.beta2

**Comment by platosha** [comment]
Let's address as part of #2746
