### ISSUE TITLE
Conflict with springdocs "/swagger-ui/index.html"

### ISSUE THREAD

**Issue by kirmorozov** [vaadin/hilla#2763]
### Describe the bug

Added Hilla to Gradle(Kotlin) config along side with 
```
    implementation(platform("org.springdoc:springdoc-openapi:2.6.0"))
    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui")
    implementation("org.springdoc:springdoc-openapi-starter-webflux-ui")
```

### Expected-behavior

I still can access /swagger-ui.html

### Reproduction

For fresh project spring boot Java, (Gradle kotlin build),
Add swagger ui
```
    implementation(platform("org.springdoc:springdoc-openapi:2.6.0"))
    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui")
    implementation("org.springdoc:springdoc-openapi-starter-webflux-ui")
```
Add Hilla.
`/swagger-ui/index.html` will be out of reach.

### System Info

Mac, linux

**Comment by Artur-** [comment]
You can add `vaadin.excludeUrls=/swagger-ui/**` so ensure Vaadin/Hilla does not handle that URL

**Comment by Artur-** [comment]
See https://vaadin.com/docs/latest/flow/integrations/spring/configuration#prevent-handling-of-specific-urls

**Comment by platosha** [comment]
Closing as won't fix, looks like using `vaadin.excludeUrls` provides a good way for addressing this on the application end.
