### ISSUE TITLE
Set HttpOnly attribute for csrfToken cookie

### ISSUE THREAD

**Issue by gitgmihd** [vaadin/hilla#2820]
### Describe your motivation

As part of a penetration test for our application, we received a recommendation to set the **HttpOnly** and Secure attributes for the csrfToken cookie. After investigating how to implement these changes, we discovered that the relevant code is located in the **CsrfIndexHtmlRequestListener** class. However, we found that the **current implementation explicitly deactivates the csrfToken cookie's HttpOnly attribute** by calling csrfCookie.setHttpOnly(false) in the CsrfIndexHtmlRequestListener.ensureCsrfTokenCookieIsSet method.

### Describe the solution you'd like

Provide the possiblity to configure hilla in a way that the the **HttpOnly** attribute of the crsfToken cookie can be activated.

### Describe alternatives you've considered

I can only think of hacky altenatives

- configure a filter to modify the cookie of the reponse before sending it to the client (not sure whether that would even work)
- patch the responsible hilla classes

### Additional context

Is there a specific reason why you decided to set csrfCookie.setHttpOnly(false) ?

**Comment by Legioth** [comment]
This cookie is part of a double-cookie submit pattern. See e.g. https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html for a description of this. I would recommend that you have a discussion with your penetration testers to understand why they don't recognize this widely used pattern that is suggested (with some reservations) by a highly regarded security organisation like OWASP.

The cookie is supposed to be readable by JavaScript. Adding the httpOnly attribute would require disabling CSRF protection which would be an actual security issue.

**Comment by gitgmihd** [comment]
Thanks for the fast response and clarification.
