### ISSUE TITLE
@PositiveOrZero annotation should not make ts fields not-nullable

### ISSUE THREAD

**Issue by berndhopp** [vaadin/hilla#2826]
### Describe the bug

The javadoc of @PositiveOrZero says that "null elements are considered valid.". However, the client side validation will not accept null fields. 

<img width="154" alt="image" src="https://github.com/user-attachments/assets/c490349c-01dd-4a7a-aa68-53e5ea92c8a1">

### Expected-behavior

Null values are being accepted on the client-side for fields that are annotated with @PositiveOrZero

### Reproduction

Annotate a DTO-Field on the java side with @PositiveOrZero, then bind the client side representation of that field to an vaadin-integer-field in a form. Leave that field empty and call validate() on the binder. The empty value will not be accepted.

### System Info

Windows 11, Java 22, Chrome

**Comment by cromoteca** [comment]
What Java type are you using for that field? Can you post a code snippet? Non-nullability can be triggered by using primitive types or by using `@NonNullApi` annotation in the package.

**Comment by platosha** [comment]
Seems to be a bug in the form library.

**Comment by platosha** [comment]
Might be caused by using `NaN` for internal representation of empty number field state.

**Comment by berndhopp** [comment]
> What Java type are you using for that field? Non-nullability can be triggered by using primitive types or by using `@NonNullApi` annotation in the package.

For this case it was an Integer (boxed).
