### ISSUE TITLE
Date picker AutoCrud, AutoGrid  and AutoForm broken when the date is 31st of October

### ISSUE THREAD

**Issue by DuncanCasteleyn** [vaadin/hilla#2887]
### Description

No months can be used that only have 30 days on the 31 of October, setting the date of the computer to the 1st of November resolves the issue.

The time of existing items being edited also jumps back 2 hours.

Also reported this on the forum: https://vaadin.com/forum/t/autocrud-grid-form-date-time-picker-doesnt-allow-to-select-september-2024/167670/6

### Expected outcome

I get the date I selected.

### Minimal reproducible example

All 3 Auto doc pages contain a date time picker where the bug can be reproduced.

https://vaadin.com/docs/latest/components/auto-crud
https://vaadin.com/docs/latest/components/auto-grid
https://vaadin.com/docs/latest/components/auto-form

### Steps to reproduce

1. Set date of computer to 31 November 2024
2. Try to select a month with only 30 days
3. Result = another month

### Environment

Vaadin version(s): 24.5.2
OS: Windows

### Browsers

Chrome, Firefox, Edge

**Comment by DuncanCasteleyn** [comment]
Can somebody add the bug label to this issue?

**Comment by platosha** [comment]
Possibly already fixed by #2882

**Comment by DuncanCasteleyn** [comment]
I see this was not included in the latest released versions. When can we expect this to be released in a patch?
