### ISSUE TITLE
Flow auto layout not applied

### ISSUE THREAD

**Issue by mcollovati** [vaadin/hilla#2928]
### Describe the bug

In a Hilla react application, there's a view in a subfolder `flow`, that does not contain a Hilla `@layout.tsx`. The same application has a Flow layout class annotated with `@Layout("/flow")`.
When running the application both in dev and prod mode, the Flow layout is not applied to the Hilla view.

View config is defined as following:

```
export const config: ViewConfig = {
    menu: {
        title: "Hello React in Flow Layout",
    },
    title: "Hilla in Flow"
};
```

If I add to the configuration `flowLayout: true`, then the page is shown correctly.

The application works as expected with Hilla 24.6.0.beta1.
The issue could be related to the changes from #2915

### Expected-behavior

Flow auto layout is applied, when available for a view and there is no Hilla layout.

### Reproduction

Link to the platform PR whose validation fails because of this issue: https://github.com/vaadin/platform/pull/7051

Failing module: https://github.com/vaadin/platform/tree/main/vaadin-platform-react-hybrid-test

React View: https://github.com/vaadin/platform/blob/main/vaadin-platform-react-hybrid-test/src/main/frontend/views/flow/hello-hilla.tsx
Flow layout: https://github.com/vaadin/platform/blob/main/vaadin-platform-react-hybrid-test/src/main/java/com/vaadin/platform/react/test/views/FlowLayout.java

### System Info

Hilla: 24.6.0.beta2
Flow: 24.6.0.beta3

**Comment by ZheSun88** [comment]
fixed in #2934
