### ISSUE TITLE
Select.setValue(value)

### ISSUE THREAD

**Issue by Lars-jnk** [vaadin/hilla#2930]
### Describe your motivation

I want to set the value with TS. "select?.value = value" is not allowed. "select.setAttribute("value", value);" works only the first time. If you change the value via UI, another setAttribute has no effect.

### Describe the solution you'd like

"select.setValue(value)"
"select.reset()" to original value, would also be great

**Comment by Lars-jnk** [comment]
Of course the setValue would be called after the component is rendered.
If you have a select as class member, without query(), and you assign something to the value you get the "left hand exception". I found out you can do it without a class member like this "(document.getElementById('id') as Select).value = value!;" It looks ugly, but it works.

I guess I have to accept that JS/TS code looks ugly. I really thought/hoped they overcame that...

**Comment by TatuLund** [comment]
> document.getElementById('id')

This is just how TypeScript works. The above function return type is plain html element, hence if you need to use any Select specific API, you need to cast it like you do or you can use the type in the @query decorated field

https://github.com/TatuLund/hilla-demo/blob/hilla2/frontend/views/list/contact-form.ts#L41
