### ISSUE TITLE
login & logout causes page refresh

### ISSUE THREAD

**Issue by Lars-jnk** [vaadin/hilla#2947]
### Describe the bug

If I use login or logout the page is refreshed.

### Expected-behavior

No refresh like it was in 2.5.6

### Reproduction

use login/logout with 2.5.6 and 24.5.*

### System Info

  <properties>
    <java.version>17</java.version>
    <vaadin.version>24.5.2</vaadin.version>
  </properties>

**Comment by Legioth** [comment]
Refreshing the page is a security feature - it ensures that all JavaScript variables are initialized based on the new security context.

The actual logic that triggers the reloads are in the application code that is generated from e.g. start.vaadin.com. `login.tsx` has an explicit `document.location = path;` assignent that you can replace with some other logic if you want to opt out from the additional security. `@layout.tsx` correspondingly contains `document.location.reload();` in the logout button click handler that you can replace with your own logic if you want.

**Comment by Lars-jnk** [comment]
And thats it? You can't make a better solution then refresh the page?

**Comment by Legioth** [comment]
If you are certain that no part of the application's code keeps potentially sensitive data in e.g. caches or other module-scoped or global JS variables, then you can customize the provided logic to skip the refresh. We cannot assume that all application code will be safe in that regard which is why we have switched to using a more cautious approach by default.

**Comment by Lars-jnk** [comment]
Thanks for nothing...

**Comment by TatuLund** [comment]
See also: https://github.com/vaadin/hilla/issues/2235

**Comment by Lars-jnk** [comment]
I really don't wanna read more issies. It wastes my time.
If have important knowledge about how make a proper login/logout (with no refresh), user to doc. Or is that abandoned?
