### ISSUE TITLE
RouterLocation is missing after update ... again!

### ISSUE THREAD

**Issue by Lars-jnk** [vaadin/hilla#2948]
### Describe the bug

Why you still removing files/classes without the deprecation step? This is so unprofessionell!
And what is the docu saying? Nothing...

### Reproduction

update

### System Info

24.5.7

**Comment by platosha** [comment]
Hi, could you provide more information on the issue? Is this a Hilla Lit project? From which version was the upgrade?

**Comment by Lars-jnk** [comment]
24.5.2 and of course lit.

**Comment by platosha** [comment]
If not, I suspect the issue could be that the React library and dependencies were installed instead of the Lit ones. Please try if the explicit opt-out would help: https://vaadin.com/docs/latest/upgrading#opting-out-of-react

**Comment by Lars-jnk** [comment]
Idk, I don't wanna make that update again. To many errors...
Maybe the next larger version.
