### ISSUE TITLE
HMR not working when specify more than one export in file routing

### ISSUE THREAD

**Issue by inithink** [vaadin/hilla#2964]
### Describe the bug

![image](https://github.com/user-attachments/assets/90691009-264a-483a-88c8-1125c8b70be8)
[This document](https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-react#consistent-components-exports) specifies why the problem occurs.
Currently, Hilla need `export config` for [customizing routes](https://vaadin.com/docs/latest/hilla/guides/routing#customizing-routes).
But that disables HMR.

### Expected-behavior

change `<div>1</div>` -> `<div>2</div>` should change `1` to `2` whit out refreshing the page

### Reproduction

If I put the content in /src/main/frontend/views/test.tsx and change `<div>1</div>` -> `<div>2</div>`, HMR is not working.
```tsx
import { ViewConfig } from '@vaadin/hilla-file-router/types.js';

export default function IndexView() {
  return (
    <div>1</div>
  )
}
export const config: ViewConfig = {
  menu: {
    order: 2,
    icon: 'line-awesome/svg/globe-solid.svg',
  },
  title: 'test',
};
```

### System Info

Intel(R) Core(TM) i7-14700KF   3.40 GHz
Windows 11 Pro 24H2 26100.2314
Intellij with Jetbrain Runtime 17 + Vaadin Plugin

**Comment by Artur-** [comment]
Tested this. Works fine, so there must be something else involved

**Comment by inithink** [comment]
I just download new project from https://start.vaadin.com/ using options below
(with Hilla Empty page)
![image](https://github.com/user-attachments/assets/a46f08ff-ed7d-428f-9b99-2829434c50e4)
I commented dependencies below
```xml
<!--        <dependency>-->
<!--            <groupId>org.postgresql</groupId>-->
<!--            <artifactId>postgresql</artifactId>-->
<!--            <scope>runtime</scope>-->
<!--        </dependency>-->

<!--        <dependency>-->
<!--            <groupId>org.springframework.boot</groupId>-->
<!--            <artifactId>spring-boot-starter-data-jpa</artifactId>-->
<!--        </dependency>-->
```

Then I just start application, then change `<h2>This place intentionally left empty</h2>` to `<h2>This place intentionally left empty1</h2>` and HMR is not worked.
So I need to refresh the page.

What are the steps I need to take to find out about this problem?

**Comment by inithink** [comment]
I tested it in my my macbook.
It works well.
Is this windows specific problem?
