### ISSUE TITLE
Gradle plugin multiproject structure 

### ISSUE THREAD

**Issue by igieon** [vaadin/hilla#3008]
### Describe the bug

We have monorepo with several projects we want add hilla project as subrpoject so we have in  root ./gradlew file and then 1 subproject is hilla project. When i run build hilla project i get error:
```
Execution failed for task ':amg-fe:vaadinBuildFrontend'.
> com.vaadin.flow.server.ExecutionFailedException: Failed to configure Hilla engine: no runner succeeded. Set log level to debug to see more details.
```
And before i have error 
```
Caused by: java.io.IOException: Cannot run program "./gradlew" (in directory  of the hilla project)
```

### Expected-behavior

Able to build monorepor project when in root is gradlew in custom location and not in PATH

### Reproduction

Create multiproject that hilla is subproject and on root is ./gradlew 

### System Info

24.5.8

**Comment by platosha** [comment]
Hi, the ongoing effort in #2616 will remove this run altogether. Expected to be part of the 24.7 feature release.

Meanwhile, would it help to symlink or install Gradle wrapper in the Hilla subproject directory?

**Comment by mcollovati** [comment]
Setting `hilla.gradleExecutable` system property could also help
