### ISSUE TITLE
v24.6 does not produce Typescript ENUM

### ISSUE THREAD

**Issue by Pascalmh** [vaadin/hilla#3045]
### Describe the bug

Using an external Model doesn't produce correct Typescript code anymore (upgrading form `24.5.8` to `24.6.0`).

This Code:

```java
// BillingAccountInfo.java
import lombok.*;
import com.acme.api.model.PaymentMethod; // <-- importing an external Model (ENUM)

@Setter
@Getter
@AllArgsConstructor
@Builder
public class BillingAccountInfo {
    private String billingAccountId;
    private PaymentMethod paymentMethod;  // <-- using the external Modal here
    private String partyName;
    private VerifiedAddress address;
}
```

used to produce this file:

```ts
// src/main/frontend/generated/…/model/BillingAccountInfo.ts
import type PaymentMethod_1 from "../../api/model/PaymentMethod.js";
import type VerifiedAddress_1 from "./VerifiedAddress.js";
interface BillingAccountInfo {
    billingAccountId: string;
    paymentMethod: PaymentMethod_1; // <-- here it is
    partyName: string;
    address: VerifiedAddress_1;
}
export default BillingAccountInfo;
```

and also this file:
```ts
// src/main/frontend/generated/…/api/model/PaymentMethod.ts
enum PaymentMethod {
    DIRECT_DEBIT = "DIRECT_DEBIT",
    MANUAL = "MANUAL",
    MANUAL_FEE = "MANUAL_FEE"
}
export default PaymentMethod;
```

after Updating to `24.6.0` the PaymentMethod.ts file is missing and inside the `BillingAccountInfo.ts` the `paymentMethod` is now of type `string`

### Expected-behavior

ENUM is created in generated Typescript folder 

### Reproduction

Import an external Modal into an Java Modal, build/run the app, try using it in typescript code/finding it in the generated folder.

### System Info

Vaadin 24.6

**Comment by cromoteca** [comment]
I cannot replicate the issue in a simple project, even using Lombok. What do you mean by external model? Does it come from a dependency?

**Comment by Pascalmh** [comment]
@cromoteca yes it comes from a dependency

**Comment by Pascalmh** [comment]
@cromoteca here's an example ENUM that should reproduce the issue:

```java
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum Foo {
    X("X"),
    Y("Y"),
    Z("Z");

    private String value;

    private Foo(String value) {
        this.value = value;
    }

    @JsonValue
    public String getValue() {
        return this.value;
    }

    public String toString() {
        return String.valueOf(this.value);
    }

    @JsonCreator
    public static Foo fromValue(String value) {
        for(Foo b : values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }

        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
}
```

**Comment by cromoteca** [comment]
This `enum` uses `JsonValue/JsonCreator`, so the cause of the regression is probably not in being an external dependency, but in https://github.com/vaadin/hilla/pull/3006, which has been cherry-picked to `24.6`.

**Comment by cromoteca** [comment]
Although that sounds like a fix to me, not a bug. As described in https://github.com/vaadin/hilla/issues/2055, when a class uses `JsonValue` and `JsonCreator`, Hilla should not generate that class and replace it with the type of the annotated accessors. Doing the same with `enum`s seems the right thing to me. @Pascalmh what do you think?

**Comment by Pascalmh** [comment]
By transforming the ENUM to a `string` in the typescript interface we're loosing a lot of valuable information.

Here's what I do with the ENUM in the frontend:

```ts
function getFooLabel(foo: Foo) {
  switch (foo) {
	case Foo.X:
		return "One thing";
	case Foo.Y:
		return "Another thing";
	case Foo.Z:
		return "Yet another thing";
	}
}
```

with `"noFallthroughCasesInSwitch": true,` set the above code would error in the IDE if the ENUM was extended or an enumeral was removed - loosing the ENUM in TypeScript doesn't make this type safetry possible anymore

**Comment by cromoteca** [comment]
The use case is not clear to me: what's the purpose of using those annotations if the enum is to be used as is?

**Comment by Pascalmh** [comment]
Fair and good point - I discussed this (again) with my colleague - you're right it's a fix, not a bug!
