### ISSUE TITLE
embedding Flow components into TypeScript views does not work

### ISSUE THREAD

**Issue by vlukashov** [vaadin/hilla#320]
If I follow the [Creating an Embedded Vaadin Application Tutorial](https://vaadin.com/docs/v15/flow/embedding-flow-applications/tutorial-webcomponent-exporter.html) in order to embed a server-side Vaadin component into a TypeScript Vaadin view, my application does not work as expected:
 - the tutorial tells me that I need to include the `webcomponents-loader` script and gives code snippets how to do that. These code snippets do not work. Moreover, the entire step of loading WebComponents polyfils is not needed because all browsers supported by Vaadin 15+ do support Web Components natively.
 - If I skip the WC polyfils (or if I manage to find my way to load them), embedding still fails with a `Uncaught TypeError: window.Vaadin.Flow.initApplication is not a function` error:
![image](https://user-images.githubusercontent.com/22416150/79981335-2ef15d00-84ad-11ea-8e57-167846d74982.png)

ServerCounter.java:
```java
public class ServerCounter extends Div {

    public ServerCounter() {
        add(new Label("Server-side counter"));
    }

    public static class Exporter extends WebComponentExporter<ServerCounter> {
        public Exporter() {
            super("server-counter");
        }

        @Override
        protected void configureInstance(
                WebComponent<ServerCounter> webComponent,
                ServerCounter counter) {
        }
    }
}
```

index.html:
```html
<script type="module" src="web-component/server-counter.js"></script>
```

main-layout.ts:
```ts
render() {
  return html`
      <server-counter></server-counter>
      <slot></slot>
  `;
}
```

**Comment by Legioth** [comment]
Proper embedding support has been implemented and documented for Vaadin 24.4
