### ISSUE TITLE
Mockito in flow does not support mocking final classes

### ISSUE THREAD

**Issue by manolo** [vaadin/hilla#352]
When moving classes and their tests from `connect` to `flow` it was necessary to ignore certain tests that depend on the mockito plugin for final classes.

We can upgrade flow to use the `org.mockito.plugins.MockMaker` pluggin in `mockito-core-2.23.0`, but it breaks tests in master flow as it's shown in the TC build :  https://teamcity.vaadin.com/viewType.html?buildTypeId=Flow_FlowTests&branch_Flow=6672

**Comment by platosha** [comment]
Closing in favour of #208
