### ISSUE TITLE
Devmode popup shows Hilla 1.0 as Vaadin 1.0

### ISSUE THREAD

**Issue by samie** [vaadin/hilla#356]
When running an Hilla application in devmode the following environment information is presented in popup: 

```
Vaadin: 1.0.0
Flow: 23.0.0
```
Instead the versions should show something like:
```

Hilla: 1.0.0
Flow: 23.0.0
```

**Comment by cromoteca** [comment]
At the moment the `Vaadin` name is hardcoded in [VaadinDevmodeGizmo](https://github.com/vaadin/flow/blob/05994fd3c2ec543da7ba2a62879c9c223d0b7589/flow-client/src/main/frontend/VaadinDevmodeGizmo.ts#L1459). Maybe the product name could be added to `serverInfo`, but the impact should be reconsidered.
