### ISSUE TITLE
@Nonnull with full qualified type names throws compiler error

### ISSUE THREAD

**Issue by Feuerwerk** [vaadin/hilla#360]
### Description of the bug 
If you annote a parameter having a fully qualified typename in an endpoint method with @Nonnull it will trigger the java compiler error _scoping construct cannot be annotated with type-use annotation: @dev.hilla.Nonnull_

### Minimal reproducible example
```
package a.b.c;
public class TransferObj {
}
```

```
package a.b.endpoints;
import dev.hilla.Nonnull;

@Endpoint
public class TestEndpoint {
    public void test(@Nonnull a.b.c.TransferObj obj) {
    }
}
```

### Versions:
    - Hilla version: 1.0.1
    - Java version: 17.0.2
    - OS version: macOS 11.6.2

**Comment by Artur-** [comment]
See https://stackoverflow.com/a/21385939/3336733

**Comment by Artur-** [comment]
So `public void test( java.lang.@Nonnull String obj) {` compiles OK. 

What do we learn here? Do not use fully qualified names, it seems...

**Comment by Feuerwerk** [comment]
Wow, didn't know about that, that looks ugly :-/
