### ISSUE TITLE
Move hilla, hilla-bom, hilla-maven-plugin, hilla-spring-boot-starter platform artifacts to the Hilla repository

### ISSUE THREAD

**Issue by platosha** [vaadin/hilla#373]
Some of the Hilla related artifacts are currently maintained and released in the platform repository, namely:

- hilla
- hilla-bom
- hilla-maven-plugin
- hilla-spring-boot-starter

Let us move them to the Hilla repository to simplify maintenance and release process.

**Comment by olaf-2** [comment]
Until then it would be good to haven them on Maven Central. The hilla-maven-plugin 2.0.6 and 2.0.7 are not there: https://repo.maven.apache.org/maven2/dev/hilla/hilla-maven-plugin/
