### ISSUE TITLE
Add feature flag for multi-module generator

### ISSUE THREAD

**Issue by platosha** [vaadin/hilla#384]
The multi-module generator is fairly new, and could have yet unknown bugs. It would be safer to introduce the new multi-module generator gradually:

- First release adds multi-module generator behind a feature flag
- The next release: enable by default, opt-out to use the old (generator) generator is optional
- The next major release after that could remove the old generator.

DoD:

- Add a feature flag for Hilla multi-module generator
- Switch between the new `TaskGenerateHilla` and the old `TaskGenerateOpenAPI`/`TaskGenerateEndpoint` based on the feature flag value.

**Comment by Lodin** [comment]
Just got a thought that feature flag might be redundant because the user already have an ability to disable the multi-module generator by removing the maven plugin for it. Since the `TaskGenerateHilla` is available because of this plugin, the old generator will be used instead.
