### ISSUE TITLE
Add helper to tie a subscription to a context, typically a view

### ISSUE THREAD

**Issue by Artur-** [vaadin/hilla#400]
**Is your feature request related to a problem? Please describe.**
Some endpoint subscriptions are opened when the application starts and not closed until the application is closed. For these it is fine to just subscribe in e.g. index.ts and never unsubscribe. Other subscriptions are tied to a certain component being visible, often a view. If you have a monitoring view with graphs, you want to subscribe to updates while the view is visible but when the view is no longer shown, you are no longer interested in the updates. It is super easy to forget to unsubscribe and then the browser will receive more and more irrelevant events when you navigate through the application.

**Describe the solution you'd like**
The helper functionality describe in the original issue (#56) should be implemented so you can tie the subscription to a `ReactiveElement` and have the subscription cancelled when the reactive element is disconnected. A clearer API than the one described in the issue (an additional parameter to the flux method) would be to add
```
context(context: ReactiveElement);
```

to `Subscription` so you can do e.g.
```
TemperatureEndpoint.monitor("kitchen").context(this).onNext(value => {
  // Add value to graph
};
```

**Describe alternatives you've considered**
The API described in the original issue is 
```
TemperatureEndpoint.monitor("kitchen", this).onNext(value => {
```

which is a bit more concise but it mixes method parameters with the context and is not as clear

**Comment by platosha** [comment]
Should probably use lit’s Reactive Controllers here to hook into the view’s connected / disconnected lifecycle.
