### ISSUE TITLE
Support polymorphic return types through @JsonSubTypes

### ISSUE THREAD

**Issue by Artur-** [vaadin/hilla#438]
When sending different types of events to the client, I want to be able to use one Flux endpoint method for all different types of events as they are happening in a logical order that I want to preserve. On the client side I want to be able to differentiate between the event types and handle them separately.

**Describe the solution you'd like**

Ideally I would want to define my endpoint method to return an abstract type, e.g.
```
public Flux<AbstractEvent> subscribe() { ... }
```
and nothing else. This does not seem realistic as Hilla then would need to find out all possible subtypes of `AbstractEvent`. While it can work for a limited case it would not work very well if returning `Flux<Object>`. Also with only this there is no information available on the client side about which type of event was actually sent, unless the event instance manually include that data.

Jackson supports `@JsonSubTypes` which should help here for both of the problems. If I annotate my `AbstractEvent` as
```
    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY)
    @JsonSubTypes({
            @JsonSubTypes.Type(value = AddEvent.class, name = "add"),
            @JsonSubTypes.Type(value = UpdateEvent.class, name = "update"),
            @JsonSubTypes.Type(value = DeleteEvent.class, name = "delete") })
```
then 
1. Hilla should generate TS for all the mentioned sub types: `AddEvent`, `UpdateEvent`, `DeleteEvent`
2. Jackson will add the `@type` property (because of use=`NAME`) when serializing so you can distinguish the event types on the client side
3. Hilla should include the `@type` property in the generated TS to make it easy to access

**Comment by samie** [comment]
Do you have TS example? Or how would the TS usage look like for `AbstractEvent`?

**Comment by cromoteca** [comment]
Before thinking about an implementation, some investigation about serialization in reactive endpoints is needed. Consider this endpoint:

```java
@Endpoint
@AnonymousAllowed
public class SubtypesEndpoint {
  public Flux<@Nonnull AbstractEvent> subscribe() {
    return Flux.just(new AddEvent(), new UpdateEvent(), new DeleteEvent());
  }

  public @Nonnull AbstractEvent single() {
    return new AddEvent();
  }

  @JsonTypeInfo(use = JsonTypeInfo.Id.MINIMAL_CLASS)
  public static class AbstractEvent {
    public String name;
  }

  public static class AddEvent extends AbstractEvent {
    public String item;
  }

  public static class UpdateEvent extends AbstractEvent {
    public String oldItem;
    public String newItem;
  }

  public static class DeleteEvent extends AbstractEvent {
    public String item;
    public boolean force;
  }
}
```

If I call the `single` method, I get this JSON: `{"@c":".SubtypesEndpoint$AddEvent","name":null,"item":null}`.

If I call the `subscribe` method, I get:

![image](https://user-images.githubusercontent.com/498086/232292977-5a835a2e-bb08-454f-86ec-c6bdccac02c9.png)

So I guess that the serialization works differently there, as the `@c` parameter is not added to JSON.

Using a more verbose type description as in your example doesn't change the outcome.
