### ISSUE TITLE
Support for Flux<T> and EndpointSubscription<T> in the multi-module engine

### ISSUE THREAD

**Issue by platosha** [vaadin/hilla#447]
The multi-module generator does not support handling Push endpoints.

The old generator's parser supports those by mapping `Flux<T>` and `EndpointSubscription<T>` to a customized `ArraySchema` type.

The old TypeScript generator emits `client.subscribe()` instead of regular `client.call()` for those, and the return type is declared as `Subscription<T>`.

**Comment by cromoteca** [comment]
The current implementation adds a flag to the OpenAPI definition to identify push-related endpoint methods. Given that this flag is added when the return type is `Flux` or `EndpointSubscription`, it should be possible to make the necessary changes in the TypeScript generator without that flag or any other hack.

@Lodin what's your advice about this transformation? Where should that happen?

**Comment by cromoteca** [comment]
Blocked by #458
