### ISSUE TITLE
Unexpected behaviour with javax @Digits constraint in hilla

### ISSUE THREAD

**Issue by SilvanJost** [vaadin/hilla#514]
### Description of the bug 

I want to limit integer&fraction positions of a Double value in my hilla/vaadin application by setting the  javax.validation.constraints.Digits annotation on the appropriate java model property.

`@Digits(integer = 3, fraction = 1)`

The autogenerated typescript model receives the same annotation 

`new Digits({integer:3, fraction:1})`

The java validation treats these values as maximums. so i can have 0-3 integer positions in my Double.
The generated frontend validation treats these values as strict values. So only numbers with exactly 3 integer positions will pass validation.

![Uploading Screenshot 2022-08-17 173849.png…]()

I tested this by first submitting the form with a number that has 3 exact integer positions. Then copied and sent the same request from postman with a number that has 2 integer positions and it worked like a charm. Meanwhile the frontend would've not let me submit the form with the same number

### Expected behavior

The frontend validation should behave the same way as the backend validation does

### Versions:
    - Hilla version: Hilla 1.1.6
    - Node version: v14.18.1
    - Java version: 11

**Comment by simasch** [comment]
Same as #513

**Comment by platosha** [comment]
Fixed in #515
