### ISSUE TITLE
Socket.io with Servlet 5

### ISSUE THREAD

**Issue by mcollovati** [vaadin/hilla#531]
`fusion-endpoint` depends on `socket.io-server` to provide PUSH feature, but it seems that the transitive dependency `engine.io-server` does not yet have support for Servlet 5.

**Comment by mshabarov** [comment]
We are going to try replacing socket.io with WebFlux for Push soon within Servlet 5 migration scope.

**Comment by Artur-** [comment]
What do you mean by WebFlux here? What is used in the browser?

**Comment by mshabarov** [comment]
Covered by https://github.com/vaadin/hilla/pull/597
