### ISSUE TITLE
Add HTTP response code to EndpointError

### ISSUE THREAD

**Issue by pm-finamis** [vaadin/hilla#537]
**Is your feature request related to a problem? Please describe.**
I would like to detect 401 Unauthorized when EndpointError occurs.

**Describe the solution you'd like**
Add HTTP response code to EndpointError.

**Describe alternatives you've considered**
Now I check if error.message === "expected \"200 OK\" response, but got 401 ", which does not seem very clean.

**Additional context**

Thanks!

**Comment by Artur-** [comment]
Is the use case that you want to know if the current user did not have access to the endpoint so that you can ask him/her to login first? Or something else?

**Comment by pm-finamis** [comment]
I want to inform the user that his authentication expired.

**Comment by platosha** [comment]
After discussing in the team, we realised that:
- Throwing `EndpointError` in this case is a bug, we should actually throw `EndpointResponseError` instead
- `EndpointResponseError` should include a `code` getter
- We should introduce a common error superclass for all errors thrown in the client
- For the purpose of handling convenience we could additionally introduce more `EndpointResponseError` subclasses, including something like `UnauthorizedResponseError` for the 401 response
- Naming suggestions for better consistency are welcome
