### ISSUE TITLE
Support for unicode client side @Pattern validations

### ISSUE THREAD

**Issue by pm-finamis** [vaadin/hilla#539]
**Is your feature request related to a problem? Please describe.**
We use @Pattern validations on form fields with national characters (e.g "Čučoriedka").
@Pattern(regexp = "^[\\p{L}\\s-]+$")
private String firstName;
Client side validators are created without 'u' flag and always fail the validation.

**Describe the solution you'd like**
Add the 'u' flag or add an option to add the 'u' flag to the client side Pattern validator.

**Describe alternatives you've considered**
Modify the validator manually affter binder has been created
let validators = this.binder.for(this.binder.model.firstName).validators;
validators.forEach(v => {
            if (v instanceof Pattern) {
                v.regexp = new RegExp(v.regexp, 'u')
            }
});

**Additional context**
[a-zA-Z] works only for ASCII
[\uXXXX-\uXXXX] do not work without the 'u' flag either

**Comment by platosha** [comment]
Looks like a bug to me, does not work as expected.
