### ISSUE TITLE
Conflict version of swagger-core on springdoc-openapi-ui

### ISSUE THREAD

**Issue by letrthang** [vaadin/hilla#551]
### Versions:
    - Vaadin / Hilla version: 23.2.1/ 1.2.1
    - Java version:1 7
   
If project config to use hybrid mode which is both Vaadin flow and Hilla. To enable swagger UI, we add 

```
<dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>1.6.11</version>
        </dependency>
```
And will get exception:

```
java.lang.NoSuchMethodError: 'io.swagger.v3.oas.models.media.ComposedSchema io.swagger.v3.oas.models.media.ComposedSchema.addAllOfItem(io.swagger.v3.oas.models.media.Schema)'
	at dev.hilla.generator.OpenAPIObjectGenerator.lambda$parseNonEndpointClassAsSchema$24(OpenAPIObjectGenerator.java:524) ~[endpoint-1.2.1.jar:na]
```

**Root cause:**
springdoc-openapi-ui uses **swagger-core** and **swagger-models** which Hilla also uses. This one causes version conflicting. So, swagger does not work.

The workaround is to exclude **swagger-core** and **swagger-models** from springdoc-openapi-ui. 
However this solution also has potential issue when springdoc-openapi-ui needs to use newer version of **swagger-core** and **swagger-models** .

```
<properties>
        <java.version>17</java.version>
        <vaadin.version>23.2.1</vaadin.version>
        <hilla.version>1.2.1</hilla.version>
    </properties>
<dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>1.6.7</version>
            <!-- avoid conflict with hilla. Note: change springdoc-openapi-ui version to 1.6.11 will not work -->
           <exclusions>
                <exclusion>
                    <groupId>io.swagger.core.v3</groupId>
                    <artifactId>swagger-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.swagger.core.v3</groupId>
                    <artifactId>swagger-models</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

so i would suggest to add _springdoc-openapi-ui_ as default lib in parent POM of Vaadin and Hilla needs not indicate version for **swagger-core** and **swagger-models**.

More details, can try to run vaadin demo project below:
https://github.com/letrthang/vaadin23-flow-pro-components.git

In above demo project, in POM to change _springdoc-openapi-ui_ version to **1.6.11** and will see the swagger UI not working.

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/13396193/190432207-690721a5-5f45-4c8b-83e2-21a9edf32b02.png">

Any better solution ?

**Comment by platosha** [comment]
Hi, thanks for submitting and for the workaround. Unfortunately, it’s not currently possible to upgrade swagger dependencies for us because of https://github.com/vaadin/hilla/issues/462

Let me close this for now. We could reconsider this once swagger has a fix for https://github.com/swagger-api/swagger-codegen-generators/issues/956
