### ISSUE TITLE
v21.0.0.alpha10 seems to choke on vargargs in Endpoints

### ISSUE THREAD

**Issue by markhm** [vaadin/hilla#57]
### Description of the bug 
v21.0.0.alpha10 seems to choke on vargargs in Endpoints.

### Minimal reproducible example
See https://github.com/markhm/varargs-example and herein `com.example.application.data.endpoint.UserEndpoint` line 24.

### Expected behavior
Frontend classes should correctly be generated.

### Actual behavior
Client-side message:
<img width="1361" alt="Screenshot 2021-07-26 at 19 08 10" src="https://user-images.githubusercontent.com/1430451/127031664-a1fd277d-42d6-4c32-bc3b-4e222276ceab.png">

Server-side message:

<img width="1176" alt="Screenshot 2021-07-26 at 19 21 14" src="https://user-images.githubusercontent.com/1430451/127031753-becc342f-04f5-46ce-b2b1-fa337f352822.png">

### Versions:
    - Vaadin / Fusion version: 21.0.0.alpha10
    - Node version: v16.5.0
    - Java version: openjdk version "16" 2021-03-16
    - OS version: macOS latest stable Big Sur 11.4 (20F71)

**Comment by Lodin** [comment]
Hi @markhm, thanks for the issue. We need to do some investigation on it. As a workaround, for now, you can use collections like array or `List`.

**Comment by platosha** [comment]
Closing, will be fixed as part of #733
