### ISSUE TITLE
Cannot run a project containing endpoints without parameter names in class files

### ISSUE THREAD

**Issue by cromoteca** [vaadin/hilla#571]
When the project containing the endpoints is compiled without the `parameters` flag, ClassGraph always returns `null` as parameter name, whereas Java reflection generates `argN` placeholder names.

While it is recommended to add the compiler flag for readability, its absence should not break the application: we should generate the missing parameter names.

**Comment by Legioth** [comment]
Even better would be to extract parameter names from JavaDocs in case it's not in the class files, but that's a separate step in addition to just making sure it still somehow works even without.
