### ISSUE TITLE
Endpoint return type with generics does not generate right type

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/hilla#579]
### Description of the bug 
My endpoint returns a data type with generics. The generated type is `any` instead of the actual type. 

### Minimal reproducible example

```java
static class PageResponse<T> {
  @Nonnull
  public List<@Nonnull T> content;
  @Nonnull
  public long size;

  PageResponse(List<T> content, long size) {
    this.content = content;
    this.size = size;
  }
}

public PageResponse<Person> getPage(int page, int size) {
  var dbPage = repo.findAll(PageRequest.of(page, size));

  return new PageResponse<Person>(dbPage.getContent(), dbPage.getTotalElements());
}
```

### Expected behavior
I would expect the content array to be of type `Array<Person>`

### Actual behavior
The array is of type `Array<any>`

### Versions:
    - Vaadin / Hilla version: 1.2.3
    - Node version: 18.8
    - Java version: 17
    - OS version: MacOS 13.0

**Comment by marcushellberg** [comment]
Note. This used to work in earlier versions. I ran into this when updating an old project from Vaadin 20.

**Comment by platosha** [comment]
Honestly I don’t remember that this was ever supported, but anyway let us support it.

**Comment by marcushellberg** [comment]
It may have worked accidentally. But somehow it did in a video I did https://www.youtube.com/watch?v=qpWrIn5xuAE

**Comment by platosha** [comment]
Looking more into that, I found that parsing / generating generic entities was never supported. Let me mark this as a feature request, not a bug.

**Comment by tarekoraby** [comment]
Maybe Hilla can support generics return type by requiring developers to add a public `Class<T> getClassType()` to their class.

``` 
public class GenericClass<T> {

     private final Class<T> type;

     public GenericClass(Class<T> type) {
          this.type = type;
     }

     public Class<T> getClassType() {
         return this.type;
     }
}
```

**Comment by Feuerwerk** [comment]
@tarekoraby That would mean that you can‘t use generics you don‘t have access to the sourcecode like org.springframework.data.domain.Page

**Comment by platosha** [comment]
Note: generic endpoint methods, such as below, should be explicitly not supported:

```java
public <T> DbEntity<T> savePerson(T pageItem) {
  //...
}
```
