### ISSUE TITLE
hillaEngine: Primitive types needs @Nonnull

### ISSUE THREAD

**Issue by sveine** [vaadin/hilla#581]
### Minimal reproducible example
```
    public void getIdForPrimitive(long id) {
    }
```
![image](https://user-images.githubusercontent.com/367125/194523621-041e42cc-53ea-4d48-aeac-4a2a2cdfd76d.png)

### Expected behavior
```
async function getIdForPrimitive_1(id: number, init?: EndpointRequestInit_1): Promise<void>
```
### Actual behavior
```
async function getIdForPrimitive_1(id: number | undefined, init?: EndpointRequestInit_1): Promise<void>
```
### Versions:
Hilla: 23.2.3
Flow: 23.2.3
Java: JetBrains s.r.o. 17.0.2
OS: amd64 Windows 10 10.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Live reload: Java active (HotswapAgent): Front end active

**Comment by cromoteca** [comment]
Will be fixed in 1.2.7.
