### ISSUE TITLE
Version 1.3 alpha is broken due to Flow changes (`DEFAULT_FLOW_RESOURCES_FOLDER`)

### ISSUE THREAD

**Issue by cromoteca** [vaadin/hilla#638]
`DEFAULT_FLOW_RESOURCES_FOLDER` is no longer available and must be replaced. This affects Flow 23.3 and so Hilla 1.3.

**Comment by cromoteca** [comment]
Commit https://github.com/vaadin/hilla/commit/de852bfe04947a48e1dd595a656b7b0faea3be1c must be cherry-picked.

**Comment by platosha** [comment]
Fixed in https://github.com/vaadin/hilla/commit/a8d43e3a51a8a87d9aeeec1bbf2e022f322c316f
