### ISSUE TITLE
PiT 23.3: cannot find reference documentation about the NonNullApi

### ISSUE THREAD

**Issue by manolo** [vaadin/hilla#641]
go to https://hilla.dev/docs/ and search for `NonNullApi`

**Comment by cromoteca** [comment]
https://hilla.dev/docs/advanced/endpoints-generator/#type-nullability

Also, nullability criteria should be reviewed for multi-module generator. For example, custom annotations must now be declared in `pom.xml`, they are not picked up automatically just by having `nonnull` in their name.

**Comment by manolo** [comment]
ping @cromoteca @platosha
