### ISSUE TITLE
EndpointExposed annotation name is not initialized

### ISSUE THREAD

**Issue by cromoteca** [vaadin/hilla#649]
### Description of the bug 

When `EndpointExposedPlugin` is used, it fails at https://github.com/vaadin/hilla/blob/e78446c61c0b84677c50fe79fe4bfaeeb2962703/packages/java/parser-jvm-plugin-backbone/src/main/java/dev/hilla/parser/plugins/backbone/EndpointExposedPlugin.java#L163 because the annotation name is not initialized in the parser: https://github.com/vaadin/hilla/blob/e78446c61c0b84677c50fe79fe4bfaeeb2962703/packages/java/maven-plugin/src/main/java/dev/hilla/maven/ParserProcessor.java#L89-L90

### Versions:
    - Hilla version: 1.2.8

Reported by @sveine in #604

**Comment by sveine** [comment]
I think you know, but I am using @Endpoint (not @EndpointExposed)

**Comment by cromoteca** [comment]
Sure, but the code I highlighted still wants to run `::equals` on a `null` object.
