### ISSUE TITLE
PiT 23.3: BinderNode.ts is using the createEmptyValue  undefined method

### ISSUE THREAD

**Issue by manolo** [vaadin/hilla#655]
### Description of the bug 
When running Hilla apps using binder generated in start, views using binder do not work.
There is an error in console.
```
BinderNode.ts:385 Uncaught TypeError: this.model.constructor.createEmptyValue is not a function
    at Binder.initializeValue (BinderNode.ts:385:98)
    at new BinderNode (BinderNode.ts:64:10)
    at new Binder (Binder.ts:72:5)
    at <instance_members_initializer> (master-detail-sample-book-typescript-view.ts:43:20)
    at new MasterDetailSampleBookTypescriptView (master-detail-sample-book-typescript-view.ts:34:8)
    at Object.component (router.js:255:34)
    at router.js:295:27

```
### Minimal reproducible example
- Generate, update version, and run the app in dev-mode
```
curl -s -f 'https://start.vaadin.com/dl?&preset=latest-typescript&projectName=latest-typescript' -o latest-typescript.zip
unzip latest-typescript.zip 
cd latest-typescript
mvn -B -q versions:set-property -Dproperty=hilla.version -DnewVersion=1.3.0.alpha2
mvn
```
- Open dev-tools console in chrome
- Go to the view http://localhost:8080/master-detail-view
- There is an error in console

### Expected behavior
View works
### Actual behavior
Blank view
### Versions:
    - Vaadin / Hilla version: 1.3.0.alpha2

**Comment by ZheSun88** [comment]
seems there is a mismatch in version.. 

![image](https://user-images.githubusercontent.com/31067185/202708904-542be247-d9a6-4788-89b1-28cdd478710a.png)

**Comment by manolo** [comment]
The error is also in production mode, so probably unrelated with the `@vaadin/bundle` 

```
rm -rf target node_modules
mvn clean package -Pproduction
java -jar target/*jar
```
