### ISSUE TITLE
PiT 23.3: JS error when running Hilla master-detail

### ISSUE THREAD

**Issue by manolo** [vaadin/hilla#673]
### Description of the bug 
Any view having master-detail fails with hilla 1.3.0.alpha3
```
Error: The following properties on element master-detail-typescript-view will not trigger updates as expected because they are set using class fields: gridSize. Native class fields and some compiled output will overwrite accessors used for detecting changes. See https://lit.dev/msg/class-field-shadowing for more information.
    at MasterDetailTypescriptView.performUpdate (...)
    at MasterDetailTypescriptView.scheduleUpdate (...)
    at MasterDetailTypescriptView.__enqueueUpdate (...)
```
### Minimal reproducible example
- Download a hilla start project having master detail and bump version to 1.3.0.alpha3, and run in dev-mode
```
curl -s -f 'https://start.vaadin.com/dl?&preset=latest-typescript&projectName=latest-typescript' -o latest-typescript.zip
unzip latest-typescript.zip
cd latest-typescript
mvn -B -q versions:set-property -Dproperty=hilla.version -DnewVersion=1.3.0.alpha3
mvn
```
- Open the browser and go to a master-detail view
- There is an error in console

### Expected behavior
Master Detail is displayed
### Actual behavior
Blank Screen
### Versions:
    - Vaadin / Hilla version: 23.3.0.alpha3 / 1.3.0.alpha3

**Comment by Artur-** [comment]
The skeleton starter tsconfig.json has not been updated

**Comment by manolo** [comment]
Removing the `tsconfig.json` does not help, and the error visiting master detail is the same regarding `gridSize`

```
element master-detail-typescript-view will not trigger updates as expected because they are set using class fields: gridSize. 
Native class fields and some compiled output will overwrite accessors used for detecting changes.
See https://lit.dev/msg/class-field-shadowing for more information.
```

**Comment by manolo** [comment]
wait it works, it seems something else in our PiT scripts, sorry for the noise
