### ISSUE TITLE
Support for Multi Module Projects with Maven

### ISSUE THREAD

**Issue by egloffmark** [vaadin/hilla#765]
I like to have for my Hilla Projects different modules, so for instance different endpoints and webcomponents can be put into modules and can be re-used. Not sure how this can be achieved with Vaadin or Hilla i.e. if today modules of a bigger Maven project would be automatcially scanned and its frontend generated at the main level.This may require changes at the Hilla or Vaadin Maven Plugin. 

**High Level Requirements / Suggestions**
- Enpoints can be consideref from different submodules
- Views and Webcomponents can be reused from  from different submodules
- Themes and Styles can be reused from  from different submodules

**Comment by marcushellberg** [comment]
In Hilla 1.x you need to enable the `hillaEngine` feature flag for multi-module support. It will be enabled by default in 2.0. See https://hilla.dev/docs/lit/reference/configuration/#java-compiler-options

**Comment by platosha** [comment]
Thanks for asking. This is partially (the endpoints part) implemented in 2.0.

Regarding sharing the frontend code using Maven, for now it’s out of our scope. Existing npm tooling should help here, as of today you could already share things (views, styles) as npm packages.

If you're looking for having a “multi-module” kind of repository structure, I would suggest to consider using [npm workspaces](https://docs.npmjs.com/cli/v9/using-npm/workspaces).
