### ISSUE TITLE
Hilla+React project does not update frontend dependencies on version update

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/hilla#772]
When updating a project with the `hilla-react` dependency from 1.3.x to 2.0, the build breaks because of mismatched frontend dependency versions. 

Expected outcome:
Hilla would update the versions of the necessary dependencies.

**Comment by platosha** [comment]
Note: probably missing `@vite/plugin-react` in the `hilla-react` platform artifact is the main culprit here.

**Comment by cromoteca** [comment]
Yes, `@vitejs/plugin-react` should be updated to `~3.0.1` in `package.json`. If I recall, we cannot use `@NpmPackage` to declare a `devDependency`.

**Comment by cromoteca** [comment]
It is now part of the [upgrading guide](https://hilla.dev/docs/react/guides/upgrading/#vite-plugin-for-react), so closing.
