### ISSUE TITLE
Unable to find auto installed node

### ISSUE THREAD

**Issue by Artur-** [vaadin/hilla#778]
### Description of the bug 
Running the build without a global node installed (tested inside Docker) results in

```
#13 51.27 [INFO] Running `npm install` to resolve and optionally download frontend dependencies. This may take a moment, please stand by...
#13 51.58 [INFO] using '/home/myuser/.vaadin/node/node /home/myuser/.vaadin/node/lib/node_modules/npm/bin/npm-cli.js --no-update-notifier --no-audit --scripts-prepend-node-path=true --ignore-scripts install' for frontend package installation
#13 82.47 [INFO] Frontend dependencies resolved successfully.
#13 83.06 [INFO] Hilla engine configuration not found: configure using build system plugin
#13 85.23 [INFO] JVM Parser started
#13 86.79 [INFO] JVM Parser finished successfully
#13 86.80 /usr/bin/env: 'node': No such file or directory
```

### Minimal reproducible example
`mvn install -Pproduction` without a global Node installation

### Expected behavior
It builds using the existing logic for finding the node installation

### Actual behavior
It thinks `node` is always in PATH and fails

### Versions:
    - Vaadin / Hilla version: 2 beta 3

**Comment by cromoteca** [comment]
I think that the bug originates here: https://github.com/vaadin/hilla/blob/main/packages/ts/generator-typescript-cli/bin/index.js.

This file will be used to launch the TypeScript generator, and it clearly requires `node` on PATH.

So, at the moment, `node` installed is a requirement for Hilla. It would be a great improvement to be able to use the downloaded version of Node.js if available.

**Comment by Artur-** [comment]
How is that file launched on Windows? There is no `/usr/bin/env` there

Should it instead find the installed/used Node using the existing `FrontendTools`  and launch `/path/to/node index.js` ?

**Comment by cromoteca** [comment]
It is run by `cmd.exe`: https://github.com/vaadin/hilla/blob/55aa88795b4520939800ca9801e21fa4a1e00f33/packages/java/engine-core/src/main/java/dev/hilla/engine/GeneratorShellRunner.java#L35

**Comment by Lodin** [comment]
Do we really need to worry about NodeJS presence if the documentation suggests downloading the Hilla template via the following command?
```
npx @vaadin/cli init my-hilla-app
```
Basically, the chance to face this problem is pretty small. And for CI it could be easily fixed by adding Node installation to the CI initialization.

**Comment by Artur-** [comment]
For those start a project with npx — totally not an issue

For those developers who start working on an existing project (hired, joined project, etc) - one less thing to worry about. 

You still have both frontend devs, who probably have node installed, and java devs, who probably do not have it. Then maybe testers who do not know what it is etc

**Comment by cromoteca** [comment]
Good points. Let me add that in the applications logs you see "downloading node 18 since you don't have it", then you see it used, and finally you get "node not found". That's bad.

**Comment by Artur-** [comment]
This could also be fixed by adding the auto installed location to PATH instead of running the script in another way
