### ISSUE TITLE
Typescript files are not updated

### ISSUE THREAD

**Issue by Artur-** [vaadin/hilla#791]
### Description of the bug 
When editing the endpoint Java file and saving it, the generated TypeScript file does not change.

### Minimal reproducible example
1. `hilla init hilla-endpoints --next`
2. Open in IDE
3. Launch Application class
4. Edit endpoint

### Expected behavior
The TS file is updated so you can call the updated method

### Actual behavior
The TS file is not updated. After a manual server restart, it is updated

### Versions:
    - Vaadin / Hilla version: 2 beta 5

**Comment by cromoteca** [comment]
AFAIK Spring Boot monitors changes to compiled classes, so make sure a build is triggered in your IDE when you edit sources.

**Comment by Artur-** [comment]
There is no problem with classes or the Java part. Only that the TS is not updated

**Comment by cromoteca** [comment]
When classes are built, the Spring Dev Tools should trigger a reload, which in turn runs the generator again.

**Comment by Artur-** [comment]
Oh it runs
```
2023-02-27T14:06:30.593+02:00  INFO 43081 --- [onPool-worker-3] dev.hilla.parser.core.Parser             : JVM Parser started
2023-02-27T14:06:30.593+02:00  INFO 43081 --- [onPool-worker-3] dev.hilla.parser.core.Parser             : Search for endpoints in directories [/Users/artur/test/hilla-endpoints/target/classes]
2023-02-27T14:06:30.601+02:00  INFO 43081 --- [onPool-worker-3] dev.hilla.parser.core.Parser             : JVM Parser finished successfully
2023-02-27T14:06:30.614+02:00  INFO 43081 --- [  restartedMain] dev.hilla.EndpointRegistry               : Registered endpoint 'HelloWorldEndpoint' with class 'class com.example.application.endpoints.helloworld.HelloWorldEndpoint'
2023-02-27T14:06:30.618+02:00  INFO 43081 --- [  restartedMain] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 59969
INFO (tsgen): Output directory: /Users/artur/test/hilla-endpoints/frontend/generated
INFO (tsgen): Plugins: BackbonePlugin, ClientPlugin, BarrelPlugin, ModelPlugin, PushPlugin
DeprecationWarning: 'createParameterDeclaration' has been deprecated since v4.8.0. Decorators have been combined with modifiers. Callers should switch to an overload that does not accept a 'decorators' parameter.
DeprecationWarning: 'createFunctionDeclaration' has been deprecated since v4.8.0. Decorators are no longer supported for this function. Callers should switch to an overload that does not accept a 'decorators' parameter.
DeprecationWarning: 'createImportDeclaration' has been deprecated since v4.8.0. Decorators are no longer supported for this function. Callers should switch to an overload that does not accept a 'decorators' parameter.
DeprecationWarning: 'createExportDeclaration' has been deprecated since v4.8.0. Decorators are no longer supported for this function. Callers should switch to an overload that does not accept a 'decorators' parameter.
DeprecationWarning: 'createExportAssignment' has been deprecated since v4.8.0. Decorators are no longer supported for this function. Callers should switch to an overload that does not accept a 'decorators' parameter.
INFO (tsgen) <BarrelPlugin>: Generating 'endpoints.ts' file
2023-02-27T14:06:30.967+02:00  INFO 43081 --- [onPool-worker-3] dev.hilla.engine.GeneratorShellRunner    : The Generator process finished with the exit code 0
```

but the file is not updated

**Comment by Artur-** [comment]
Seems like `target/classes/dev/hilla/openapi.json` is not updated

**Comment by cromoteca** [comment]
When the parser inspect the `Class<?>` associated to the modified endpoint, it still gets the old one. The easiest solution I can think of is to run Maven again each time to get fresh classes. This is something we tried to avoid, but when we did that we were using ClassGraph to inspect classes, now we use Jackson and reflection.

**Comment by Artur-** [comment]
It runs after Spring Boot has restarted, how can it find the old class?

**Comment by cromoteca** [comment]
I verified that:
- the .class file is recompiled and updated
- the class is loaded from that .class file
- the class is unaware of the new parameter method I added

**Comment by Artur-** [comment]
Where in the code is the class read?

**Comment by cromoteca** [comment]
https://github.com/vaadin/hilla/blob/9c7dff0dde5d6ccba736704806179ab3c414d996/packages/java/parser-jvm-plugin-backbone/src/main/java/dev/hilla/parser/plugins/backbone/EndpointPlugin.java#L31 for the method parameters

**Comment by Artur-** [comment]
Looks like you are using the AppClassLoader when you should be using the RestartClassLoader. I wonder where that comes from

**Comment by platosha** [comment]
AFAIK we use the class loader obtained from `Options.classFinder`.

**Comment by Artur-** [comment]
I wonder if `Thread.currentThread().getContextClassLoader()` is what should be used. The Flow/Hilla classes do not seem to be loaded with the restart class loader ever

**Comment by platosha** [comment]
Probably. I suggest that we fix `Options.classFinder` to use it then.

**Comment by Artur-** [comment]
Yeah the real problem is here https://github.com/vaadin/flow/blob/80745115637b454dc7b04cb16fd3f5163b8554a8/flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ClassFinder.java#L66

The list of classes passed to the `ClassFinder` uses different class loaders and the finder will grab one of the class loaders randomly

**Comment by Artur-** [comment]
... or then the problem is that the classes are loaded with different class loaders..

**Comment by Artur-** [comment]
Let's see what https://github.com/vaadin/flow/pull/16063 says

**Comment by Artur-** [comment]
The PR at least fixes this problem
