### ISSUE TITLE
Implement a better handling of external process launch (mvn and node)

### ISSUE THREAD

**Issue by cromoteca** [vaadin/hilla#823]
The Hilla generator needs to execute both Maven and Node. Running them is handled in different classes. This could be unified by extracting a process launcher which handles common functionalities:

- use commands inside the application if available (Maven Wrapper or Node download by Flow);
- use platform-dependent commands (Windows or UNIX-like);
- make sure that the chosen command can be executed correctly, like in case of missing execution permissions (can be done by running a test command like `mvn -v`);
- handle special characters, like spaces in #822.

**Comment by Legioth** [comment]
Maven is just Java so I wonder if it would make more sense to instead refactor the Java code that runs through Maven so that it could instead run directly in the JVM where Hilla itself runs. This would avoid weirdness such as documenting that Gradle users needs to have some specific version of Maven installed on their system and in the PATH.

**Comment by cromoteca** [comment]
The problem is that the generator expects to be configured through Maven. To avoid running Maven, that configuration should happen elsewhere.
Gradle is not a concern: when we'll add support for it, Gradle projects will be configured in `build.gradle` and will run it instead of Maven.

**Comment by Legioth** [comment]
It's our code so we can refactor it to be configured in whatever way makes most sense for us. I assume we already have most of that in place on the Flow side so that could maybe be reused?

**Comment by cromoteca** [comment]
Actually, the configuration I'm talking about is to be made by developer using Hilla. If we change how it happens, it is a breaking change.

**Comment by Legioth** [comment]
We can keep reading configuration from `pom.xml` for Maven users as a deprecated fallback even if we also add a new way of configuring that works the same regardless of whether you're using Maven, Gradle or just running the `main` method straight from your IDE.
