### ISSUE TITLE
Client side validators not generated in model for hilla 2.0

### ISSUE THREAD

**Issue by aspan** [vaadin/hilla#830]
### Description of the bug 
Client side validators not generated in model for hilla 2.0

### Minimal reproducible example
* Check out the basics tutorial project
  `git clone https://github.com/vaadin/hilla-basics-tutorial.git`
* Reset the branch to hilla 1.2.7
  `git reset --hard 1804c05a91fd7e37131df59edeec64e395d45844`
* Set the execute permission for the mvnw script
  `chmod +x mvnw`
* Run the project
  `./mvnw`

The `TodoModel` contains the expected validator

* Reset the branch to hilla 2.0
  `git reset --hard HEAD` followed by `git pull`
* Run the project
  `./mvnw`

The `TodoModel` does not contain the expected validator

### Expected behavior
The model should have a NotBlank validator for the task property.

```
export default class TodoModel<T extends Todo = Todo> extends ObjectModel<T> { 
  static createEmptyValue: () => Todo;

  get id(): NumberModel {
    return this[_getPropertyModel]('id', NumberModel, [true]);
  }

  get done(): BooleanModel {
    return this[_getPropertyModel]('done', BooleanModel, [false]);
  }

  get task(): StringModel {
    return this[_getPropertyModel]('task', StringModel, [true, new NotBlank()]);
  }
}
```

### Actual behavior
The model does not have a NotBlank validator for the task property.

```
class TodoModel<T extends Todo_1 = Todo_1> extends ObjectModel_1<T> {
    declare static createEmptyValue: () => Todo_1;
    get done(): BooleanModel_1 {
        return this[_getPropertyModel_1]("done", BooleanModel_1, [false]) as BooleanModel_1;
    }
    get id(): NumberModel_1 {
        return this[_getPropertyModel_1]("id", NumberModel_1, [true]) as NumberModel_1;
    }
    get task(): StringModel_1 {
        return this[_getPropertyModel_1]("task", StringModel_1, [true]) as StringModel_1;
    }
}
```

### Versions:
    - Vaadin / Hilla version: 2.0
    - Node version: v18.14.2
    - Java version: 17.0.6
    - OS version: Mac OS Ventura 13.2.1

**Comment by simasch** [comment]
This is a huge blocker! https://github.com/vaadin/hilla/issues/852

Please fix ASAP.

**Comment by simasch** [comment]
As a workaround having the Bean Validation annotations on the getter works.
