### ISSUE TITLE
Combination of Bean Validation only one constraint is working

### ISSUE THREAD

**Issue by simasch** [vaadin/hilla#853]
If I use more than one constraint annotation only one is working 

```java
@Email
@NotBlank
private String email;
```

In this case only NotBlank is checked

**Comment by simasch** [comment]
Hilla 1.3 and Hilla 2 are affected

**Comment by platosha** [comment]
Hello. I'm unable to reproduce this issue now. Also we seem to had this supported back in 1.3, there were tests asserting multiple constraints for both parser and generator.

Here is a PR with IT test case for this, based on the ongoing fixes for the #830: https://github.com/vaadin/hilla/pull/868

If this still occurs, could you, please, provide a full class example code?

**Comment by simasch** [comment]
Indeed it is working! I assume that the problem was the same as https://github.com/vaadin/hilla/issues/830 and I misinterpreted the generated output.
