### ISSUE TITLE
Browser gets stuck showing "Building front-end development bundle" 

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/hilla#867]
### Description of the bug 
Often, when running a Hilla 2.0.2 app, the browser gets stuck displaying "Building front-end development bundle"  even though the build is complete. 
<img width="516" alt="Screenshot 2023-03-30 at 08 01 27" src="https://user-images.githubusercontent.com/883698/228932323-0573c3d8-9d14-49c8-8070-8b649e917cbf.png">

### Minimal reproducible example
```
npx @hilla/cli init --react app
cd app
mvn
```
### Expected behavior
The app is displayed when the front-end bundle is built. 

### Actual behavior
Sometimes it isn't.  The following errors are shown in the console. 

<img width="714" alt="Screenshot 2023-03-30 at 11 34 32" src="https://user-images.githubusercontent.com/883698/228932874-7b5b6749-3881-45e0-8cd5-3d8576636de3.png">

### Versions:
    - Vaadin / Hilla version: 2.0.2
    - Node version: 19.5
    - Java version: 17
    - OS version: MacOS 13.3
    - Browser version (if applicable): Chrome latest

**Comment by Artur-** [comment]
This should have been fixed by https://github.com/vaadin/flow/pull/16638
