### ISSUE TITLE
Add support for lazy loading of stylesheets

### ISSUE THREAD

**Issue by egloffmark** [vaadin/hilla#888]
Looking at the current [documentation for theme and styling,](https://hilla.dev/docs/css/styling-with-css) I noticed that you need to "@import" all CSS files for your views and components. This will load all stylesheets already at the beginning and will slow down the start of the application. I think a lazy-loading would be better, so the required stylesheets for views and components will only be downloaded when needed. 

Also the lit framework seems not to support a kind of lazy loading for stylesheets. You can  with `import`and `static styles = [...]` refer to  own *.css files (see [here](https://lit.dev/docs/components/styles/)), but these will be injected into the main page.  

 Therefore I like to request for such a lazy-loading feature.

**Comment by Artur-** [comment]
What happens if you do a dynamic import of a css file in e.g. a click listener? Something like
`@click=${() => import(’./viewstyles.css’)`?

**Comment by Artur-** [comment]
… and add ?inline and get the result from the import, if you need it inside a shadow root

**Comment by egloffmark** [comment]
Regarding "inline". A `static styles = css ` seems not to be supported by Hilla for "Views". i.e. the following get ignored
```
import { html,css } from 'lit';
import { customElement, query, state } from "lit/decorators.js";

@customElement("my-view")
export class MyView extends View {
  static styles = css`div { border: 2px grey red;}`;
  render() {
    return html `<div> my View </div>`;
  }
}
```
If I use a normal lit component then it gets applied
```
import { css, html, LitElement } from "lit";
import { customElement, query, state } from "lit/decorators.js";

@customElement("my-component")
export class MyComponent extends LitElement {
  static styles = css`div { border: 2px grey red;}`;
  render() {
    return html `<div> my View </div>`;
  }
}
```
Any idea?

**Comment by egloffmark** [comment]
The `?inline` seems not to work, here the Typescript comes up with an error

```
@customElement('my-view')
export class MyView extends View {
	
	connectedCallback() {
   		super.connectedCallback();
		import('./my-view.css?inline');
	}
	render() {
		return html`<div> My View</div>`;
	}
}
```
```
ERROR(TypeScript)  Cannot find module './my-component-view.css?inline' or its corresponding type declarations.
```

**Comment by Artur-** [comment]
If you take the default starter and add `frontend/views/helloworld/hello-world-view.css`: 
```css
vaadin-button {
    background: blue;
    color: white;
}
```
and in `sayHello` in `hello-world-view.ts` add:
```
    import("./hello-world-view.css");
```

then the css is loaded, applied globally and the button turns blue when you click it

**Comment by Artur-** [comment]
For LitElements with a shadow root, you can use the standard way to add css https://lit.dev/docs/components/styles/#add-styles. When written inside the TS file for the component, they will be loaded with the component (view). So if you lazy load that, you also lazy load the styles

**Comment by egloffmark** [comment]
Ok and how can I enforce a  lazy loading of a "View"? I noticed when I add the view  as import to "routes.ts" it will be loaded although it is not yet required.

```
import type { Route } from '@vaadin/router';
import './views/my-view/my-view'
import './views/my-2nd-view/my-2nd-view'

...

export const routes: ViewRoute[] = [
  {
    path: '',
    component: 'my-view'
  },
  {
    path: '2nd',
    component: 'my-2nd-view'
  },
];
```

**Comment by Artur-** [comment]
Like about view is loaded in the default starter
```
  {
    path: 'about',
    component: 'about-view',
    icon: 'file',
    title: 'About',
    action: async (_context, _command) => {
      await import('./views/about/about-view.js');
      return;
    },
  },
```

**Comment by egloffmark** [comment]
Thank you, this works. 

any example how to get the `?inline` working?

**Comment by Artur-** [comment]
What would be the use case for it here? If you import with ?inline then you need to get the css text from the import and do something with it manuelly

**Comment by egloffmark** [comment]
I just like to understand how the code would like, just for learning purpose.

**Comment by Artur-** [comment]
With a `LitElement` if you want to use an external CSS file, you can do
```

import helloWorldStyles from "./hello-world-view.css?inline";
...
@customElement("hello-world-view")
export class HelloWorldView extends Layout {
...
  static get styles() {
    return helloWorldStyles;
  }

```

Then the CSS will be only placed in a variable named `helloWorldStyles` and not applied globally. Because of the way Vite is set up, the result will be a lit `CSSResultGroup` that you can use directly with `static get styles`.

**Comment by Artur-** [comment]
If you want to do something really dynamic, you can also do
```
  async sayHello() {
    const cssImport = await import("./hello-world-view.css?inline");
    Notification.show("the css is: " + cssImport.default.toString());
```

Both of these `?inline` imports require either `//@ts-ignore` or adding
```
declare module '*.css?inline' {
  import { CSSResultGroup } from 'lit';
  const content: CSSResultGroup;
  export default content;
}
```
to `types.d.ts` for TypeScript to understand what is going on

**Comment by egloffmark** [comment]
Thank you, really appreciated! It worked.  Especially the  `declare module '*.css?inline'` this I had forgotten to add.

**Comment by platosha** [comment]
As discussed, this seems to be generally supported, but TypeScript definition is missing. Let me close this in favour of #890 focusing on `types.d.ts` specifically.
