### ISSUE TITLE
When to use "View" instead of just "LitElement"?

### ISSUE THREAD

**Issue by egloffmark** [vaadin/hilla#889]
I noticed that when you use for the views the base class "LitElement" the provided examples will also work. So when is the "View" instead of "LitElement" preferred or to be used?

```
import { View } from '../view';
export class MyView extends View { ... }
```

```
import { html,css, LitElement } from 'lit';
export class MyView extends LitElement { ... }
```

**Comment by Artur-** [comment]
`View` is a `LitElement` without a shadow root
`Layout` is a `LitElement` with a shadow root that supports mobx and injects the application theme into the shadow root

**Comment by egloffmark** [comment]
Thank you for the clarification.
