### ISSUE TITLE
Login using stateless authentication does not work in a new starter project with 2.1 alpha4

### ISSUE THREAD

**Issue by Artur-** [vaadin/hilla#910]
### Description of the bug 

Login in a starter project does not work when using stateless authentication. Any login attempt results in
```
Invalid CSRF token found for http://localhost:8080/login
```

This is related to https://github.com/vaadin/flow/pull/16521 which causes the CSRF written to the index page to be XOR:ed. To my understanding, the CSRF should not be written at all to the page when you use stateless auth. However, when logging in, the CSRF from the page is automatically used by the login component: https://github.com/vaadin/web-components/blob/45cdb78cac837227eafb3fa4a750a5ae632ed704/packages/login/src/vaadin-login-form.js#L163-L168 if it is available and there is no other code that would add the correct CSRF instead

### Minimal reproducible example
```
npx @hilla/cli init --pre --auth hilla-auth
cd hilla-auth
mvn
```

### Expected behavior
You can log in by entering "user" and "user"

### Versions:
    - Vaadin / Hilla version: 2.1 alpha4

**Comment by joekrom** [comment]
`@Endpoint
@AnonymousAllowed
public class MyEndpoint {

 public String hello(String first, String key) {
        return "Hello " + first + " " + key;
    }
  
}`

> error message:  "dev.hilla.auth.EndpointAccessChecker - Unable to verify CSRF token for endpoint request, got null token in cookie"  when trying trying to access the endpoint
