### ISSUE TITLE
NonNullApi does not work for a child package if called by "hilla:generate"

### ISSUE THREAD

**Issue by Lodin** [vaadin/hilla#921]
### Description of the bug 
If `@NonNullApi` is applied to a package that isn't mentioned by any endpoint or entity, it does not affect any child package. E.g., if applied to `com.example.application` it does not make `com.example.application.endpoints.helloworld` non-nullable unless the child imports any class from `com.example.application` scope.

It happens because during the goal execution `com.example.application` is considered undefined, and is filtered at [ClassInfoReflectionModel#228](https://github.com/vaadin/hilla/blob/main/packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/ClassInfoReflectionModel.java#L228).

### Minimal reproducible example
1. Create a new project via `npx @hilla/cli init`.
2. Create `package-info.java` in `com.example.application` and apply `@NonNullApi` to `com.example.application` package.
3. Remove all `@Nonnull` annotations in `com.example.application.endpoints.helloworld.HelloWorldEndpoint` class.
4. Run `mvn compile hilla:generate`. 

### Expected behavior
The generated endpoint methods should not have nullable elements.

### Actual behavior
The generated endpoint methods are nullable like no `@NonNullApi` is applied. 

### Versions:
    - Hilla version: 2.1-SNAPSHOT
    - Node version: 8.15.0
    - Java version: 17
    - OS version: Windows 11

**Comment by cromoteca** [comment]
A possible solution to improve the search for `@NonNullApi` in ancestors could be to try to load `package-info.class` as a resource for each parent package. This way, Java is forced to search for that resource, no matter if the package is loaded or not. Then we need to find a way to inspect if the annotation is there. The brute-force solution is to do a text search (should be UTF-16). For me, if the `NonNullApi` text is there, there's little room for mistakes. But of course it is possible to use tools like ASM to analyze the bytecode properly if we want to be 100% sure.

**Comment by platosha** [comment]
Contrary to the expectation here, the [API description of Spring Data's `NullabilityUtils`](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/util/NullableUtils.html) says:

> Subpackages do not inherit nullability rules and must be annotated themself.

It seems that this is a design limitation rather than a bug.
