### ISSUE TITLE
Validation imports not working from javax.validation 

### ISSUE THREAD

**Issue by ahsinsiddique** [vaadin/hilla#951]
documentation pages need to be updated. 
<img width="698" alt="Screenshot 2023-05-14 at 10 00 31 PM" src="https://github.com/vaadin/hilla/assets/20045689/84647dfe-b7d9-438c-8d0b-b4bb950ab15f">

these imports are working, instead of documentation one's 
https://hilla.dev/docs/tutorials/quickstart

```
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
```

**Comment by tarekoraby** [comment]
We should find and replace all javax namespaces in the doc.

**Comment by platosha** [comment]
This was an old revision of the documentation, should be updated by now. Note that the URLs changed.
