### ISSUE TITLE
Improve the init-app feature

### ISSUE THREAD

**Issue by cromoteca** [vaadin/hilla#961]
After https://github.com/vaadin/hilla/pull/952 has been merged, let's keep improving it:
- rename `hilla-plugin-base` to `plugin-base`: https://github.com/vaadin/hilla/pull/952#discussion_r1196059573
- improve scanning: https://github.com/vaadin/hilla/pull/952#discussion_r1196035466
- consider making helper static: https://github.com/vaadin/hilla/pull/952#discussion_r1196030945
- consider renaming it: https://github.com/vaadin/hilla/pull/952#discussion_r1196028961

**Comment by platosha** [comment]
The Gradle command does not provide any output, whereas the Maven one prints the list of files created. Something to further improve in Gradle plugin maybe.
