### ISSUE TITLE
Autowiring in Validators in Hilla Endpoint DTO Validation

### ISSUE THREAD

**Issue by gitgdako** [vaadin/hilla#964]
### Description of the bug 
When annotating a DTO which is submitted to an Endpoint with a Custom Constraint Validator that DTO is validated by dev.hilla.EndpointInvoker#validator. That works as expected. If that Validator has an @Autowire dependency it is not resolved and is therefore null.

### Minimal reproducible example
Call any endpoint with any DTO. That DTO is annotated by a custom constraint with a custom validator with an @Autowire dependency

### Expected behavior
The dependency is resolved and therefore not null

### Actual behavior
That dependency is not resolved according to Spring Spec

### Versions:
    - Vaadin / Hilla version: 1.2.10
    - Node version: 18.15.0
    - Java version: 1.8.0_352
    - Application Server (if applicable): Spring 2.7.0

### Working with spring
If you call a Spring service with org.springframework.validation.annotation.Validated and the same DTO as parameter with javax.validation.Valid [0] spring resolves the dependency as expected.

### Hibernate workaround
Hibernate has the same problem which we fixed by implementing a custom org.springframework.context.annotation.Configuration which returns a factory org.springframework.context.annotation.Bean that implements org.springframework.beans.factory.config.AutowireCapableBeanFactory

### Private Repo
As always we have shared a reproducer example in our private repo

[0]
@Validated
public class Service {
    public void serviceCall(@Valid final IEntity2 entity2) {

**Comment by platosha** [comment]
Thanks for reporting and ideas for the implementation. This seems to be a missing feature rather than a bug, so marking as such.
