### ISSUE TITLE
Mono return types are handled incorrectly

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/hilla#965]
### Description of the bug 
Returning a Mono from an endpoint generates an incorrect TS signature.

### Minimal reproducible example
```java
public Mono<ChatCompletionMessage> getCompletion(List<ChatCompletionMessage> history) {
    return docsAssistantService.getCompletion(history);
}
```

Generates 
```ts
async function getCompletion_1(history: Array<ChatCompletionMessage_1>, init?: EndpointRequestInit_1): Promise<Mono_1> { return client_1.call("DocsAssistantEndpoint", "getCompletion", { history }, init); }
```

### Expected behavior
I would expect the return value to be of type `ChatCompletionMessage` and that I can await the value on the client, i.e. it should work identically to just returning the type itself. 

### Actual behavior
See above. 

### Versions:
    - Vaadin / Hilla version: 2.0.5

**Comment by cromoteca** [comment]
There's no support for `Mono` at the moment, so I think this would be an enhancement, not a bug.

It could be simply replaced by its wrapped type like you suggest, return a `Subscription` like `Flux`, or even something more specific like a different subscription type that cancels automatically after the value is received.

**Comment by Artur-** [comment]
#399

**Comment by marcushellberg** [comment]
Closing in favor of the ticket @Artur- already made earlier
