### ISSUE TITLE
Basic tutorial TodoView not working as expected in screenshot

### ISSUE THREAD

**Issue by ahsinsiddique** [vaadin/hilla#968]
Default behaviour, 
i.e string interpolation not working  inside Checkbox

<img width="506" alt="Screenshot 2023-05-22 at 12 59 10 AM" src="https://github.com/vaadin/hilla/assets/20045689/0521f334-2b7e-43e4-b32c-0df8cd3bbf21">

When we try to put string outside of Checkbox then we see string data
 <span>{todo.task}</span> 
<img width="544" alt="Screenshot 2023-05-22 at 1 01 50 AM" src="https://github.com/vaadin/hilla/assets/20045689/d69c7a71-e8af-408f-82c0-9cf25c59cccb">

https://hilla.dev/docs/react/start/basics

**Comment by platosha** [comment]
Indeed, the checkbox does not support child content.

The correct way is to give the `label` prop:

```tsx
<Checkbox label="string" />
```

Let's fix the documentation about this.
