### ISSUE TITLE
PiT 24.1: error compiling hilla start application with authentication in prod-mode

### ISSUE THREAD

**Issue by manolo** [vaadin/hilla#970]
### Description of the bug 
When downloading and compiling a new hilla application with authentication it fails during ts compilation in prod-mode and not in dev.mode.

Error in logs is: 

```
[ERROR] vite v4.3.5 building for production...
[ERROR] transforming...
[ERROR] frontend/views/login/login-view.ts(15,3): error TS2739: Type '{ title: string; message: string; }' is missing the following properties from type '{ title: string; message: string; username: string; password: string; }': username, password
[ERROR] ✓ 452 modules transformed.
```
### Minimal reproducible example
1. Download a new app from start
```
curl -s -f 'https://start.vaadin.com/dl?&preset=latest-lit&projectName=latest-lit' -o latest-lit.zip
unzip latest-lit.zip
cd latest-lit
```
2. Change hilla.version from 2.0.3 to 2.1.0.alpha2
4. Add pre-releases repository
```
<pluginRepositories><pluginRepository><id>v</id><url>https://maven.vaadin.com/vaadin-prereleases/</url></pluginRepository></pluginRepositories>
<repositories><repository><id>v</id><url>https://maven.vaadin.com/vaadin-prereleases/</url></repository></repositories>
```
5.  Run and compile in dev-mode, it works
```
./mvnw 
```
7. Compile it for production, it fails
```
./mvnw  clean
./mvnw  -Pproduction package 
```
### Expected behavior
It compiles and run
### Versions:
    - Vaadin / Hilla version: 24.1.0.beta1 / 2.1.0.beta1

**Comment by Artur-** [comment]
You see the error in the console also for dev mode. Login-view has added two new translation properties in 24.1

**Comment by platosha** [comment]
While we can fix the starter, I think it would be preferred that the new properties are optional in the login form component. This way the users won't be required to address this breaking change when migrating.

**Comment by platosha** [comment]
Fixed in the component by https://github.com/vaadin/web-components/pull/5886
