### ISSUE TITLE
Icons are not shown as they are requested from /VAADIN/build/ instead of context-root in Production

### ISSUE THREAD

**Issue by taefi** [vaadin/hilla#971]
### Description of the bug 
When running a Hilla application project that is built for production, the icons are not rendered since they are requested from the `/VAADIN/build/` and not from the context root. The same thing works fine in development mode.

### Minimal reproducible example
Any starter project can be built for production and running from the jar archive shows the problem.

### Expected behavior
Expect to see the icons. 
The underlying behavior expectation is for the icons to be requested from context-root not from `/VAADIN/build/` in production mode. 

### Versions:
    - Vaadin / Hilla version: v2.0.5 and v2.1.0.beta1
    - Node version: v18.15.0
    - Java version: 17
    - OS version: macOS
    - Browser version (if applicable): Chrome/Firefox

**Comment by cromoteca** [comment]
I can reproduce as follows:
```bash
npx @hilla/cli init --next --react my-app
cd my-app
mvn # I can see the icons in the menu
mvn clean package -Pproduction
java -jar target/my-app-1.0-SNAPSHOT.jar # I cannot see the icons in the menu
```

**Comment by cromoteca** [comment]
Flow uses `generated-flow-imports.js` to serve those icons. That file is created in `build-frontend`, but not for Hilla.
