### ISSUE TITLE
How to configure path for auth secret

### ISSUE THREAD

**Issue by egloffmark** [vaadin/hilla#992]
The demo project "hilla-with-auth" comes with a config file where the application secret is stored for stateless JWT authentication. By default is set to path "config/secrets/application.properties". See also basic documentation
https://hilla.dev/docs/lit/guides/security/intro
https://hilla.dev/docs/lit/guides/security/spring-stateless

 I like to know

- how this file path can be configured and if it can be changed?
- how it supports different environments? Does it behave similar as spring boot means it searches for "application-{profile}.properties" ?
- does it also support "*.yaml" files?

Thank you

**Comment by Artur-** [comment]
It is basically a normal application.properties, see https://docs.spring.io/spring-boot/docs/3.1.0/reference/htmlsingle/#features.external-config.files

**Comment by egloffmark** [comment]
Ok thank you that helped.
