### ISSUE TITLE
Consider always scaning current project/module root package for endpoints

### ISSUE THREAD

**Issue by taefi** [vaadin/hilla#994]
Currently, the packages from current project (or current module of a multi-module project) is scanned for endpoints, only if there is no configuration for the exposed packages from dependencies (or other modules). If the user configure the maven/gradle plugin to scan and include a single external endpoint from some dependency (e.g. SSO Kit), then they should also always list the a high-level package from the current project/module which is not convenient and redundant IMO.

Configuring the for exposed packages from other modules or from dependencies should not affect the parser behavior for scanning the packages in the current project (or current module of a multi-module project), as most of the times, the use case is to use some external utility endpoints, and not to hide the endpoints of the current project/module. 

We should consider always scanning the current project/module's packages, plus the additional exposed packages from the dependencies or other modules.

**Comment by platosha** [comment]
Sounds like a good idea. However note that the actual scanning happens for the compiled files in the `target`/`build` directories, not for the source.

**Comment by taefi** [comment]
> Sounds like a good idea. However note that the actual scanning happens for the compiled files in the `target`/`build` directories, not for the source.

Thanks for the input. Updated the wording in the title and description.
